### ISSUE TITLE
naming of numpy based deterministics functions

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#10]
Many of the deterministic functions have the same names as numpy functions and builtins. I imagine this can cause problems sometimes. It has already caused one internal problem (with any() conflicting with builtin any()). The best way to deal with this seems to me to move them into a subpackage, but I am not sure what name it should have. Suggestions?

**Comment by fonnesbeck** [comment]
We could simply capitalize them, but that would be pretty un-pythonic for functions.

I think isolating them into a file that is not automatically imported by **init** should do the trick. We should probably get rid of the \* import convention everywhere in the codebase. I think (hope) it is isolated in the examples.

**Comment by apatil** [comment]
How about 'dfuncs'?

**Comment by jsalvatier** [comment]
That seems pretty good. I'll go with that for now.
