### ISSUE TITLE
revert_to_max() fails for NormApprox fits?

### ISSUE THREAD

**Issue by thommevans** [pymc-devs/pymc3#109]
**What steps will reproduce the problem?

Simply perform a NormApprox fit for one of the built-in examples. For example:

> > import pymc
> > from pymc.examples import gelman_bioassay
> > N = pymc.NormApprox(gelman_bioassay)
> > N.fit()
> > N.revert_to_max()

**What is the expected output? What do you see instead?

I would expect N.alpha.value and N.beta.value to revert to the MAP solution values (i.e. those stored in N._mu). Instead, I get:

/usr/local/scisoft/packages/python/lib/python2.6/site-packages/pymc/NormalApproximation.py in revert_to_max(self)
    444         Sets all N's stochastics to their MAP values.
    445         """
--> 446         self._set_stochastics(self.mu)
    447 
    448 

/usr/local/scisoft/packages/python/lib/python2.6/site-packages/pymc/NormalApproximation.py in _set_stochastics(self, p)
    339                 stochastic.value = round_array(reshape(ravel(p)[self._slices[stochastic]],shape(stochastic.value)))
    340             else:
--> 341                 stochastic.value = reshape(ravel(p)[self._slices[stochastic]],shape(stochastic.value))
    342 
    343     def __setitem__(self, index, value):

/usr/local/scisoft/packages/python/lib/python2.6/site-packages/pymc/PyMCObjects.pyc in set_value(self, value, force)
    602 
    603         if self.dtype.kind != 'O':
--> 604             self._value = asanyarray(value, dtype=self.dtype)
    605             self._value.flags['W']=False
    606         else:

/usr/local/scisoft/packages/python/lib/python2.6/site-packages/numpy/core/numeric.pyc in asanyarray(a, dtype, order)
    334 
    335     """
--> 336     return array(a, dtype, copy=False, order=order, subok=True)
    337 
    338 def ascontiguousarray(a, dtype=None):

ValueError: setting an array element with a sequence.

> /usr/local/scisoft/packages/python/lib/python2.6/site-packages/numpy/core/numeric.py(336)asanyarray()
>     335     """
> --> 336     return array(a, dtype, copy=False, order=order, subok=True)
>     337 

**What version of the product are you using? On what operating system?

pymc version 2.1alpha on Mac OS X 10.6.8.

Please provide any additional information below.

I get the expected behaviour if I replace the self._set_stochastics(self.mu) call with self._set_stochastics(self._mu) inside the revert_to_max() definition. Could this be a simple bug and that's all that needs to change (in which case I thought I'd bring it to your attention, because I see that the revert_to_max definition is the same in version 2.1beta), or am I missing something? Thanks for any help!

**Comment by fonnesbeck** [comment]
Thanks for the report. Fixed in 1f1bd50910ecc23e0a708f189998fe891a8a349e -- please test.

**Comment by thommevans** [comment]
Thanks - that seems to have done the trick.
