### ISSUE TITLE
Float comparison in categorical

### ISSUE THREAD

**Issue by borisaqua** [pymc-devs/pymc3#11]
categorical_like checks if vector of probabilities sums to one (Ln 849 in distributions.py) and prints out the vector if test fails. If the sum is slightly off this results in a massive text output and slowdown. Should the exact comparison be replaced with approximate (abs(np.sum(p, 1)-1)<0.00001)?

**Comment by fonnesbeck** [comment]
Fixed in 9ad5767ea331e15b737808255924fe06de853222. Thanks.
