### ISSUE TITLE
MathJax Out-Of-Date

### ISSUE THREAD

**Issue by tshauck** [pymc-devs/pymc3#113]
On the document page MathJax isn't rendering properly.  It throws a (very ugly) error, and makes any of the markup display as it would appear w/o MathJax.

[Docs](http://readthedocs.org/docs/pymcmc/en/latest/README.html)

[Pic](https://s3.amazonaws.com/trent_testbucket/Screen+Shot+2012-05-04+at+10.32.31+PM.png)

**Comment by fonnesbeck** [comment]
Thanks for the report. Unfortunately, that is not our official docs page. In fact, I'm not sure who posted them on readthedocs. Our official docs are hosted here on GitHub:

http://pymc-devs.github.com/pymc/
