### ISSUE TITLE
Model.write_csv ignores variables argument

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#116]
`write_csv` does not honor the `variables` argument, and instead dumps all traced variables to the file.

**Comment by seeslab** [comment]
I am experiencing this problem--is there any way to fix it? Thanks!

**Comment by fonnesbeck** [comment]
Actually, this was fixed in 7fb51890df8b83cb081debe4d34db0b455939895. Did you build PyMC from source, or get it prebuilt from someplace else? Can you post an example of it failing?

**Comment by seeslab** [comment]
Ok. I might have been using an old version of PyMC (2.1beta, I think). Thanks for maintaining this--it's just great!

**Comment by fonnesbeck** [comment]
Glad its useful!

Yes, please build from the current Github master if you can -- it has several bug fixes and feature additions.
