### ISSUE TITLE
Bug with scipy optimization caused by numpy.seterr in testing.

### ISSUE THREAD

**Issue by joezuntz** [pymc-devs/pymc3#117]
The dev version of pymc has a bug which can cause problems running the scipy fmin_powell optimizer.

On import, pymc imports the tests submodule.  tests/**init**.py changes the numpy error settings with numpy.seterr(divide = 'raise', invalid = 'raise').  This change is not reverted later.

When the Brent line search moves outside the prior region it receives an infinite value from pymc, and then this becomes a nan after some operations.  A call to numpy.abs (done in the line search) on this value yields a floating point error.

**Comment by fonnesbeck** [comment]
I have fixed the error settings issue. Let me know if you still have optimizer problems. I did not think we used the Brent search in PyMC.

**Comment by joezuntz** [comment]
Many thanks - that fixes my problem.  Powell's method has a line search step, called _linesearch_powell in scipy/optimize/optimize.py, which is a wrapper around Brent.
