### ISSUE TITLE
flib.normal (and normal_like) returns nan instead of -inf

### ISSUE THREAD

**Issue by borisaqua** [pymc-devs/pymc3#12]
flib.normal (and normal_like) returns nan instead of -inf for very low values, resulting in sampler craching. For example: normal_like(-1e99,1e99,1e999)

Could be fixed by modifying normal_like:
    res = flib.normal(x, mu, tau)
    if np.isnan(res): res = -np.Inf
    return res

**Comment by jsalvatier** [comment]
the numexpr_dist branch (python likelihoods) appears to handle this correctly.

**Comment by apatil** [comment]
Fixed in cfcbd59cdb92208b808185d9d5d8c70b0edd170c, thanks
