### ISSUE TITLE
Matplot.plot error: doanes binning method formula error

### ISSUE THREAD

**Issue by mirage007** [pymc-devs/pymc3#120]
i got an error at the following line
under Matplot.py:line 433

current:
_doanes = lambda data, n: 1 + log(n) + log(1 + (kurtosis(data)_n/6.)_*0.5)

whereas i think it should be:
_doanes = lambda data, n: 1 + log(n) + log(1 + kurtosis(data)_(n/6.)_*0.5)

the double (*) are not showing up very well on my screen, but it's supposed to be raised to the power of 0.5

according to wikipedia:
http://en.wikipedia.org/wiki/Histogram

otherwise this throws an error when the kurtosis is negative.

**Comment by fonnesbeck** [comment]
Should be fixed in the commit above. Thanks for reporting it.
