### ISSUE TITLE
User Guide Links

### ISSUE THREAD

**Issue by binarybana** [pymc-devs/pymc3#121]
PyMC has some of the best documentation I've seen in it's user guide at http://pymc-devs.github.com/pymc/ but for the life of me I can't find a link to this documentation anywhere on the pymc github page.

I'd recommend putting large prominent links to the user guide on the
- Top blurb on the Github code page which currently has a link to the wiki
- Prominently on top of the README
- Prominently on top of the Github Wiki

Keep up the great work!

**Comment by fonnesbeck** [comment]
I have done all three. Thanks for your feedback.
