### ISSUE TITLE
pymc.test() failures...

### ISSUE THREAD

**Issue by pennucci** [pymc-devs/pymc3#122]
Hi-

I recently installed pymc on my linux machine.  I ran pymc.test() a number of times and it would return different failures each time, and then would pass all tests on occasion.  I left the problem alone for a while, but have come back to investigate it again.  Now pymc.test() fails every time with the same error:
# 

Running unit tests for pymc.tests
NumPy version 1.6.1
NumPy is installed in /usr/lib/python2.7/dist-packages/numpy
Python version 2.7.3 (default, Apr 20 2012, 22:44:07) [GCC 4.6.3]
nose version 1.1.2
..F.....Plotting switchpoint
/usr/lib/pymodules/python2.7/matplotlib/axes.py:4257: RuntimeWarning: invalid value encountered in true_divide
  if normed: c/= np.sqrt(np.dot(x,x) \* np.dot(y,y))
Plotting early_mean
Plotting late_mean
....................................S................./usr/local/lib/python2.7/dist-packages/pymc/tests/test_distributions.py:170: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.array(l))
......................./usr/local/lib/python2.7/dist-packages/pymc/tests/test_distributions.py:202: RuntimeWarning: overflow encountered in exp
  like = np.exp(np.array(l))
............................................/usr/local/lib/python2.7/dist-packages/pymc/tests/test_distributions.py:265: RuntimeWarning: overflow encountered in exp
  return sum(exp([like(x,**parameters) for x in np.arange(N)]))
......................................./usr/local/lib/python2.7/dist-packages/pymc/tests/test_utils.py:14: RuntimeWarning: invalid value encountered in sqrt
  C = Lambda('C',lambda b=B: sqrt(b))
# ...

FAIL: Failure: AssertionError (
Items are not equal:
 ACTUAL: 3
##  DESIRED: 0)

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_LazyFunction.py", line 96, in <module>
    assert_equal(L.get_cached_counts()[1,cur_frame], C.counter.get_count())
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 3
 DESIRED: 0

---

Ran 171 tests in 23.915s

FAILED (SKIP=1, failures=1)
# 

Is this actually a problem to worry about?  Thanks!

**Comment by fonnesbeck** [comment]
I cannot replicate this error on OS X. How recent is the build that you are using? 

Some errors will be stochastic, particularly those having to do with testing the distributions, but they should not occur regularly.

**Comment by pennucci** [comment]
I built it on May 22nd, or thereabouts.  I'm rerunning the test suite again, and now it gives me that same error, plus an error in test_random.  Two subsequent attempts gives me that same error, plus an error in test_gradients.

But now a third time shows OK (SKIP=1)...all tests pass, no errors, no failures...these are all hopefully stochastic that won't actually matter?

**Comment by fonnesbeck** [comment]
Should be nothing to worry about. I probably need to adjust the tolerances on some tests.
