### ISSUE TITLE
Google code repository is forbidden?

### ISSUE THREAD

**Issue by jakebiesinger** [pymc-devs/pymc3#123]
When googling for pymc, most of the links (docs, downloads, etc) sit under the Google Code site which is forbidden atm.

Repro:
go to http://code.google.com/p/pymc/

see: 403 forbidden.

Also, the only docs that do work (that I could find) complain about mathjax not specifying a default config file:

site: http://readthedocs.org/docs/pymcmc/en/latest/tutorial.html
message: """MathJax no longer loads a default configuration file; you must specify such files explicitly. This page seems to use the older default config/MathJax.js file, and so needs to be updated. This is explained further at
http://www.mathjax.org/help/configuration"""

**Comment by fonnesbeck** [comment]
Sorry for the confusion. The Google Code site is out of date, and is no longer the home of PyMC, so I have scheduled it for deletion. Hence, it is no longer available. Once it is deleted, the Google search results should improve.  You will see a link to the docs both in the [readme file](https://github.com/pymc-devs/pymc#readme) for this repo and at the top of the wiki page. I have also created a shortened link which is easy to remember: http://bit.ly/pymc_docs

The docs at readthedocs.org were not put there by me, so I have no control over them. You should not get mathjax issues with the official docs on this site.

**Comment by jakebiesinger** [comment]
Gotcha.  In that case, the google code links in README.rst are out of date.  See my pull request ad890b0 for a few fixes that might help the average Googler.  I missed that link entirely, even though I read the README here.
