### ISSUE TITLE
Container initialization has illegal attribute names

### ISSUE THREAD

**Issue by deapplegate** [pymc-devs/pymc3#125]
Hi-

When the ObjectContainer tries to wrap internal containers in Container.py:file_items, it calls replace in such a way that the container has integers for attribute names. This creates a problem, as with the following example:

import pymc, numpy as np
testobjs = np.empty(5, dtype=object)
for i in range(5):
    testobjs[i] = pymc.Uniform('test_%d' % i, 0, 1)

model = pymc.Model([testobjs])
map = pymc.MAP(model)

produces the following backtrace:

---

TypeError                                 Traceback (most recent call last)
/path/<ipython-input-7-ced81cecbb39> in <module>()
----> 1 map = pymc.MAP(model)

/path/pymc/NormalApproximation.pyc in **init**(self, input, eps, diff_order, verbose)
    144             raise ImportError('Scipy must be installed to use NormApprox and MAP.')
    145 
--> 146         Model.**init**(self, input, verbose=verbose)
    147 
    148         # Allocate memory for internal traces and get stochastic slices

/path/pymc/Model.pyc in **init**(self, input, name, verbose)
     90             input = **main**
     91 
---> 92         ObjectContainer.**init**(self, input)
     93 
     94         if name is not None:

/path/pymc/Container.pyc in **init**(self, input)
    554         else: # Modules, objects, etc.
    555             input_to_file = input.**dict**
--> 556             conservative_update(self, input_to_file)
    557             # self.**dict**.update(input_to_file)

/path/pymc/Container.pyc in conservative_update(obj, dict)
    500 def conservative_update(obj, dict):
    501     for k in dict:
--> 502         if not hasattr(obj, k):
    503             try:
    504                 setattr(obj, k, dict[k])

TypeError: hasattr(): attribute name must be string

---

Printing out model.**dict**.keys() gets you:
[0,
 'stochastics',
 'moral_neighbors',
 'verbose',
 'OCValue',
 'variables',
 'observed_stochastics',
 '_value',
 'deterministics',
 'coparents',
 'potentials',
 '__name__',
 'nodes',
 '_dict_container',
 'markov_blanket',
 'containers']
and you see that illegal 0 as an attribute name.

Placing a print statement in ObjectContainer:replace :
   def replace(self, item, new_container, key):
        print '$$$$$ ', item, new_container, key
        dict.**setitem**(self.**dict**, key, new_container)

results in 
  $$$$$  [test_0 test_1 test_2 test_3 test_4] [test_0 test_1 test_2 test_3 test_4] 0
and a 0 for an attribute name in the container dictionary.

I'm not sure what the code is supposed to be doing here, otherwise I'd offer a fix.

Cheers,
Douglas Applegate

**Comment by fonnesbeck** [comment]
You are mistakenly initializing both a Model object and a MAP object. MAP is a subclass of Model, so you just need to pass the model parameters directly to MAP:

```
import pymc, numpy as np
testobjs = np.empty(5, dtype=object)
for i in range(5):
    testobjs[i] = pymc.Uniform('test_%d' % i, 0, 1)
map = pymc.MAP([testobjs])
```

**Comment by deapplegate** [comment]
But if I'm just given a Model, how can I extract the relevant set of
objects?

And so the integers in place of strings as attribute names is intentional?

On Tue, Jun 12, 2012 at 6:37 PM, Chris Fonnesbeck <
reply@reply.github.com

**Comment by fonnesbeck** [comment]
You can extract them either via:

```
map.containers
```

if you want the Container itself, or 

```
map.stochastics
```

for the Stochastics inside the containers. The integer is intentional, because Containers are typically generated automatically. It is not intended that users employ them as keys to index those objects.
