### ISSUE TITLE
weibull_expval and gamma

### ISSUE THREAD

**Issue by egleave** [pymc-devs/pymc3#128]
I'm new to PYMC, so am not terribly confident that this is true, but it looks like there's a flaw in the distributions code that leads to erroneous expected values for Weibull distributions.

First, the code:
def weibull_expval(alpha,beta):
    """
    Expected value of weibull distribution.
    """
    return beta \* gammaln((alpha + 1.) / alpha)

The first thing that confuses me is the use of gammaln rather than gamma. Interpreting the expected value to be equivalent to the mean, I thought this formula would match what Wikipedia defines as the mean for a Weibull.

Then I looked for the definition of gammaln. 
def gammaln(x):
    """
    Logarithm of the Gamma function
    """

```
return flib.gamfun(x)
```

There's no definition or help available on flib.gamfun, but its name suggests it is the gamma function. Feeding it several values and exponentiating the results, it is returning the logarithm of the gamma function.

I dug into this because weibull_expval was returning negative values, which shouldn't be possible.

Either adding a gamma function to the defined functions in distributions.py that returns the exponentiated gammaln value and changing the definition in weibull_expval or just adding the exponential to weibull_expval would fix this.

**Comment by fonnesbeck** [comment]
Good catch, thanks. Fixed in 837f6367ef57b914412085a7363d7b15e39dfe1f. I will add a unit test to check this.
