### ISSUE TITLE
2.1alpha tarball

### ISSUE THREAD

**Issue by jonnybazookatone** [pymc-devs/pymc3#13]
seems to still have files missing in pymc/gp, 'gp_submodel.py' and 'step_methods.py'. Downloading and placing them in the folder seems to fix the issue.

**Comment by apatil** [comment]
I suppose we should just remove that tarball for now and let people download the head. I don't know how to remove downloads, though. Anyone else?

**Comment by pymc-devs** [comment]
That is not a download in the usual sense; its just a tarball that gets generated automatically for each tag. To get rid of it, we'd have to change or remove the tag, I think.

**Comment by apatil** [comment]
I nuked the release2.1alpha tag, since it's broken.
