### ISSUE TITLE
Unit test failure, OSX 10.8

### ISSUE THREAD

**Issue by kwjohnson** [pymc-devs/pymc3#130]
Pymc 2.2 on OSX 10.8 installed with easy_install; tried building from source as well, and I was getting other errors. Compiled with the OSX 10.8 version of gfortran, "GNU Fortran (GCC) 4.8.0 20120722 (experimental)".

Getting the following unit test failures:

Python 2.7.3 |EPD 7.3-1 (64-bit)| (default, Apr 12 2012, 11:14:05) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "credits", "demo" or "enthought" for more information.

> > > import pymc
> > > pymc.test()
> > > Running unit tests for pymc.tests
> > > NumPy version 1.6.1
> > > NumPy is installed in /Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/numpy
> > > Python version 2.7.3 |EPD 7.3-1 (64-bit)| (default, Apr 12 2012, 11:14:05) [GCC 4.0.1 (Apple Inc. build 5493)]
> > > nose version 1.1.2
> > > ..F.....Plotting switchpoint
> > > Plotting late_mean
> > > Plotting early_mean
> > > ....................................S..............................................................................................................................

FAIL: Failure: AssertionError (
Items are not equal:
 ACTUAL: 1
 DESIRED: 0)

Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/pymc-2.2-py2.7-macosx-10.5-x86_64.egg/pymc/tests/test_LazyFunction.py", line 96, in <module>
    assert_equal(L.get_cached_counts()[1,cur_frame], C.counter.get_count())
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 1
 DESIRED: 0

---

Ran 171 tests in 21.846s

FAILED (SKIP=1, failures=1)
<nose.result.TextTestResult run=171 errors=0 failures=1>

I'm not really sure how to proceed from here; is this failure permissible?

**Comment by fonnesbeck** [comment]
Interesting. I cannot replicate this. Does it show up consistently, or is it a stochastic error? 

BTW, if you are running OS X 10.8, you can try the binary that I provide [here](http://fonnesbeck.github.com/ScipySuperpack/). This runs clean on my machine.

**Comment by kwjohnson** [comment]
Thanks! Very cool, hadn't seen your binaries. I think the problem is with the gfortran compiler that I had installed, as I was getting lots of error messages during compilation.

Tried that; no longer getting the failure, but still a single skipped test:

Python 2.7.3 |EPD 7.3-1 (64-bit)| (default, Apr 12 2012, 11:14:05) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "credits", "demo" or "enthought" for more information.

> > > import pymc
> > > pymc.test()
> > > Running unit tests for pymc.tests
> > > NumPy version 1.6.1
> > > NumPy is installed in /Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/numpy
> > > Python version 2.7.3 |EPD 7.3-1 (64-bit)| (default, Apr 12 2012, 11:14:05) [GCC 4.0.1 (Apple Inc. build 5493)]
> > > nose version 1.1.2
> > > .......Plotting switchpoint
> > > Cannot plot autocorrelation for switchpoint
> > > Plotting early_mean
> > > Plotting late_mean
> > > ....................................S..............................................................................................................................

Ran 170 tests in 21.052s

OK (SKIP=1)
<nose.result.TextTestResult run=170 errors=0 failures=0>

**Comment by fonnesbeck** [comment]
A skip is fine. Its probably HDF5, or something else that has a missing optional dependency.

**Comment by kwjohnson** [comment]
I thought it might be something along those lines. Thank you!

for completeness, I used this gfortran compiler originally:

gfortran-4.7-bin.tar.gz (4.7.1) (gfortran only), updated July 2012 (Lion & M. Lion).
downloaded from 
http://hpc.sourceforge.net
