### ISSUE TITLE
Geweke score data structures under AdaptiveMetropolis

### ISSUE THREAD

**Issue by egleave** [pymc-devs/pymc3#139]
Apologies for not having chased this down further myself:

I have a model that has difficulty converging, so I was testing to see if Adaptive Metropolis would work faster than Metropolis. All code identical except for this step method.

In order to check that the model sufficiently converges, my scripts use the Geweke Test:

```
def geweketest(MCObject):
    scores=pymc.geweke(MCObject)
    test=0
    for var in scores.keys():
        test=max([test]+[abs(j[1]) for j in scores[var]])
    return test
```

All I care about is that the largest [absolute] value found is reasonable, which I've defined as 1.96. 

I get errors when I use this geweketest function against Adaptive Metropolis results but it works fine for Metropolis. The issue is the data structure in those scores. When step methods are not set, the structure is a dictionary of var:list where the list is a list of [iteration,value] lists. That's normal. The above function works because scores[var][j][1] is a Geweke score for iteration j in variable var. 

To do the same with Adaptive Metropolis, this would have to be scores[var][j][0][0][1] because the desired list of [iteration, value] is nested in a series of otherwise-empty lists. 

I don't even know where to look in the code to find how this would be happening and don't see why the step method would be affecting the data structure of the Geweke test, but this is what I believe is happening.

I'd be happy to try and dig further into it myself if provided some suggestions on where to look in the code base.

Eric Gleave

**Comment by fonnesbeck** [comment]
Can you provide a simple working example of this? I have tried it on my end, and can't seem to replicate it.
