### ISSUE TITLE
Allow block updating for arbitrary sets of stochastics in Metropolis

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#141]
In PyMC 2.2, block updating only occurs in Metropolis when stochastics are vector-valued. It would be nice to be able to block-update arbitrary sets of variables without having to use AdaptiveMetropolis.

**Comment by jsalvatier** [comment]
@fonnesbeck This is already implemented. For metropolis_step or hmc_step all you need to do is pass it the appropriate variables and it will update them together. If you want separate blocks, you just add more step methods. Do we need an example for this?

**Comment by fonnesbeck** [comment]
It would definitely be useful to have an example of this in action, as it will be extremely popular for intermediate/advanced users.
