### ISSUE TITLE
Test framework

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#145]
I was going to start adding some tests to pymc3. Is the current test framework what we want to stick with? Or something else. I have no strong opinions.

@fonnesbeck

**Comment by fonnesbeck** [comment]
I've started adding docstring tests, but we should have a proper suite of tests with adequate coverage, yes. I typically use numpy.testing and nose for this, which have worked well in the past.

**Comment by twiecki** [comment]
Continuous integration is also very handy. Especially travisCI is very well integrated with github and allows to see, for example, if a PR would break existing unittests.

Currently, it seems that almost all pymc3 examples are broken in one way or another.

**Comment by jsalvatier** [comment]
We have some small number of tests in place now, so I'll say this is done.
