### ISSUE TITLE
write_csv

### ISSUE THREAD

**Issue by aerotuck** [pymc-devs/pymc3#146]
This may not be considered a bug, since the same issue appears in the example on the documentation page, but the write_csv function, which is a very welcome advance,  would be more useful if the output parameters corresponded to the order of the input argument parameters, and for vector parameters in numerical order (theta1, theta2 etc). Otherwise, for large models there is a lot of post-processing just to get an output table sorted.

**Comment by fonnesbeck** [comment]
Thanks for the report. This should be fixed in 7fb51890df8b83cb081debe4d34db0b455939895. If a list of variable names in `variables` is passed, they will be saved in the order of that list; otherwise, the entire set of nodes will be saved in alphabetical order. Please test.
