### ISSUE TITLE
pymc.Matplot.plot sometimes ignore path argument

### ISSUE THREAD

**Issue by kforeman** [pymc-devs/pymc3#15]
If you initialize a model using vars() and then plot it, the "compound" objects (e.g. MVN) don't use the specified path when saving.

a = pymc.MvNormalCov('a',[10,10],[[1,0],[0,1]])
b = pymc.Normal('b',10,1)

m = pymc.MCMC(vars())
m.sample(10)

pymc.Matplot.plot(m.a, path='C:/tmp', format='pdf')
pymc.Matplot.plot(m.b, path='C:/tmp', format='pdf')

In this case b.pdf will be saved in C:/tmp, but a.pdf will be placed in the working directory. Tested in both 2.1alpha and latest dev version.

**Comment by pymc-devs** [comment]
Fixed in 6c1954f55ce5255dd954d634211e1b137b0aaf27. Thanks.
