### ISSUE TITLE
Error tallyin

### ISSUE THREAD

**Issue by madslupe** [pymc-devs/pymc3#150]
Hi,
I've just started running analyses with HDDM, and came across the error message below. I've been able to run through without problems previously, but now this error comes up no matter what I do. Does anyone know what I can be doing wrong?

/cluster/software/VERSIONS/python2-packages-2.7_2/lib/python2.7/site-packages/pymc/database/base.py:266: UserWarning: 
Error tallying v( d3. control), will not try to tally it again this chain.
Did you make all the samevariables and step methods tallyable
as were tallyable last time you used the database file?

Error:

Traceback (most recent call last):
  File "/cluster/software/VERSIONS/python2-packages-2.7_2/lib/python2.7/site-packages/pymc/database/base.py", line 256, in tally
    self._traces[name].tally(chain)
  File "/cluster/software/VERSIONS/python2-packages-2.7_2/lib/python2.7/site-packages/pymc/database/ram.py", line 93, in tally
    self._trace[chain][self._index[chain]] = value.copy()
IndexError: index out of bounds

  %s"""%(name, ''.join(traceback.format_exception(cls, inst, tb))))
/cluster/software/VERSIONS/python2-packages-2.7_2/lib/python2.7/site-packages/pymc/database/base.py:266: UserWarning: 
Error tallying a( d4. on), will not try to tally it again this chain.
Did you make all the samevariables and step methods tallyable
as were tallyable last time you used the database file?

**Comment by fonnesbeck** [comment]
I have not seen this come up before. You may want to bring this to the attention of the HDDM folks, as it may have something to do with what their code is doing behind the scenes.

**Comment by twiecki** [comment]
@madslupe HDDM issues are best addressed on the HDDM github repo https://github.com/hddm-devs/hddm or the HDDM mailing list https://groups.google.com/forum/?fromgroups#!forum/hddm-users.

Please make sure to also post accompanying code and the full traceback.

**Comment by madslupe** [comment]
Ok, thank you. I've posted it on the HDDM group to see if they might know.

Mads

On Mon, Feb 4, 2013 at 11:43 PM, Thomas Wiecki notifications@github.comwrote:

> @madslupe https://github.com/madslupe HDDM issues are best addressed on
> the HDDM github repo https://github.com/hddm-devs/hddm or the HDDM
> mailing list https://groups.google.com/forum/?fromgroups#!forum/hddm-users
> .
> 
> Please make sure to also post accompanying code and the full traceback.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pymc-devs/pymc/issues/150#issuecomment-13104206.

## 

Mvh Mads
