### ISSUE TITLE
PyMC 3 alpha release

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#152]
I'm interested in releasing a PyMC 3 alpha release. Putting it in a relatively usable state so that we can have some people try it out and give feedback. How does that sound to you @fonnesbeck ?

If we're going to do this what are the minimum things that have to be changed? I'll post my list below.

**Comment by jsalvatier** [comment]
Here's my list. Any seem non-critical?
- Tests covering
  - All examples 
  - Parallel sampling tests
  - History object tests
  - Step method specific tests
  - All graph functions (model_logp etc.)
- Better debugging. Theano is a bit tricky to debug and we have to let the users know that and make it as simple as possible
  - Require test point when making a model. This causes theano to compute test values and throw appropriate errors.
  - Errors when step methods that need scaling matrixes get non-positive definite matrixes
  - More thorough checking for nans and infs in find_MAP and the step methods. Throw errors in response when appropriate.
  - Standard functions for graphing the likelihood density with respect to different variables. This is useful if you want to write a new likelihood and suspect you may have gotten something wrong. 
- Get theano patch  https://github.com/Theano/Theano/pull/1083 fully integrated. This is important for having working gradients when indexing into variables. 
- Better errors for find_MAP when it encounters a problem
- Remove non-working examples/step methods 
- Be sure pymc does not import any numpy functions into the namespace directly since these often have name collisions with theano functions. 
- Eliminate problems related to giving starting points in the wrong format (using a starting point like {'a' : 1.5 } instead of {'a' : np.array([1.5])} will give annoying errors in certain contexts.

**Comment by fonnesbeck** [comment]
Probably best to call it an alpha, particularly since it is missing a test suite, convergence diagnostics, GOF and other important pieces. We should reserve beta for a feature-complete codebase that just needs to be tested by users.

**Comment by jsalvatier** [comment]
Yeah, good call.

**Comment by fonnesbeck** [comment]
That's a good list. We should turn each item into an issue on the tracker, with the appropriate label and knock them off from there. I already have a `v.3` label set up, so we will know when an alpha release is ready when all of those items disappear from the list.

**Comment by jsalvatier** [comment]
@fonnesbeck 

I think I've solved most of these problems, though I've refactored quite a few things, so there may be new problems. I'm still waiting on Theano/Theano#1083  though. 

Do you have thoughts on other features that are important for getting people excited? Any specific examples that we should bring over?

**Comment by fonnesbeck** [comment]
We should probably have a benchmark performance example, one that shows the benefit of moving to PyMC 3. This is both in terms of sampling speed and in terms of rate of convergence. Maybe a Rosenbrock function, or something similar?

**Comment by jsalvatier** [comment]
These criteria are almost all fulfilled. Are there other big things we need to do before we make an alpha release?

**Comment by fonnesbeck** [comment]
I will add outstanding issues as I come across them. One thing that pops to mind are docstrings for all methods and functions. I made a start in a few places but got distracted.

**Comment by jsalvatier** [comment]
After a long delay (employer had to approve my continuing contribution to pymc), I've committed a bunch of changes. I think we are quite close. If people are happy with the syntax, I think we should clean up a little bit and make an alpha release.

**Comment by jsalvatier** [comment]
Released! Great job everybody!
