### ISSUE TITLE
TestMissing test generates a lot of errors, looks related to TWalk

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#16]
I get a lot of divide by zero in log errors and invalid value errors in TestMissing. I set numpy.seterr(divide = 'raise', invalid = 'raise') and it looks like the problem comes up in TWalk

**Comment by fonnesbeck** [comment]
I've downgraded the competence of TWalk in f3968c2317e384365f5c7f6bdafc67e427777cf6 until I sort it out.
