### ISSUE TITLE
Theano advanced indexing

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#161]
Theano/Theano#1083 needs to be fully integrated into Theano. This is important for having working gradients when indexing into variables.

**Comment by jsalvatier** [comment]
With the merging of https://github.com/Theano/Theano/pull/1279, this is completed.

**Comment by twiecki** [comment]
Congrats on getting that in!

**Comment by jsalvatier** [comment]
:D :dancer:
