### ISSUE TITLE
Starting values dict

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#170]
I'm worried about having a separate dict for starting values, particularly in terms of scaling to larger models. Users will probably not want to build this by hand after already specifying each node in the model. I realize the desire to keep the state of the MCMC chain separate from the structure of the model, but I also want to keep the model-building workflow as frictionless as possible.

Thoughts?

**Comment by fonnesbeck** [comment]
One idea: have automatic smart initialization, say to the expected value given the values of the parameters (or hyper priors), which users can override using the start dict. Most of the time, users manually initialize to a value near the mean/median anyhow, so this would make sense. Then users would only have to mess with the starting values when the felt they needed to.

**Comment by twiecki** [comment]
To add to this: If starting values are set automatically from the prior, I think there should be a "retry" parameter that proposes new starting values until a valid one is found. In the case of an invalid parameter setting, pymc2 currently just bails.

**Comment by fonnesbeck** [comment]
This can be trickier than it sounds. If you sample from the prior to set an initial value, and the prior is very uninformative, you can end up with very bad initial values. 

Of course, the best way to set initial values (if you can) is via a MAP approximation.

**Comment by twiecki** [comment]
That's true. However, when running multiple chains I think you actually want random (or at least different) starting values, no?

**Comment by fonnesbeck** [comment]
Ideally, you would want highly dispersed values, but not so dispersed that they are in the tails of the conditional posterior.

**Comment by jsalvatier** [comment]
How about this?

Models automatically generate test points by picking the mean, median or mode point of the prior for each variable (or user specified). This is to get better error messages from Theano. Not sure if we should throw an error if the test value is out of bounds.

For sampling, if a user does not specify a starting point, the default will be a model's test point. 

Later on (probably not now), we'll make some functions that take a model and generate a random starting point (say by drawing from the prior distribution).

**Comment by jsalvatier** [comment]
I've implemented this in: https://github.com/pymc-devs/pymc/tree/distributions

How does this solution seem to you guys? 

`sample` still takes a point, but the user can pass model.test_point . 

In the future, I'd like to figure out how to rework `sample` so that it takes a model and step_methods do not, but I'm not sure what is the best way to do this is.

**Comment by jsalvatier** [comment]
I've integrated this into the `pymc3`

**Comment by fonnesbeck** [comment]
How does this work, exactly? I tried sampling without passing a `start` dict, and it threw a TypeError because it `sample` tries to look for a point in a non-existant trace when `start` is None. Should it not be looking for the `mean` or `mode` values of the variables in the model?

**Comment by jsalvatier** [comment]
The way this currently works is that if you don't pass in a value, it sees if there's a trace, and picks the last value in the trace. It would be natural to have it also look at model.test_point. I was somewhat concerned that it would be confusing to have so many different sources, but maybe that's not true.
