### ISSUE TITLE
More descriptive class names for `map`

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#171]
The classes in the `map` module are not very descriptive  (e.g. `DictArrBij`). In the spirit of PEP8, it is more important that class and function names be meaningful than short.

**Comment by jsalvatier** [comment]
Fair enough, is DictArrBijection descriptive enough? The notion is that it maps between an element of DictionarySpace and ArraySpace.

**Comment by jsalvatier** [comment]
I've made their names more informative, but we still need some better documentation in this spot.
