### ISSUE TITLE
Rename `pymc.distributions` to `pymc.likelihoods`

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#172]
Can we do this, since that is really what these functions are? The primary reason for this, other than for descriptive clarity, is that we will need random number generators and expected values for each of these distributions in order to do goodness-of-fit diagnostics.

**Comment by jsalvatier** [comment]
I think we  can actually incorporate random number generators and expectations the current way distributions are written. I had been resisting the idea, but I've come around. My notion is as follows:

Instead of having a function which returns a function:

```
def Normal(mu, tau): 
    def dist(x) :
          return (x - mu)**2*tau + log(tau)
    return dist
```

We can have a function that returns a class: 

```
def Normal(mu, tau): 
     class dist(object): 
          def logp(self, x) :
               return (x - mu)**2*tau + log(tau)
          expectation = mu 
          variance = tau**-1
      return dist
```

Then in AddVar(), the dist gets initialized, and logp(x) gets called and expectation etc if they're needed. This would also support distributions that just have expectations etc and not a logp. 

If you're wondering why I don't just want a regular class, it's just because it seems like that makes things much more verbose and less elegant:

```
class Normal(object): 
     def __init__(self, mu, tau):
          self.mu = mu
          self.tau = tau

     def logp(self, x) :
               return (x - self.mu)**2*self.tau + log(self.tau)
     def expectation(self):
         return self.mu 
     def variance(self)
         return self.tau**-1

I guess that's not *soo* bad. I could be talked out of it.
```

**Comment by twiecki** [comment]
FWIW I find the 2nd option much easier on the eyes as I've seen that idiom a million times before. Returning classes? Not so much..

**Comment by jsalvatier** [comment]
2nd option = pure class? 

What I am really trying to get is something like scala style classes, something like :

```
class Normal(mu, tau):
    def logp(x):
        return (x-mu)**2 * tau
    expectation = mu
    variance = tau **-1
```

But that won't work. However, maybe we can do: 

```
def Normal(mu, tau):
    def logp(x):
        return (x-mu)**2 * tau
    expectation = mu
    variance = tau**-1
    return locals()
```

This is actually not _that_ far from what pymc2 does. The idiom is nonstandard, but is pretty simple. And I think this will behave a lot like a class. 

If it helped, we could also have an `@class` decorator which would turn the function into an actual class.

**Comment by twiecki** [comment]
What about @property?

**Comment by mrocklin** [comment]
An example of SymPy.stats distribution classes

``` Python
class ArcsinDistribution(SingleContinuousDistribution):
    _argnames = ('a', 'b')

    def pdf(self, x):
        return 1/(pi*sqrt((x - self.a)*(self.b - x)))

class NormalDistribution(SingleContinuousDistribution):
    _argnames = ('mean', 'std')

    @staticmethod
    def check(mean, std):
        _value_check(std > 0, "Standard deviation must be positive")

    def pdf(self, x):
        return exp(-(x - self.mean)**2 / (2*self.std**2)) / (sqrt(2*pi)*self.std)

    def sample(self):
        return random.normalvariate(self.mean, self.std)
```

Other attributes like expectations, variances, sampling and cdf are computed analytically by default (see definition for SingleContinuousDistribution [here](https://github.com/sympy/sympy/blob/master/sympy/stats/crv.py#L150) )  but can be overridden by the subclass if extra knowledge exists.

**Comment by jsalvatier** [comment]
Distributions have become more distribution like in https://github.com/pymc-devs/pymc/tree/distributions
