### ISSUE TITLE
Document timeseries.py

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#176]
Are we retaining this module? If so, classes and methods need documentation and tests.

**Comment by jsalvatier** [comment]
I have found it personally useful, but that's the only reason its there. Since it's not 'basic' nor well developed, perhaps we should remove it.

**Comment by jsalvatier** [comment]
I now use this in the stochastic vol example, so I don't think we should remove this. I've added some documentation, but not tests. Right now, I'm not inclined to add tests: I think it's a little tricky to test multivariate distributions.
