### ISSUE TITLE
Can't subclass pymc.Metropolis for block updates

### ISSUE THREAD

**Issue by jzelner** [pymc-devs/pymc3#179]
Hi - Apologies if I'm missing something or if this has been addressed elsewhere, but as it currently stands pymc.Metropolis automatically wraps the stochastic passed to it in a list before passing to pymc.StepMethod. So, if the original argument is a list of stochastics (i.e. for a custom block-update), pymc.StepMethod.**init** receives [[stochastic_1, stochastic_2]] and throws an error. It would be great if Metropolis checked to see if the stochastic is iterable before wrapping it, and then this would get rid of the issue (or I could be completely missing the point, in which case any advice would be greatly appreciated!).

Thanks!
-Jon

**Comment by fonnesbeck** [comment]
The Metropolis step method is designed to work only with a single stochastic, so block updating can happen in Metropolis for elements of a vector-valued Stochastic, but not for lists of Stochastics. If you want to do block updating for arbitrary collections of Stochastics, you should look at AdaptiveMetropolis and try subclassing it to your liking if you do not like the adaptive stuff.

**Comment by fonnesbeck** [comment]
Also, note that a general solution is coming in PyMC 3 (#141).
