### ISSUE TITLE
likelihood function refactoring (numexpr_dist) 

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#18]
For those interested, these are the current timings for the likelihoods I've rewritten for numexpr.

The gist seems to be that at small sizes, numexpr is much slower. At larger sizes it is comparable and occasionally a bit faster. The problem with beta_like is (I think) that it requires numerous calls to gammaln which cannot be directly included in numexpr and must instead be precomputed. 

I looked into modifying numexpr to allow user functions, but it looks very nontrivial.

I am additionally experimenting with automatically generating Cython code for the distributions given strings describing the calculation, and that seems somewhat promising. numpy.newiter appears to be coming out soon, and that comes with some relevant iteration improvements. 

Given as numexpr_dist time/normal time: 

number of elements :  [1,           10,        100,  1000,  10000, 100000]
beta_like           [  106.779    55.677    63.131   100.663   421.671  3013.556]
betabin_like        [ 52.397  20.327   3.46    0.913   0.824   0.721]
cauchy_like         [ 39.158  13.16   14.841   4.276   1.919   1.241]
chi2_like           [ 28.572   9.255   5.228   1.697   0.931   0.759]
exponential_like    [ 42.131  11.882   7.805   1.144   0.677   0.324]
gamma_like      [ 16.13   12.087   7.695   1.901   0.979   0.728]
geometric_like      [ 28.92   18.659  16.294   5.197   2.161   1.235]
half_cauchy_like    [ 3.568    2.686    1.298   0.991   0.993    0.976]
half_normal_like        [ 70.651  33.408  28.134   9.692   2.772   1.295]
inverse_gamma_like  [ 35.528  14.217   6.688   1.722   1.027   0.759]
laplace_like        [  5.171   5.481   3.755    1.37    0.658    0.425]
lognormal_like      [ 112.921   56.943   27.621   12.079    3.219    2.084]
normal_like         [ 60.752  27.092  24.34    9.203   2.694   1.37 ]
t_like              [ 28.571   9.71    4.602   1.392   0.952   0.832]
noncentral_t_like   [ 22.946   7.275   4.347   1.423   0.976   0.769]
uniform_like        [  31.675   16.325   16.355   20.127   57.899  276.854]
weibull_like        [ 71.362  39.418  18.42    4.069   1.639   0.876]

To run these yourselves, run pymc/tests/speed_test.py in numexpr_dist.

**Comment by fonnesbeck** [comment]
Interesting. I would imagine that cython would improve on the performance for smaller sizes. I'm assuming you started with numexpr because of ease of implementation?

**Comment by jsalvatier** [comment]
Yeah, I would expect that too. I started with numexpr because it's the idea that first seemed good. One good thing about numexpr is that it automatically multithreads the computation.

**Comment by jsalvatier** [comment]
Some timings using cython code generation using jinja2 (http://jinja.pocoo.org/) templates. 

sizes [1, 10, 100, 1000, 10000, 100000]
bernoulli_like(x, p) [ 2.874  3.133  2.321  0.888  0.274  0.137]
beta_like(x, alpha, beta) [ 4.253  4.071  3.54   3.625  3.856  3.97 ]
betabin_like(xd, alpha, beta, n) [ 4.561  2.589  0.639  0.141  0.096  0.09 ]
cauchy_like(x, alpha, beta) [ 4.468  4.034  3.185  0.978  0.267  0.172]
gamma_like(x, alpha, beta) [ 4.258  3.636  1.524  0.246  0.031  0.008]
normal_like(x, mu, tau) [ 4.326  4.251  3.199  1.468  0.257  0.145]

The gist is that for small sizes, it's about 4x slower, but for sizes > 1000 there are ~8x improvements. I'm not sure what's going on with beta_like, it's not much different than the other functions.

To duplicate the comparisons run speed_test2.py in the tests folder. You will need to rebuild and you will need the code generation package I wrote ufunc_gen (https://github.com/jsalvatier/ufunc_gen). 

Reasons why I like the code generation approach: 
-  fast
-  supports multidimensional arrays correctly
-  it is now easy to do efficiency improvements on many likelihoods simultaneously, or even switch languages; it wouldn't be very tedious to generate and compile c-extensions instead of cython extensions.
-  easy to open up code generation to the user as well for custom likelihoods. 
-  opens up the possibility of automatically (but symbolically) differentiated gradients and jacobians by using SymPy. This would eliminate even more code, work especially well for custom likelihoods and eliminate one source of errors.
-  eliminates a lot of manual fortran code

Drawbacks: 
-  multivariate distributions still need to be custom written. 

I may look into Theano (http://deeplearning.net/software/theano/), which, it strikes me now, is doing more or less exactly this kind of code generation from text kernel.

I am somewhat curious about eliminating the large quantity of metaprogramming we currently have in distributions.py and using templating to do code generation instead. I suspect this would make the code easier to understand and maintain. Code generation might also be good for auto writing tests. The reason I think code generation is suited to PyMC is that when we build distributions we essentially want to create many classes with a standard format.

**Comment by jsalvatier** [comment]
It comes to mind that Theano would also facilitate GPU usage. Theano also, optimizes the whole graph at once, which I think would be very advantageous to likelihood calculations. It also does symbolic differentiation. 

Once you start thinking code generation is a good idea, Theano starts to look really good.

**Comment by apatil** [comment]
Also, once you start thinking about code generation, Fortran looks a lot better. :) I agree with you that, if we use any code generation approach, it should be easy to convert to different 'backends'.

Theano would really shine if it had access to whole submodels, not just one variable at a time, right?

**Comment by apatil** [comment]
The timings you're showing are relative to the Fortran timings, right? How does Cython manage to beat Fortran by such a wide margin for some of them?

**Comment by jsalvatier** [comment]
Yes, I think more more you include in your graph, the better.

Yes, relative to Fortran. I am not sure how Cython is beating Fortran so much. I'll make sure I haven't made a mistake. Could it be compile options on Cython vs F2Py?

I asked about Theano on the Theano list, and the responses were very encouraging, it avoided all the potential issues I was worred about except for linear algebra support, which is currently primitive (dot, outer and tensordot), though under development, and masked arrays (though it should be possible to DIY). I am intrigued by Theano enough that I am going to try building a prototype PyMC like package for its underlying DAG, to see how the design turns out. Then I will see what can inspire PyMC.

**Comment by apatil** [comment]
Cool, sounds extremely interesting. Please keep us posted.

**Comment by fonnesbeck** [comment]
An interesting thread on the numpy list on the relative virtues of C/C++/FORTRAN. This is the start of the relevant bit:

http://mail.scipy.org/pipermail/numpy-discussion/2011-March/055392.html

**Comment by fonnesbeck** [comment]
For reference, [here](http://code.google.com/p/pymc/issues/detail?id=328) is the discussion started on the Google Code tracker.

**Comment by fonnesbeck** [comment]
Once the 2.2 release is out the door, this is one of the first things that I want to improve for 2.3. I think the first step is to figure out what the optimal implementation would be given current performance and the outlook for the future. Numexpr might be the easiest to implement, but the capabilities of Cython are broader. Are we willing to take a hit on smaller models for the sake of speed in larger models?

**Comment by twiecki** [comment]
My .02$: I think Cython is a great backend for this. But I wouldn't rule out Theano, especially given that there has been some foreway been made by James Bergstra (although the project seems inactive) and that GPU would be for free:

https://github.com/jaberg/MonteTheano

**Comment by fonnesbeck** [comment]
I suppose another advantage of Theano is that we would also get gradients for free, which would be handy for Hamiltonian MC. I will do some exploring.

**Comment by fonnesbeck** [comment]
On the other hand, you don't really ever get GPU for "free" -- you need to install CUDA, Boost, PyCUDA. I would like to keep the dependencies list as short as possible going forward, as it represents an adoption hurdle for new users.

**Comment by twiecki** [comment]
I don't think Theano depends on PyCUDA or Boost. And the CUDA
dependency is optional:

http://deeplearning.net/software/theano/install.html

On Thu, Apr 5, 2012 at 10:48 PM, Chris Fonnesbeck
reply@reply.github.com
wrote:

**Comment by jsalvatier** [comment]
I think we've abandoned this for now.
