### ISSUE TITLE
segfault with minimal example

### ISSUE THREAD

**Issue by astraw** [pymc-devs/pymc3#180]
I ran across a segfault on a couple different machines. It's possible that I screwed something up with my PyMC build, but I reproduce this on two different Ubuntu 12.04 setups running the git master branch of PyMC. Anyhow, here's a minimal example:

```
from pymc import Binomial

data = [0,0,1,1,0,0,1,1,0,0,1,1]
Binomial('fair_coin',len(data),0.5, observed=True, value=data)
```

This invariably results in a core dump for me. On the console before the backtrace I see:

```
*** glibc detected *** python: free(): corrupted unsorted chunks: 0x00000000039109f0 ***
```

I think that, even if I have something deeply wrong with my code, I shouldn't be getting a segfault here.

**Comment by fonnesbeck** [comment]
Egad. I've never seen this, and I can't reproduce it here, as I am on OS X. The only C (cython) code in PyMC is related to container objects and lazy evaluation, neither of which is in play here. 

What version of Python are you running? Can you try with a different Python?

**Comment by astraw** [comment]
Actually, the lazy evaluation stuff is in play here. An instance of LazyFunction is created in the Stochastic.**init** method and the force_compute() method is called there, too. The happens both for the main Binomial log-likelihood function as well as the partial gradient functions.

And it seems the lazy evaluation stuff is somehow potentially the culprit. I've been trying to track this down, but so far the closest I can get is that removing a few lines of code seems to have no adverse effect on the way I'm calling PyMC and the segfault and core dumps I'm seeing are gone.

```
diff --git a/pymc/PyMCObjects.py b/pymc/PyMCObjects.py
index d01180a..0f735da 100644
--- a/pymc/PyMCObjects.py
+++ b/pymc/PyMCObjects.py
@@ -744,16 +744,6 @@ class Stochastic(StochasticBase):
                                     cache_depth = self._cache_depth)
         self._logp.force_compute()

-
-        self._logp_partial_gradients = {}
-        for parameter, function in six.iteritems(self._logp_partial_gradient_functions):
-            lazy_logp_partial_gradient = LazyFunction(fun = function,
-                                            arguments = arguments,
-                                            ultimate_args = self.extended_parents | set([self]),
-                                            cache_depth = self._cache_depth)
-            lazy_logp_partial_gradient.force_compute()
-            self._logp_partial_gradients[parameter] = lazy_logp_partial_gradient
-
     def get_value(self):
         # Define value attribute
         if self.verbose > 1:
```

Obviously, this isn't solving the problem, and weirdly it suggests that a single LazyFunction instance is OK. The problems only start when more than one are instantiated.

Anyhow, this is on Python 2.7 as shipped by Ubuntu 12.04 amd64.

**Comment by fonnesbeck** [comment]
I can't reproduce this at all, so closing. Please reopen if this can be repeated on another machine.

**Comment by rsepassi** [comment]
I'm having the same issue. Have tried on 5 OS X computers, all running Mavericks, Python 2.7.6, pymc 2.3.2 (fresh install with pip).

Here's the code:

```
from pymc import Binomial, Uniform
p = Uniform('p', 0, 1)
data = [0, 1, 1, 0, 1]
b = Binomial('data', len(data), p, value=data, observed=True)
```

Error: `Segmentation fault: 11`

The above code doesn't always seg fault immediately but always does if you run the `b = Binomial...` line several times.
