### ISSUE TITLE
Varying behaviour for Python 2/3 with histogram function

### ISSUE THREAD

**Issue by warrd** [pymc-devs/pymc3#181]
I've noticed there's been some breaking changes to pymc for py3 since this [pull request](https://github.com/pymc-devs/pymc/pull/83).
I've forked the latest version and made some changes to get it working, [here](https://github.com/warrd/pymc).

However, the fork is failing on a large number of the [test_distributions.py](https://github.com/warrd/pymc/blob/master/pymc/tests/test_distributions.py) tests. 
The problem seems to be in the histogram function when the Fortran function FIXED_BINSIZE is called:  with python 3 the return value is always zero for each bin.

Here's an example:

``` python
import numpy as np
from pymc import flib
x = np.arange(4)
result = flib.fixed_binsize(x, 0.5, 1, 2)
```

With py2 the result is `array([1, 1, 1, 1], dtype=int32)`, whereas py3 the result is `array([0, 0, 0, 0], dtype=int32)`. 
Any ideas? I would try and debug further, but have to say I'm not too familiar with Fortran :)

**Comment by fonnesbeck** [comment]
I have yet to use PyMC under Python 3 myself (though I probably should). Perhaps others will have some intuition. It must have something to do with f2py, since the Fortran itself does not change. The `fixed_binsize` subroutine itself is pretty straightforward:

```
      SUBROUTINE FIXED_BINSIZE(X, BIN0, DELTA, N, NX, H)

C PARAMETERS
C ----------
C X : ARRAY 
C BIN0 : LEFT BIN EDGE
C DELTA : BIN WIDTH
C N : NUMBER OF BINS
C H : HISTOGRAM

      IMPLICIT NONE
      INTEGER :: N, NX, i, K
      DOUBLE PRECISION ::  X(NX), BIN0, DELTA
      INTEGER :: H(N+2), UP, LOW

CF2PY INTEGER INTENT(IN) :: N
CF2PY INTEGER INTENT(HIDE) :: NX = LEN(X)
CF2PY DOUBLE PRECISION DIMENSION(NX), INTENT(IN) :: X
CF2PY DOUBLE PRECISION INTENT(IN) :: BIN0, DELTA
CF2PY INTEGER DIMENSION(N+2), INTENT(OUT) :: H
CF2PY THREADSAFE


      DO i=1,N+2
        H(i) = 0
      ENDDO

C     OUTLIERS INDICES
      UP = N+2
      LOW = 1

      DO i=1,NX
        IF (X(i) >= BIN0) THEN
          K = INT((X(i)-BIN0)/DELTA)+1
          IF (K <= N) THEN
            H(K+1) = H(K+1) + 1
          ELSE 
            H(UP) = H(UP) + 1
          ENDIF
        ELSE 
          H(LOW) = H(LOW) + 1
        ENDIF
      ENDDO

      END SUBROUTINE
```

**Comment by warrd** [comment]
Strange, I can't reproduce the error: the distribution tests which were failing are now passing, and the code snippet above is the same for py2 and py3.
I'm guessing there was something wrong with my previous build..

There's still a couple of tests failing in my fork, but they are failing in 2 in the main branch as well, so I'm closing the issue and putting in a pull request..
