### ISSUE TITLE
Running examples from clean install

### ISSUE THREAD

**Issue by mrocklin** [pymc-devs/pymc3#185]
I was trying to run some of the examples from a clean install.  This generated some dependency errors.  Previous discussion was in https://github.com/pymc-devs/pymc/issues/178 .  I thought it would be a good idea to separate this issue.

**Comment by mrocklin** [comment]
@jsalvatier I can import pymc but can't run examples.  At first I found that my pandas install was out of date.  I then pip installed everything listed by `python setup.py --requires`

Now I get this

```
pymc/examples$ ipython
In [1]: run ARM5-4.py


*** libmkl_avx.so *** failed with error : /home/mrocklin/Software/epd-7.3-2-rh5-x86_64/lib/libmkl_avx.so: undefined symbol: i_free
*** libmkl_def.so *** failed with error : /home/mrocklin/Software/epd-7.3-2-rh5-x86_64/lib/libmkl_def.so: undefined symbol: i_free
MKL FATAL ERROR: Cannot load neither libmkl_avx.so nor libmkl_def.so
mrocklin@notebook:~/workspace/pymc/examples$ 
```

It could be that this is specific to my machine and my install in which case feel free to deprioritize this.  I believe I've gone through relatively normal channels to reach this point though.

**Comment by jsalvatier** [comment]
That's interesting. I don't think pymc3 does anything MKL specific, and I know relatively little about it. Do you have MKL installed?

**Comment by jsalvatier** [comment]
I guess you clearly do since it lists a path for it. 

This link is relevant: http://stackoverflow.com/questions/14495334/python-matplotlib-mkl-fatal-error-on-ubuntu-12-04

**Comment by mrocklin** [comment]
I suspect that pip installing pandas caused me to update numpy using pip.  I've heard that this isn't bulletproof.  

I suspect that running off of a newer EPD distribution would work.  I'm curious, what do the pymc developers use?

**Comment by jsalvatier** [comment]
I often use pip or install it directly if I am installing the source.

**Comment by jsalvatier** [comment]
Though I just determined you can use pip to install from source 

`pip install pymc/`

**Comment by jsalvatier** [comment]
@mrocklin Did you get this to work?

**Comment by mrocklin** [comment]
Yes.  Turns out I was running into a known issue with numpy on Ubuntu 12.04.

**Comment by jsalvatier** [comment]
Oh good, glad we know what caused this. Let me know if you have further troubles.
