### ISSUE TITLE
Need block updating example for metropolis

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#187]
Block updating is a popular feature for intermediate/advanced users (https://github.com/pymc-devs/pymc/issues/141#issuecomment-15189079). Should have an example for this.

**Comment by jsalvatier** [comment]
@fonnesbeck Do you have a good example on hand I could use for a block updating example?

**Comment by fonnesbeck** [comment]
I'm sure I have several, but will have to dig around through some of my old models. A general case where it is useful, however, is when you have a set or regression covariates, some of which are strongly correlated. One of the papers that comes to mind is [Chib and Carlin (1999)](http://link.springer.com/article/10.1023/A%3A1008853808677) that has a couple of examples that we could use.

**Comment by jsalvatier** [comment]
Excellent, Thanks.

**Comment by jsalvatier** [comment]
The example should be for block updating or more than one random variable, right? Not just a vector valued random variable?

**Comment by fonnesbeck** [comment]
It would be good to show the generality of blocking by using several random variables, yes. [Here is an example](http://www.bias-project.org.uk/GMRFCourse/approx-inference-intro-slides.pdf) of a latent Gaussian model for rainfall that is improved by blocking. The associated data are [here](http://www.stat.uni-muenchen.de/service/datenarchiv/tokio/tokio_e.html#top).

**Comment by jsalvatier** [comment]
Added an example: https://github.com/pymc-devs/pymc/blob/pymc3/examples/lasso_block_update.py
