### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#188]
We should probably stick to PEP8 naming conventions for v.3. Specifically, CapWords for classes and lowercase_with_underscores for methods and functions. At present there are violations in both directions (e.g. `metropolis_step` and `Data`/`Var`). I can see making the `quickclass` functions look like classes, but otherwise not.

**Comment by jsalvatier** [comment]
Yeah, methods should be CapWords I'll change that. 

I kinda like CapWords for Data, Var and TransformedVar since relatively constructor-like, they build new random variables. Do you think it's important for them to be lowercase?

**Comment by fonnesbeck** [comment]
Well, there is already a Variable function that behaves like a constructor. I suppose strictly speaking, the method for adding them to the model should be `add_var` and add_data`, but the former actually returns a Variable object (Tensor). I do not know what is cleaner.

**Comment by jsalvatier** [comment]
I actually think we should rename Variable, I don't think the name is that appropriate. It creates a theano tensor that matches the specification of the random variable. It's also only intended to be used within a function for making a random variable. I'm not sure what would be a better name, though.

**Comment by jsalvatier** [comment]
Fyi, I've changed the samplers.
