### ISSUE TITLE
pymc.gp.observe doesn't handle undefined OMP_NUM_THREADS

### ISSUE THREAD

**Issue by mcfarljm** [pymc-devs/pymc3#19]
On my system, the environment variable OMP_NUM_THREADS is not defined, so I get a KeyError when executing pymc.gp.observe.  A suggested patch is below, but I'm not sure whether this is consistent with the rest of the code in threadpool.py, for example lines 307-310 which appear to be there to handle this case.

John

diff --git a/pymc/threadpool.py b/pymc/threadpool.py
index 7f06f8c..83e2907 100644
--- a/pymc/threadpool.py
+++ b/pymc/threadpool.py
@@ -372,7 +372,7 @@ def get_threadpool_size():

 def thread_partition_array(x):
     "Partition work arrays for multithreaded addition and multiplication"
-    n_threads = int(os.environ['OMP_NUM_THREADS'])
-    n_threads = int(os.environ.get('OMP_NUM_THREADS','1'))
   if len(x.shape)>1:
       maxind = x.shape[1]
   else:

**Comment by mcfarljm** [comment]
OK, the markup on this system has really messed up the display of that patch.  All I did was change this line:

n_threads = int(os.environ['OMP_NUM_THREADS'])

To this:

n_threads = int(os.environ.get('OMP_NUM_THREADS','1'))

**Comment by apatil** [comment]
Fixed in 4e8bfddb56158064c45ed92d36cca3995fe8e8ad, thanks.
