### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#190]
We will need some way of providing feedback during long runs. It should be easy to port the `progressbar.py` from PyMC2.

**Comment by jsalvatier** [comment]
I saw that it apparently works nicely in IPython notebook, that's awesome.

**Comment by jsalvatier** [comment]
Added this https://github.com/pymc-devs/pymc/blob/31f4c596a4f38e095b022e645d4348b7a39a903e/pymc/progressbar.py . Currently we just have a text progress bar, but if we can figure out how to detect if called within ipython notebook, there's a javascript progress bar ready to use.
