### ISSUE TITLE
Traces for deterministics

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#192]
Unless I am mistaken, deterministic functions (e.g. transforms) of variables are not stored as traces. However, these may be the desired pieces of inference from a given model. For example, in `logistic.py` the `effects` node would not be of direct inference, since they are more easily interpreted on the inverse-logit (probability) scale. I suppose one can transform the trace after sampling, but if the calculation is already being done, we may as well store it.

**Comment by jsalvatier** [comment]
Agreed. I fooled around with this a while back, trying to get it to work nicely, and I could not. I think the issue I ran into is that you don't really want to call the model functions with those extra variables. However, we always compile with on_unused_input = 'ignore', so maybe I'm misremembering? 

Ideas on how to do it right?

**Comment by jsalvatier** [comment]
@fonnesbeck do you have thoughts on where the appropriate place/way would be to specify that you want to track a deterministic?

**Comment by kyleabeauchamp** [comment]
So I actually just ran into this issue in my model--I agree it would be nice to be able to trace the transformed object.

Does anyone else think the current naming of trace, keep_trace, and trace() is a bit confusing?  One is a bool passed to the **init** function, the other is a bool member variable, and the last is a Trace() instance stored as a member variable in a RV.

**Comment by jsalvatier** [comment]
@kyleabeauchamp That does sound fairly confusing. For pymc3, we have a trace object that is returned by a sampler (for example see In[10] here http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/pymc3/examples/tutorial.ipynb). Do you have thoughts on where would be a natural place to pass which deterministics you want to keep track of?

**Comment by jsalvatier** [comment]
Implemented, simply pass a set of variables to NpTrace or to sample. See the call to sample in http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/pymc3/examples/stochastic_volatility.ipynb

**Comment by fonnesbeck** [comment]
One inconvenience associated with this is accessing the trace of the deterministic after sampling. For example, appending an odds ratio calculation to a list of traced variables:

```
    trace = sample(10000, step, start, trace=model.vars + [odds_ratios]) 
```

results in the following `varnames` for the trace:

```
In [67]: trace.varnames
Out[67]: ['mu_0',
 'lam_0',
 'nu_0',
 'mu',
 'beta',
 'mu_treat',
 'lam_treat',
 'nu_treat',
 'beta_treat',
 'alpha',
 'Elemwise{exp,no_inplace}.0']
```

which makes it awkward to use in subsequent functions, such as `traceplot`. Would it be possible to either somehow name the deterministic node or pass a dict to sample?

**Comment by jsalvatier** [comment]
I have the very simple `named` function https://github.com/pymc-devs/pymc/blob/pymc3/pymc/model.py which does just that (you can also just set .name). It's not exposed right now, but we can do that. I was trying to think of a better way but I didn't think of anything.

**Comment by fonnesbeck** [comment]
I'm happy with setting the `name` attribute in-place.

**Comment by fonnesbeck** [comment]
This issue has come up again in a more subtle, but important form. If you define a function that generates models, it does not appear to be possible to add deterministics by name to the list of elements to be tracked by the trace. For example:

```
def power_model(n, p_true=p):

    # Simulate data
    x = [[np.random.binomial(n[s][d], p_true[s][d]) for d in STANDARD, HIGH] for s in CONTROL, SCT]

    with pm.Model() as model:

        # Priors
        theta = pm.Normal('theta', 0, 0.0001, shape=2)
        delta = pm.Normal('delta', 0, 0.0001)

        # Probability of 4-fold increase
        p = [[tinvlogit(theta[s] + delta*d) for d in STANDARD, HIGH] for s in CONTROL, SCT]

        like = [[pm.Binomial('like{0}{1}'.format(s,d), n=n[s][d], p=p[s][d], observed=x[s][d]) 
                 for d in STANDARD, HIGH] for s in CONTROL, SCT]

        # Contrasts

        #SD vs SD  sct vs control
        sd_diff = p[0][0] - p[1][0]
        #HD vs HD  sct vs control
        hd_diff = p[0][1] - p[1][1]
        #HD vs SD  control
        control_diff = p[0][0] - p[0][1]

    return model
```

Here, the contrasts at the bottom are of primary interest in the analysis, yet they cannot be added to the trace because they will be inside the namespace of the `power_model` function:

```
with m:
    step = pm.Metropolis()
    tr = pm.sample(10000, step=step, trace=m.vars + [sd_diff, hd_diff, control_diff])


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-135-bf45312501e3> in <module>()
      1 with m:
      2     step = pm.Metropolis()
----> 3     tr = pm.sample(10000, step=step, trace=m.vars + [sd_diff, hd_diff, control_diff])

AttributeError: name 'sd_diff' is not defined
```

This is an important use case, because we often want to be able to generate custom models in this way.

**Comment by jsalvatier** [comment]
Hmm, okay, so it sounds like we want models to have a list of relevant variables that can be accessed by name. Be they stochastics or deterministics.

**Comment by jsalvatier** [comment]
How about this: 

Any random variables or named stochastics, get added to the Model object (unless they have illegal identifiers or conflict) and are also accessible by indexing model['variable name']. 

We can have the `named(variable, name)` function add the name to the model.  

Thus you would fix your issue by: 

```
        #SD vs SD  sct vs control
        sd_diff = named(p[0][0] - p[1][0], "sd_diff")
        #HD vs HD  sct vs control
        hd_diff = named(p[0][1] - p[1][1], "hd_diff")
        #HD vs SD  control
        control_diff = named(p[0][0] - p[0][1], "control_diff")
```

and 

```
tr = pm.sample(10000, step=step, trace=m.vars + [m.sd_diff, m.hd_diff, m.control_diff])
```

We could also have `sample` track all named variables by default.

**Comment by jsalvatier** [comment]
I think this pull request addresses this: https://github.com/pymc-devs/pymc/pull/325

**Comment by twiecki** [comment]
Closing as PR is merged.
