### ISSUE TITLE
Issues Building on Anaconda

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc3#194]
In setup.py, you currently check the build options of numpy to determine your library flags for the fortran subroutines:

```
lapack_info = get_info('lapack_opt',1)
...
if lapack_info:
    config.add_extension(name='flib',sources=f_sources, extra_info=lapack_info, f2py_options=['skip:ppnd7'])
```

However, in some situations, people might not have access to all of the Fortran libraries that were used during the numpy build.  Here is my lapack_info:

{'define_macros': [('SCIPY_MKL_H', None)],
 'include_dirs': ['/home/kyleb/opt/include'],
 'libraries': ['mkl_lapack95_lp64',
  'mkl_intel_lp64',
  'mkl_intel_thread',
  'mkl_core',
  'iomp5',
  'pthread'],
 'library_dirs': ['/home/kyleb/opt/lib']}

For now, I have a workaround where I manually clear the lapack_info to force the local blas build:

```
lapack_info = {}
```

**Comment by kyleabeauchamp** [comment]
As an aside, this seems to have different behavior between Enthought Python and Anaconda python.  In Enthought, here is lapack_info:

{'define_macros': [('NO_ATLAS_INFO', 1)],
 'language': 'f77',
 'libraries': ['lapack', 'blas'],
 'library_dirs': ['/usr/lib']}

**Comment by kyleabeauchamp** [comment]
PS: the missing library is mkl_lapack95_lp64

**Comment by kyleabeauchamp** [comment]
@ilanschnell This might be of interest to you.

More precisely, some people might be surprised when they encounter build issues they didn't previously see with EPD.

**Comment by fonnesbeck** [comment]
Thanks for reporting. I have not had anyone else complain about this, which is not to say that it does not occur. I'm admittedly not much of a distutils expert, so I'm not sure what the best way to deal with this might be. I guess I could have a setup.cfg file that folks could mess with. Suggestions welcome.

This problem will go away with PyMC3, which will have no Fortran extensions whatsoever.

**Comment by twiecki** [comment]
Closing in favor of https://github.com/pymc-devs/pymc/issues/556.
