### ISSUE TITLE
Implement factor potentials

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#195]
Alongside stochastic and deterministic nodes, there needs to be a facility in v.3 for adding arbitrary log-probability terms (or, factor potentials as we called them in PyMC 2) to models. These are essentially nodes that return a log-probability as part of the joint posterior distribution, but do not have a value associated with them. Most frequently, they are used to constrain some part of the model.

I assume this would be done in a similar way to a Variable, but without it being assigned to a step method.

**Comment by jsalvatier** [comment]
Yeah, shouldn't be too hard. Something like: 

```
def Potential(model, variables, potential): 
     model.factors += [potential(*variables)]

```

or even just

```
def AddFactor(model, factor):
    model.factors += [factor]
```

which would get used by `model.AddFactor(potential(a, b,c))`

Do you want to do this? I don't know what the major use cases are, so I don't know if there are other features I'm missing. Do potentials have other properties of importance?

**Comment by kyleabeauchamp** [comment]
I'm going to sign up for this thread.  When this issue gets resolved, I can start to think about porting my code to pymc3.

**Comment by jsalvatier** [comment]
Good to know! Any key features or advice related to factor potentials? Advice is useful.

**Comment by kyleabeauchamp** [comment]
Hmm, I was always puzzled that you cannot trace individual factor potentials in pymc2.  To me, it seems useful to be able to trace how the individual model components are contributing over time.  

That said, if this is causes difficulties in performance or maintainability, then it's not worth it.

**Comment by jsalvatier** [comment]
Oh, interesting. Is there a natural way you would expect to be able to do that?

**Comment by kyleabeauchamp** [comment]
I would forget I even said anything--this is not a super useful property, and I think it could be more confusion than it's worth...

**Comment by jsalvatier** [comment]
No example so far, but this is implemented now: 

```
with Model() as model: 
   x = Normal('x', 1,1)
   model.AddPotential(-x**2)
```

**Comment by jsalvatier** [comment]
Added a short example: https://github.com/pymc-devs/pymc/blob/pymc3/examples/factor_potential.py
