### ISSUE TITLE
Creating of arbitrary stochastic nodes

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#200]
One feature of PyMC 2 that might be hard to replicate in v.3 that has been enormously useful is the creating of arbitrary stochastics (and determinsitics, for that matter) using the `@stochastic` (or `@observed` for likelihoods) decorator. It comes in handy for adding non-standard distributions to a model. For example, in survival modeling, the log-likelihood for the parametric survival model with exponential hazard is:

```
@observed
def survival(value=t, lam=lam, f=failure):
    """Exponential survival likelihood, accounting for censoring"""
    return sum(f*log(lam) - lam*value)
```

This allows the user the ability to easily specify a stochastic node without building a class by hand.

**Comment by mamacneil** [comment]
I would agree - I use this a lot to create custom stochastics and feel it is a strength of PyMC to be able to do so easily.

**Comment by jsalvatier** [comment]
You can create arbitrary distributions very easily as long as they can be
described by theano operations. Theano is pretty expressive,  so this isn't
too  bad. But,  In order to have truly arbitrary distributions easily , you
need to create arbitrary theano operations easily.

I don't think this exists right now, but I suspect it would be possible to
add to Theano.

**Comment by jsalvatier** [comment]
We should probably have an example of  this.

**Comment by jsalvatier** [comment]
In the current syntax you would do something like:

```
@quickclass
def Survival(lam, f): 
    """Exponential survival distribution, accounting for censoring"""
    def logp(value): 
        return sum(f*log(lam) - lam*value)
    return locals()

x = Data(t, Survival(lam, failure))
```

A distribution is just an object that has the required properties (usually, a `logp` function, but can also include other things). `@quickclass` just creates a class from a function that returns a dict. This is the exact way we define distributions in pymc/distributions/. 

Are there other features we need? Obviously an example would be good to include.

**Comment by twiecki** [comment]
Maybe one could just pass in a theano expressions instead of something that returns a theano expression once .logp() is called. That would be even simpler than in pymc2.

**Comment by jsalvatier** [comment]
Well for observed nodes, you could just do it via adding a potential (not yet added):

```
lp = sum(failure*log(lam) - lam*t)
x = AddPotential(lp)
```

For unobserved nodes, you would have to at least pass a logp() function since pymc has to create the tensor variable. 

```
def lp(value): 
    return sum(failure*log(lam) - lam*value)
x = Var('x', LogPDist(lp))
```

**Comment by fonnesbeck** [comment]
Can the call to LogPDist be automated when a function is passed Var? Alternately, a decorator might work, as which would be very similar to the current implementation.

**Comment by jsalvatier** [comment]
Well, I just got the `Normal('x', mu, tau, shape)` syntax to work, so, you should just be able to say `x = LogPDist('x', sum(failure*log(lam) - lam*value))`. Is that good?

**Comment by jsalvatier** [comment]
No example as of yet, but this is now implemented:

```
def logp(lam):
     return sum(failure*log(lam) - lam*value)

x =  DensityDist('x', logp)
```

**Comment by jsalvatier** [comment]
I added a short example: https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/arbitrary_stochastic.py

**Comment by frmsaul** [comment]
Hi @jsalvatier, 

The link you shared is dead. Would you mind editing your comment and changing it to this: [https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/arbitrary_stochastic.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/arbitrary_stochastic.py)
