### ISSUE TITLE
Example of setting random seed

### ISSUE THREAD

**Issue by gaborgulya** [pymc-devs/pymc3#201]
What is the best way to set the seed of the random number generator? So as to guarantee the same output after each run.
Could you please modify the https://github.com/pymc-devs/pymc/wiki/NormalFit example to demonstrate this?
Many thanks

**Comment by fonnesbeck** [comment]
The seed is set via numpy. I have changed the example on the wiki to demonstrate this.

**Comment by gaborgulya** [comment]
Many thanks!
