### ISSUE TITLE
Activate pymc3 branch on travis-ci.org

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#202]
@jsalvatier Someone from pymc-devs group has to create a travis-ci account and enable pymc to be tracked.

**Comment by fonnesbeck** [comment]
I've added you to pymc-devs.

**Comment by twiecki** [comment]
Thanks!

I tried doing it but alas, as it turns out the webhooks they use require admin rights so probably @fonnesbeck is the only one who can do it then. It's quite simple, you can login with your github credentials on travis-ci.org, you then go to Accounts (upper right corner), pymc-devs and activate pymc.

**Comment by fonnesbeck** [comment]
Done.
