### ISSUE TITLE
Autocorrelation plots

### ISSUE THREAD

**Issue by CamDavidsonPilon** [pymc-devs/pymc3#203]
Hey devs, 

I'm curious about why the autocorrelation plots are symmetrically displayed with 0 in the center, instead of starting the left-hand side of the plot as 0 (or 1) lag. Thanks!

**Comment by fonnesbeck** [comment]
It's purely a stylistic choice. Some think it is easier to view since the section of the acf that is of interest ( generally values closer to zero) are in the center of the plot rather than at the left. We may switch back in future versions, or at least make it optional.

**Comment by CamDavidsonPilon** [comment]
Ah, I see. Thanks Chris.
