### ISSUE TITLE
Failure in test_LazyFunction.py

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#204]
Really bizarre failure in `test_LazyFunction.py` whereby the test fails if the debugging string in line 48 is not printed! Commenting out the print statement or changing the string appreciably causes failure. I have no earthly idea how printing a string should affect cached counts. May have to kill this test and write a new one.

**Comment by cournape** [comment]
I have seen the same behaviour on multiple platforms (at leasat rhel5 and mac os x). I noticed that the failure is correlated to the if acc branch around line 95 to be executed many times (success) or only once (failure). Not sure whether that helps

**Comment by fonnesbeck** [comment]
This appears to have been fixed (finally) in 5ebb2fa03022aee79d3b4105e83a309dd28187a8.
