### ISSUE TITLE
MCMC is memory costing.

### ISSUE THREAD

**Issue by hyissue** [pymc-devs/pymc3#205]
When the number of Stochastic variables are large, e.g. 1,000, it is memory costing when I call a=pymc.MCMC(model). I wonder why? Thank you.

**Comment by fonnesbeck** [comment]
Does this happen when you instantiate the `MCMC` object, or when you call `sample`? It would be understandable on `sample` because the default ram backend will preallocated traces for all the stochastics in memory. Can you try another backend, for example:

```
a = pymc.MCMC(model, db='sqlite')
```

and see if the memory usage persists?

**Comment by hyissue** [comment]
It happens when I instantiate the MCMC object. It costs about 30 GB memory when the number of stochastic is 1,000.

**Comment by fonnesbeck** [comment]
Is it just any 1000 variables, or just your particular example? What about:

```
x = [Normal('x_{0}'.format(i), 0, 1) for i in range(1000)]
```

How much data is associated with the parameters if any? It would be helpful if you could post an example (even if simplified), to see if I can replicate the issue.

**Comment by piantado** [comment]
I don't know about the original poster, but I just had this problem of huge memory usage (tens of GB, hard to kill process) when I call pymc.MCMC(model). I traced it to doing something like,

```
p = pymc.Container([pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)])
x = pymc.Bernoulli('x', p)
```

instead of 

```
p = pymc.Container([pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)])
x = pymc.Container([pymc.Bernoulli('x_%i'%i, p[i]) for i in xrange(1000)])
```

I'm not sure why the former uses so much memory though.

**Comment by fonnesbeck** [comment]
Unless there is a reason not to, the best approach is to create a single, vector-valued Beta:

```
p = pymc.Beta('p', 1, 1, size=1000)
```

By the way, you _do_ need 1000 individual betas, there is no need to call `Container` directly; PyMC will do the work for you:

```
p = [pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)]
```

On my machine, this consumes 575 MB memory; the vector-valued `p` only uses 80 MB. 

Are you using PyMC built from the GitHub master, or a binary release?

**Comment by piantado** [comment]
Here is some code. If I use size=1000 everything works. If I don't use an explicit container, I get a "TypeError: hasattr(): attribute name must be string". If I write an explicit container, it eats memory. I was using an ubuntu binary but just checked out from here. Version 2.2

```
import pymc

def make_model():

    #p = pymc.Beta('p', 1, 1, size=1000) ## Works great
    #p = [pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)] ## gives TypeError: hasattr(): attribute name must be string
    p = pymc.Container([pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)]) ## Eats memory

    x = pymc.Bernoulli('x', p, size=1000)

    return locals()

model = pymc.Model(make_model())
#mcmc = pymc.MCMC(model)
#mcmc.sample(100)
```

**Comment by fonnesbeck** [comment]
I can't reproduce either the memory issue (beyond the 500MB that I reported above) or the AttributeError. Are you getting these issues with the latest GitHub checkout?

**Comment by fonnesbeck** [comment]
Definitely try building from source; there have been plenty of bugs fixed since the 2.2 release. I need to get a 2.3 release done soon.

**Comment by piantado** [comment]
Thanks, I rebuilt it  and now I get the same issues at pymc.MCMC(model), but _not_ if I only run pymc.Model(make_model()) as before.

```
import pymc

def make_model():

    #p = pymc.Beta('p', 1, 1, size=1000) ## Works great
    #p = [pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)] ## gives TypeError: hasattr(): attribute name must be string
    p = pymc.Container([pymc.Beta('p_%i'%i, 1., 1.) for i in xrange(1000)]) ## Eats memory

    x = pymc.Bernoulli('x', p, size=1000)

    return locals()

model = pymc.Model(make_model())
mcmc = pymc.MCMC(model)
```

**Comment by fonnesbeck** [comment]
You need not call Model explicitly; just as with `Container`, this is all taken care of by PyMC. You just need to call:

```
mcmc = pymc.MCMC(make_model())
```

I'm still confused by the error, though. I can't replicate it.

**Comment by piantado** [comment]
Well, that seems to fix my problem--everything works when I call pymc.MCMC(make_model()). Thanks for your help.
