### ISSUE TITLE
Implement No U-Turn Sampler

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#207]
Seems to work quite well for Stan, so we should steal this.

**Comment by jsalvatier** [comment]
I have a [draft](https://github.com/pymc-devs/pymc/blob/nuts/pymc/step_methods/nuts.py) without the dual averaging. However there must be something wrong since it seems to generate samples with [too much variance](http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/nuts/examples/nutstest.ipynb).

**Comment by twiecki** [comment]
What's that testing? Recovery of a single data point?

```
xtrue = normal(scale = 2., size = 1)
```

**Comment by jsalvatier** [comment]
I think I just forgot to remove that. It doesn't do anything.

**Comment by twiecki** [comment]
Oh right, you're just sampling from the prior. I see now.

**Comment by jsalvatier** [comment]
I think I've got the NUTS part working in https://github.com/pymc-devs/pymc/tree/nuts2, and the step size adjustment is implemented, but I don't think its working right.

**Comment by twiecki** [comment]
Nice! What makes you think it's not working? Maybe now would be a good time to check with the stan guys?

**Comment by jsalvatier** [comment]
In the stochastic volatility example, the step size seems to get adjusted to be so large that only 1 step is done. This means all the steps are rejected. 

I have been talking to them, and they've been helpful.

**Comment by twiecki** [comment]
Oh, that seems like it might be a corner-case. I'll try it for the GLM.

**Comment by jsalvatier** [comment]
I think this is working now, but still needs cleanup and tests and such. Try it on the GLM and let me know how it works. 

I'm excited to get this working especially with some automatic scale finding.

**Comment by twiecki** [comment]
Nice, I'll give it a test run tomorrow.

**Comment by jsalvatier** [comment]
Pull request in #285
