### ISSUE TITLE
Gelman-Rubin should catch non-equal-length chains

### ISSUE THREAD

**Issue by keflavich** [pymc-devs/pymc3#209]
`gelman_rubin` checks for multiple chains, but doesn't check that the chains are the same length, and fails with the opaque (since incorrect) error:
`ValueError: Gelman-Rubin diagnostic requires multiple chains.`

I'm not entirely clear whether the statistic is valid for non-equal chain lengths, but certainly numpy doesn't allow the tricks being used when chain lengths are different.

**Comment by fonnesbeck** [comment]
How did you manage to pass multiple chains of unequal length to the function? A list of arrays?

**Comment by keflavich** [comment]
I just did a few different samples:

```
mc.sample(100)
mc.sample(1000)
mc.sample(10000)
```

then tried `pymc.Matplot.summary_plot(mc)`

**Comment by fonnesbeck** [comment]
This should be taken care of now. Please test.
