### ISSUE TITLE
autopep8 code base

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#218]
There are quite a few white-space issues on the current pymc3 branch and pep8 divergences. The former gets automatically fixed by some editors leading to huge diffs even though the code change might be small.

autopep8 makes the whole code base conform to pep8 standard and fixes any white space issues.

It's quite easy to do but would need a good time point when no one is on a separate branch or has unpushed changes. Let me know.

**Comment by fonnesbeck** [comment]
Sorry, much of this is due to my TextMate bundle that strips trailing whitespaces every time it saves. I think you could go ahead and do it any time; we can rebase before merging.

**Comment by twiecki** [comment]
I think that's actually a very nice feature -- emacs does the same. @jsalvatier should probably just start using a decent editor ;P (teasing, obviously).

I think rebasing would be a nightmare as there will certainly be conflicts which would have to be resolved manually. Your branch @fonnesbeck is probably the only unmerged one currently? In that case it's easy enough to just wait.

**Comment by fonnesbeck** [comment]
If we ready to merge the tuning feature for Metropolis in #214 then that is all that I have waiting. For some reason I thought @jsalvatier had a merge waiting too, though.

**Comment by jsalvatier** [comment]
I have this https://github.com/pymc-devs/pymc/pull/215 merge waiting. Right
before release might a good time.

**Comment by jsalvatier** [comment]
Maybe now would be a good time to do this? I don't have anything out.

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc/pull/232
