### ISSUE TITLE
Should Normal be parameterized by precision or variance or stdev by default? 

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#219]
I tend to think that Normal should be parameterized by the standard deviation by default, since I think this is how people usually think about such things and because we're not doing much gibbs sampling. I think this will be friendlier to noobs and less verbose. 

We should also have a NormalPrec for normal distribution parameterized by precision. 

The major reason to prefer keeping Normal parameterized by precision is that that's the way it is in pymc2.

This is probably something we should decide before we release since we're probably stuck with the decision.

What do you guys think? @fonnesbeck @twiecki

**Comment by fonnesbeck** [comment]
Parameterizing with precision is pretty standard in Bayes, and has found its way into most of the software, including JAGS and BUGS from which many new PyMC users will be familiar. In PyMC2 we do have multivariate normals parameterized both ways for a few cases where it may be advantageous to work with the covariance matrix instead.

My vote is to stick with precision, and have a NormalCov alternative.

**Comment by twiecki** [comment]
I'm happily overruled by @fonnesbeck but I agree with @jsalvatier -- standard deviation is how normals are introduced in most classes and textbooks. Numpy and scipy also use std. I wonder why Bayesian software started to go with precision almost exclusively. It certainly is a source of confusion for the studients in the bayesian stats class I'm TAing.

The NormalCov alternative is also reasonable. Alternatively, we could have Normal take tau and sigma kwargs and use the parameterization depending on what was passed.

**Comment by fonnesbeck** [comment]
It started because of conjugacy: the conjugate prior for precision is a gamma, as opposed to an inverse gamma as a conj. prior for the variance. Same goes for the (inverse) Wishart for the multivariate normal. Folks were just happier working with non-inverted distributions. These are all conventions, so my suggestion is to stick with the "industry de factor standard". Its only a suggestion, so I can be overruled if there is a stronger pull in the other direction.

**Comment by fonnesbeck** [comment]
I just posted an [informal poll on Twitter](https://twitter.com/fonnesbeck/status/330031831971950592). Let's see what Bayesians have to say on the matter.

**Comment by jsalvatier** [comment]
What if we had a distributions.conjugate module that had Normal parameterized by precision (along with anything else with similar issues). Then the only difference will be which module is imported. could be kind of error prone though.

**Comment by twiecki** [comment]
Yeah, I think that'd be confusing if it had the same name but only a different import path. I do think `Normal('x', mu=0, sigma=1)` and `Normal('x', mu=0, tau=1)` is pretty obvious of what it's doing. Maybe a little weird behind the scenes though with a conditional.

**Comment by jsalvatier** [comment]
Dang, that poll seems to be evenly split...

Maybe we adopt @twiecki's solution but leave tau as the default?

**Comment by fonnesbeck** [comment]
Well, it could all be sampling error, of course, since only 5 have responded. I think using the keyword argument might solve the problem.

**Comment by twiecki** [comment]
Closing this as we seemed to decide on the optional sd parameter and a PR is out.
