### ISSUE TITLE
HMC fails without scikits.sparse installed

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#223]
Without installing scikits.sparse, using the HMC sampler does not work (see below). While its fine to require the package, when its an optional package it should fail more gracefully than this, by checking for the package on initialization and returning an informative message, instead of a cryptic exception.

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-62f83321ba5d> in <module>()
      1 with model:
----> 2     step = HamiltonianMC(model.vars, hessian(start, 6))
      3     trace = sample(200, step, start, trace = model.vars + [sigma])
      4 
      5     # Start next run at the last sampled position.

/Users/fonnescj/Code/pymc3/pymc/step_methods/hmc.py in __init__(self, vars, C, step_scale, path_length, is_cov, step_rand, state, model)
     45         self.step_size = step_scale / n**(1/4.)
     46 
---> 47         self.potential = quad_potential(C, is_cov)
     48         self.path_length = path_length
     49         self.step_rand = step_rand

/Users/fonnescj/Code/pymc3/pymc/step_methods/quadpotential.py in quad_potential(C, is_cov)
     14 
     15     if issparse(C):
---> 16         return QuadPotential_SparseInv(C)
     17 
     18     partial_check_positive_definite(C)

NameError: global name 'QuadPotential_SparseInv' is not defined
```

**Comment by fonnesbeck** [comment]
I changed HamiltonianMC (tutorial-fixup branch) to raise an error when a sparse scaling matrix is passed without scikits.sparse in f43a0e44a2db2a0ce757cf645e0149a3057e1fc6 . Will this work?

**Comment by twiecki** [comment]
Seems like the same issue as here https://github.com/pymc-devs/pymc/pull/225. I'm also not sure it fixes the error in the right way as I don't see where it checks for whether scikits.sparse is installed? I think #225 should do the trick though.
