### ISSUE TITLE
Stochastic Volatility example doesn't run without scikits.sparse

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#227]
The Stochastic Volatility example doesn't run without scikits.sparse. Unfortunately, this is apparently hard to install on mac and probably really difficult on windows. 

I'm seeing how well it runs without the sparse scaling.

**Comment by jsalvatier** [comment]
Fixed.

**Comment by twiecki** [comment]
What's the problem with scikits.sparse on win and mac?

**Comment by jsalvatier** [comment]
@johmmcdonnell reported it was a pain to install scikits.sparse. The major issue is that it involve installing libsuitsparse-dev.

**Comment by fonnesbeck** [comment]
I had similar issues with scikits.sparse on OS X. I would suggest wrapping CHOLMOD stuff ourselves, but it has unfriendly licensing (i.e. GPL). What about [CHOMPACK](http://abel.ee.ucla.edu/chompack/pythonapi.html)?

**Comment by jsalvatier** [comment]
That seems like it might be a possibility. What I need is something that
gives fast solves with a sparse matrix and fast multiplications with the
cholesky decomposition of that matrix. It looks like CHOMPACK might do that.
