### ISSUE TITLE
Error in Stochastic Volatility example

### ISSUE THREAD

**Issue by fccoelho** [pymc-devs/pymc3#230]
I am getting the following error the fitting cell

---

AssertionError                            Traceback (most recent call last)
<ipython-input-7-925cce8e2cc3> in <module>()
----> 1 H = model.d2logpc()
      2 
      3 def hessian(point, nusd):
      4     h = H(Point(point))
      5     h[1,1] = nusd**-2

/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc in d2logpc(model, vars)
     78     def d2logpc(model, vars = None):
     79         """Compiled log probability density hessian function"""
---> 80         return compilef(hessian(model.logp, vars))
     81 
     82     @property

/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc in hessian(f, vars)
    211 
    212 def hessian(f, vars = None):
--> 213     return -jacobian(gradient(f, vars), vars)
    214 
    215 

/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc in gradient(f, vars)
    192         vars = cont_inputs(f)
    193 
--> 194     return t.concatenate([gradient1(f, v) for v in vars], axis = 0)
    195 
    196 def jacobian1(f, v):

/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc in gradient1(f, v)
    186 def gradient1(f, v):
    187     """flat gradient of f wrt v"""
--> 188     return t.flatten(t.grad(f, v, disconnected_inputs='warn'))
    189 
    190 def gradient(f, vars = None):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in grad(cost, wrt, consider_constant, disconnected_inputs, add_names, known_grads, return_disconnected)
    525 
    526     rval = _populate_grad_dict(var_to_app_to_idx,
--> 527             grad_dict, wrt, cost_name)
    528 
    529     for i in xrange(len(rval)):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
   1064         return grad_dict[var]
   1065 
-> 1066     rval = [access_grad_cache(elem) for elem in wrt]
   1067 
   1068     return rval

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_grad_cache(var)
   1024                     for idx in node_to_idx[node]:
   1025 
-> 1026                         term = access_term_cache(node)[idx]
   1027 
   1028                         if not isinstance(term, gof.Variable):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_term_cache(node)
    779             inputs = node.inputs
    780 
--> 781             output_grads = [access_grad_cache(var) for var in node.outputs]
    782 
    783             # list of bools indicating if each output is connected to the cost

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_grad_cache(var)
   1024                     for idx in node_to_idx[node]:
   1025 
-> 1026                         term = access_term_cache(node)[idx]
   1027 
   1028                         if not isinstance(term, gof.Variable):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_term_cache(node)
    779             inputs = node.inputs
    780 
--> 781             output_grads = [access_grad_cache(var) for var in node.outputs]
    782 
    783             # list of bools indicating if each output is connected to the cost

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_grad_cache(var)
   1024                     for idx in node_to_idx[node]:
   1025 
-> 1026                         term = access_term_cache(node)[idx]
   1027 
   1028                         if not isinstance(term, gof.Variable):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_term_cache(node)
    779             inputs = node.inputs
    780 
--> 781             output_grads = [access_grad_cache(var) for var in node.outputs]
    782 
    783             # list of bools indicating if each output is connected to the cost

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_grad_cache(var)
   1024                     for idx in node_to_idx[node]:
   1025 
-> 1026                         term = access_term_cache(node)[idx]
   1027 
   1028                         if not isinstance(term, gof.Variable):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_term_cache(node)
    779             inputs = node.inputs
    780 
--> 781             output_grads = [access_grad_cache(var) for var in node.outputs]
    782 
    783             # list of bools indicating if each output is connected to the cost

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_grad_cache(var)
   1024                     for idx in node_to_idx[node]:
   1025 
-> 1026                         term = access_term_cache(node)[idx]
   1027 
   1028                         if not isinstance(term, gof.Variable):

/usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in access_term_cache(node)
    892                     assert getattr(ng.type, 'dtype', None) not in theano.tensor.discrete_dtypes
    893 
--> 894                 input_grads = node.op.grad(inputs, new_output_grads)
    895 
    896                 if input_grads is None:

/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.pyc in grad(self, inputs, ograds)
    661 
    662         #compute grad with respect to broadcasted input
--> 663         rval = self._bgrad(inputs, ograds)
    664 
    665         # TODO: make sure that zeros are clearly identifiable

/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.pyc in _bgrad(self, inputs, ograds)
    739             scalar_igrads = self.scalar_op.grad(scalar_inputs, scalar_ograds)
    740             for igrad in scalar_igrads:
--> 741                 assert igrad is not None
    742 
    743         finally:

AssertionError:

**Comment by jsalvatier** [comment]
I think this is probably due to the Theano version. Try getting theano from
the github repo https://github.com/Theano/Theano

**Comment by fccoelho** [comment]
Thanks John,

You nailed it.

On Sun, May 5, 2013 at 1:57 PM, John Salvatier notifications@github.comwrote:

> I think this is probably due to the Theano version. Try getting theano
> from
> the github repo https://github.com/Theano/Theano
> 
> On Sun, May 5, 2013 at 3:40 AM, Flávio Codeço Coelho <
> notifications@github.com> wrote:
> 
> > ## I am getting the following error the fitting cell
> > 
> > AssertionError Traceback (most recent call last)
> > in ()
> > ----> 1 H = model.d2logpc()
> > 2
> > 3 def hessian(point, nusd):
> > 4 h = H(Point(point))
> > 5 h[1,1] = nusd**-2
> > 
> > /usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc
> > in d2logpc(model, vars)
> > 78 def d2logpc(model, vars = None):
> > 79 """Compiled log probability density hessian function"""
> > ---> 80 return compilef(hessian(model.logp, vars))
> > 81
> > 82 @property https://github.com/property
> > 
> > /usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc
> > in hessian(f, vars)
> > 211
> > 212 def hessian(f, vars = None):
> > --> 213 return -jacobian(gradient(f, vars), vars)
> > 214
> > 215
> > 
> > /usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc
> > in gradient(f, vars)
> > 192 vars = cont_inputs(f)
> > 193
> > --> 194 return t.concatenate([gradient1(f, v) for v in vars], axis = 0)
> > 195
> > 196 def jacobian1(f, v):
> > 
> > /usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/model.pyc
> > in gradient1(f, v)
> > 186 def gradient1(f, v):
> > 187 """flat gradient of f wrt v"""
> > --> 188 return t.flatten(t.grad(f, v, disconnected_inputs='warn'))
> > 189
> > 190 def gradient(f, vars = None):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in grad(cost,
> > wrt, consider_constant, disconnected_inputs, add_names, known_grads,
> > return_disconnected)
> > 525
> > 526 rval = _populate_grad_dict(var_to_app_to_idx,
> > --> 527 grad_dict, wrt, cost_name)
> > 528
> > 529 for i in xrange(len(rval)):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
> > 1064 return grad_dict[var]
> > 1065
> > -> 1066 rval = [access_grad_cache(elem) for elem in wrt]
> > 1067
> > 1068 return rval
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_grad_cache(var)
> > 1024 for idx in node_to_idx[node]:
> > 1025
> > -> 1026 term = access_term_cache(node)[idx]
> > 1027
> > 1028 if not isinstance(term, gof.Variable):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_term_cache(node)
> > 779 inputs = node.inputs
> > 780
> > --> 781 output_grads = [access_grad_cache(var) for var in node.outputs]
> > 782
> > 783 # list of bools indicating if each output is connected to the cost
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_grad_cache(var)
> > 1024 for idx in node_to_idx[node]:
> > 1025
> > -> 1026 term = access_term_cache(node)[idx]
> > 1027
> > 1028 if not isinstance(term, gof.Variable):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_term_cache(node)
> > 779 inputs = node.inputs
> > 780
> > --> 781 output_grads = [access_grad_cache(var) for var in node.outputs]
> > 782
> > 783 # list of bools indicating if each output is connected to the cost
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_grad_cache(var)
> > 1024 for idx in node_to_idx[node]:
> > 1025
> > -> 1026 term = access_term_cache(node)[idx]
> > 1027
> > 1028 if not isinstance(term, gof.Variable):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_term_cache(node)
> > 779 inputs = node.inputs
> > 780
> > --> 781 output_grads = [access_grad_cache(var) for var in node.outputs]
> > 782
> > 783 # list of bools indicating if each output is connected to the cost
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_grad_cache(var)
> > 1024 for idx in node_to_idx[node]:
> > 1025
> > -> 1026 term = access_term_cache(node)[idx]
> > 1027
> > 1028 if not isinstance(term, gof.Variable):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_term_cache(node)
> > 779 inputs = node.inputs
> > 780
> > --> 781 output_grads = [access_grad_cache(var) for var in node.outputs]
> > 782
> > 783 # list of bools indicating if each output is connected to the cost
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_grad_cache(var)
> > 1024 for idx in node_to_idx[node]:
> > 1025
> > -> 1026 term = access_term_cache(node)[idx]
> > 1027
> > 1028 if not isinstance(term, gof.Variable):
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/gradient.pyc in
> > access_term_cache(node)
> > 892 assert getattr(ng.type, 'dtype', None) not in
> > theano.tensor.discrete_dtypes
> > 893
> > --> 894 input_grads = node.op.grad(inputs, new_output_grads)
> > 895
> > 896 if input_grads is None:
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.pyc in
> > grad(self, inputs, ograds)
> > 661
> > 662 #compute grad with respect to broadcasted input
> > --> 663 rval = self._bgrad(inputs, ograds)
> > 664
> > 665 # TODO: make sure that zeros are clearly identifiable
> > 
> > /usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.pyc in
> > _bgrad(self, inputs, ograds)
> > 739 scalar_igrads = self.scalar_op.grad(scalar_inputs, scalar_ograds)
> > 740 for igrad in scalar_igrads:
> > --> 741 assert igrad is not None
> > 742
> > 743 finally:
> > 
> > AssertionError:
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/pymc-devs/pymc/issues/230>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pymc-devs/pymc/issues/230#issuecomment-17454713
> .

## 

# Flávio Codeço Coelho

+55(21) 3799-5567
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil
