### ISSUE TITLE
Discrete Metropolis and other discrete samplers

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#231]
At present, PyMC 3 does not have any samplers that work efficiently with discrete and binary random variables (except of course, under certain conditions, the Gibbs step).

**Comment by fonnesbeck** [comment]
I will start working on DiscreteMetropolis and BinaryMetropolis on the `metropolis` feature branch.

**Comment by fonnesbeck** [comment]
It may be possible just to generalize Metropolis to detect discrete variables and round the proposals. We could do this a few different ways:
1. Add `isdiscrete` flags to each distribution, which can be checked by the step function.
2. Have a list of discrete distributions, and have the step function check for membership in the list.
3. Add a `discrete` flag to `Metropolis`.
4. Subclass Metropolis.

Option 2 would be the least friendly to extending PyMC, since if I create a new, arbitrary stochastic, it will not be in the list. Option 4, which is how we did things in PyMC 2 would require a lot of copy-pasting of code unless we refactor Metropolis to better accommodate it.

**Comment by jsalvatier** [comment]
Each random variable already has a `dtype` property (which is like 'int64' or 'float32') property already from which you should be able to tell if its discrete.

**Comment by jsalvatier** [comment]
I think you took care of this quite well! I think we've got the basic discrete samplers down now. Good work.
