### ISSUE TITLE
Travis fails, exceeds time limit.

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#237]
Since some days our travis build hangs. Any tests added that take a long time to run?

https://s3.amazonaws.com/archive.travis-ci.org/jobs/6910650/log.txt

```
[?1049h[?1h=
Help on Model in module pymc.model object:

class [1mModel[0m(Context)
 |  Base class for encapsulation of the variables and
 |  likelihood factors of a model.
 |  
 |  Method resolution order:
 |      Model
 |      Context
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  [1mAddPotential[0m(model, potential)
 |  
 |  [1mData[0m(model, data, dist)
 |  
 |  [1mTransformedVar[0m(model, name, dist, trans)
 |  
 |  [1mVar[0m(model, name, dist)
 |  
 |  [1m__init__[0m(self)
 |  
:[K

I'm sorry but your test run exceeded 50.0 minutes. 

One possible solution is to split up your test run.
```

**Comment by jsalvatier** [comment]
I'd be totally OK with paying money in turn for allowing longer builds, but they don't seem to offer that yet.

Could we have the virtual machine preloaded with some of the dependencies?

The other thing to do is make the tests complete faster. Fixing https://github.com/pymc-devs/pymc/issues/236 might help.

**Comment by fonnesbeck** [comment]
The tests seem to be stalling, as opposed to running tests for too long:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

I've experienced this myself occasionally when running tests locally.

**Comment by jsalvatier** [comment]
Some of them seem that way, but some of them seem like they got to 50 minutes. I think the stalling issue was perhaps due to the lambda during parallel sampling issue (which hangs tests locally for me). 

@twiecki is there a reason we nosetests run with the -s option? not capturing output makes the output hard to read. I would sort of like the -v option, tells you what tests are running.

If Theano doesn't complain, it would be cool to run the tests in parallel http://nose.readthedocs.org/en/latest/plugins/multiprocess.html.

**Comment by twiecki** [comment]
I was wondering about the parallel sampling tests. I remember that I had to fix something about them but I think the reason was that multiprocessing failed to import. In any case, that's a likely source for the problems.

I just used -s to get more output but -v would work too.

I would be surprised if travis allowed you to run the tests in parallel but I might be wrong.

**Comment by jsalvatier** [comment]
There's also this:
http://about.travis-ci.org/blog/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
.
I'm trying to separate the example tests and other tests here:
https://github.com/pymc-devs/pymc/tree/travisoutput

**Comment by jsalvatier** [comment]
Fixed.
