### ISSUE TITLE
traceplot double-plotting in iPython notebook

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#243]
I have no earthy idea why this would happen, but calling traceplot in the iPython notebook causes [double plotting of the passed variable](http://cl.ly/OpSt). The same model exported to a .py script does not exhibit this behavior. Anyone else seen this?

**Comment by jsalvatier** [comment]
Yes, I think it's because traceplot returns a figure, so it gets plotted
both from the internal calls and from the returned figure. An easy fix
would be to remove the returned figure. Adding a  `;` at the end also stops
this.

**Comment by fonnesbeck** [comment]
Aha. That's fine. `_ = traceplot()` should do the trick for me, then.
