### ISSUE TITLE
attributeError in Binomial variables

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#244]
Using a Binomial in as a non-observed stochastic results in an AttributeError being raised. For example:

```
quitters_pred = Binomial('quitters_pred', n=n, p=p_quit)
```

yields:

```
AttributeError: <pymc.quickclass.Binomial object at 0x10755f650> does not have a value for any of: ['mode']
```

whereas an observed variable does not:

```
quitters = Binomial('quitters', n=n, p=p_quit, observed=y) 
```

**Comment by jsalvatier** [comment]
That is weird, can you check to see if you haven't reassigned Binomial or
something? Binomial does have tests that don't use observed:
https://github.com/pymc-devs/pymc/blob/pymc3/pymc/tests/test_distributions.py

**Comment by fonnesbeck** [comment]
I figured it out. Some of the discrete variables were missing mode attributes. Should be fixed in the commit above.
