### ISSUE TITLE
Discrete sampling example

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#246]
We should have an example of sampling a discrete distribution using `BinaryMetropolis` and `Metropolis`.

**Comment by fonnesbeck** [comment]
`latent_occupancy.py` uses a Bernoulli, so I had incorporated BinaryMetropolis there. I will dig up a binomial or Poisson example for the discrete Metropolis.

**Comment by fonnesbeck** [comment]
A discrete example is in the pull request in #250

**Comment by jsalvatier** [comment]
Great!
