### ISSUE TITLE
Can we get past transient state in hierarchical model?	

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#25]
An apparent bug in AdaptiveMetropolis, detailed in [this issue](http://code.google.com/p/pymc/issues/detail?id=269) on Google Code.

**Comment by dmarx** [comment]
The google code link is dead. Also, considering this issue is two years old, can it be closed? Without the google code link, it's not clear what the bug discussed even is.

**Comment by fonnesbeck** [comment]
Old issue from v.2.x.
