### ISSUE TITLE
Location of examples folder

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#251]
Is there a reason for keeping the examples outside of the `pymc` directory? It would be easier to access them (via `from pymc.examples import ...`) if we moved them.

**Comment by jsalvatier** [comment]
No, I don't think there is. Lets do it. That should make running the examples as tests a bit easier too.

**Comment by fonnesbeck** [comment]
Great. Will do this in my "diagnostics" branch, as my tests make use of an example.
