### ISSUE TITLE
Support for data in pandas Series/DataFrame formats

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#256]
If data in either `Series` or `DataFrame` formats are passed to the `observed` argument, it raises an AssertionError from Theano, which is checking for a Numpy array. We should probably do the type conversion, since `DataFrame` is such a common data structure these days.

**Comment by jsalvatier** [comment]
It would be good to talk to the Theano list about this, because we probably also want to support using `DataFrame` and `Series` as predictor variables. It would be nice if it was Theano that supported this, but we can do some casting in the mean time.

**Comment by twiecki** [comment]
Agreed. The casting is pretty easy though as dataframes are just numpy arrays underneath you can access via `DataFrame.values`

**Comment by fonnesbeck** [comment]
Simple tweak in 9869f10fdf7fd78f315f893775d242c2f8b0917e should work for now. Does not deal with pandas data structures in a list or tuple, but I think we can live with that.

**Comment by twiecki** [comment]
Seems to work fine so closing.
