### ISSUE TITLE
More obvious model specification syntax

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#258]
Right now `Normal('name', ...)` returns a random variable and `Normal(...)` returns a distribution. 

This seems a bit subtle and potentially confusing, so it would be nice if we could make this more obvious. What about having `Normal` always take a name and return a random variable and `Normal.dist` or `Normal.new` return a distribution?

**Comment by fonnesbeck** [comment]
A `dist` staticmethod (classmethod?) works for me. I think we had a discussion about this a while back. Some suggestions included:
- lower case for distribution, capitalized first letter for random variable
- `normal_dist` for distribution, which is analogous to `normal_like` in PyMC2

Happy with a staticmethod though.

**Comment by jsalvatier** [comment]
Yeah, I've come around.

I like the classmethod version a bit better because the lowercase/_dist
versions seem like they'll involve more ugly meta-programming. (you have to
create two variables out of one which is going to require injecting stuff
into the namespace). They also seem less aesthetic to me.

**Comment by twiecki** [comment]
But would `Normal('name', ...)` work as before? I think that's the main usage so should be easy syntax. `Normal.dist()` seems good to me.

**Comment by jsalvatier** [comment]
Yup!

**Comment by fonnesbeck** [comment]
Are we happy with this one now? How is the distribution specification faring for everyone?

**Comment by twiecki** [comment]
I think it's great.

**Comment by jsalvatier** [comment]
I think it works pretty well.
