### ISSUE TITLE
Betabin test stalling

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#259]
This isn't a new test, so I'm not sure why its stalling, but it is.

**Comment by fonnesbeck** [comment]
I increased the upper end of the `Nat` sequence to accommodate the Geometric distribution, which will make the test take longer, but should not stall outright.

**Comment by jsalvatier** [comment]
Yeah, you're right, I think that was the issue. I'm just going to make a 'Nathuge' for the geometric distribution to use so the tests complete in a more reasonable amount of time and Travis can cope.

**Comment by jsalvatier** [comment]
Fixed.
