### ISSUE TITLE
Uniform testval not acting as expected for certain parameter ranges

### ISSUE THREAD

**Issue by mmargenot** [pymc-devs/pymc3#2651]
Upon defining a `Uniform` random variable, certain values of `lower` and `upper` make setting `testval` not perform as expected. 

If I define:
```
with pm.Model as example:
    a = pm.Uniform('alpha', lower=-64, upper=64, testval=0)
```

and subsequently examine `a.tag.test_value`, I get back `array([-128])` instead of `array([0.0])`. This leads to problems with sampler initialization further down the line if I reuse `a` as, for example, the mean of a `Normal` likelihood.

Similar issues occur with values of `lower` and `upper` up to +/-127.
```
with pm.Model as example:
    a = pm.Uniform('alpha', lower=-127, upper=127, testval=0)
```
Outside of the 64-127 range, there is no trouble with `testval` and setting it equal to `0` performs as expected.

```
with pm.Model as example:
    a = pm.Uniform('alpha', lower=-128, upper=128, testval=0)
```
and
```
with pm.Model as example:
    a = pm.Uniform('alpha', lower=-63, upper=63, testval=0)
```
both yield `a.tag.test_value = array([0.0])`.

I suspect some sort of issue with the underlying datatype. This seems to be similar to https://github.com/pymc-devs/pymc3/issues/2366#issuecomment-312364619, mentioned by @aseyboldt.

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 0.9.0
* Python Version: 2.7.12
* Operating system: Linux
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
A partial solution for now is making sure you add `.` to each number: e.g., `b = pm.Uniform('alpha', lower=-64., upper=64.)`

**Comment by mmargenot** [comment]
Makes sense! I never checked whether the decimal would help. I initially found the issue when trying to do `a = pm.Uniform('alpha', lower=-100, upper=100)` and settled on using `a = pm.Uniform('alpha', lower=-128, upper=128)`.

**Comment by junpenglao** [comment]
type issue is one of our daily struggles. The other two is shape and GPU.
