### ISSUE TITLE
Bringing multivariate distributions into pymc namespace

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#270]
Currently, the multivariate distributions are not available in the main pymc namespace, unlike the univariate distributions, which seems a little arbitrary. Can we bring them in as well, eliminating the conflict with `Normal` by renaming to `MvNormal` or similar?

**Comment by jsalvatier** [comment]
Yes, I think that's alright. We could also shorten the `multivariate` namespace to 'mv' and that would serve a similar purpose. I will leave this one up to you.

**Comment by fonnesbeck** [comment]
Done in 455e40b. Please test.
