### ISSUE TITLE
sample() lacks track argument

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#271]
`sample` should have a `track` argument to specify which nodes should be tracked by the trace, as `psample` does. In my experience, it is the rule rather than the exception to track some deterministic nodes in a given model.

**Comment by fonnesbeck** [comment]
OK, nevermind. Remembered that we have `trace` instead of `track` with `sample`. Lets rename them to be consistent. Which do we prefer?

**Comment by jsalvatier** [comment]
Yeah, they should definitely be named the same. I think we should go with `trace`.

**Comment by fonnesbeck** [comment]
OK, I have done this in ccf73d0, which passes all tests on my machine. Keep in mind this means the `trace` argument can be polymorphic, accepting either a list of variables to track or a NpTrace (or MultiTrace) object to continue sampling with.
