### ISSUE TITLE
Smart resizing for traceplot

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#276]
Running `traceplot` with several traces can result in plots that look like this:

![unknown](https://f.cloud.github.com/assets/81476/537322/a76b0b74-c16d-11e2-9660-5f8eadd381f5.png)

Our plotting functions should be smarter about resizing themselves to match the dimensionality of the trace.

**Comment by twiecki** [comment]
I think a PR added a tight_layout() call for this.

**Comment by fonnesbeck** [comment]
You are correct.
