### ISSUE TITLE
Allow for arrays of multivariate stochastics

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#29]
Currently, the MvNormal object (as well as other multivariates) does not allow for vectors of multivariate normals; individual objects need to be created for each MVN variable.

**Comment by kforeman** [comment]
I would find this one useful, as I have a couple models that implement lists of MVNs to get around this

**Comment by fonnesbeck** [comment]
Perhaps the multivariate distributions would be good candidates to be the first moved to cython or numexpr, as they need to be overhauled to allow for vectors of multivariate parameters.

**Comment by twiecki** [comment]
Are there plans to move from Fortran to cython or numexpr? I think this is a great idea, but would add Theano to the list of possible replacements as this could also allow for GPU support without any additional work. I know that Anand and John have started work on this (much more fundamental however, could just start with rewriting the likelihoods in Theano instead).
