### ISSUE TITLE
vars argument fails in approx_hess

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#291]
Irrespective of which variables I pass to the `vars` argument in  `approx_hess`, a TypeError is generated:

```
TypeError: can't turn ([mu, theta, betas, sigma_b, b],) and {} into a dict. cannot convert dictionary update sequence element #0 to a sequence
```

Tried passing a list of variables and list of variable names, but neither works.

**Comment by jsalvatier** [comment]
What turned out to be the issue here? Anything we can do to get better error messages?

**Comment by fonnesbeck** [comment]
There was no issue.
