### ISSUE TITLE
pymc3: Gradient computation fails for Bound distributions (fix included)

### ISSUE THREAD

**Issue by kadeng** [pymc-devs/pymc3#298]
I experimented a bit with "Bound" distributions in PyMC3, and found that the following code raises an exception:

``` python
PositiveNormal = Bound(Normal, -0.2)  # Normal distribution with a lower bound at -0.2
val = T.dscalar('val')
dist = PositiveNormal.dist(mu=0.2, tau=1.)
logp = dist.logp(val)
dlogp = theano.tensor.grad(logp, val) # This one raises an exception
```

The problem is, that the bitwise "AND" operator used in the "alltrue" method does not have a gradient.

A simple fix seems to be to replace the "&" found in pymc.dist_math.alltrue() with a multiplication. In this case, the gradient calculation works, and the effect seems to be the same.

So the fixed version of "alltrue" looks like this:

``` python
def alltrue(vals):
    ret = 1
    for c in vals:
        ret = ret * (1 * c)
    return ret
```

**Comment by jsalvatier** [comment]
I think updating Theano will also fix this as newer versions should have a gradient for AND. If there aren't any issues with \* though, maybe we should use that.
