### ISSUE TITLE
Error with lambda expression

### ISSUE THREAD

**Issue by juliohm** [pymc-devs/pymc3#303]
The following code:

``` python
from pymc import *
x = Normal('x',0,1,0)
y = x**2
```

causes an error:

> /usr/local/lib/python2.7/dist-packages/pymc/CommonDeterministics.py:834: RuntimeWarning: divide by zero encountered in log
>  'b': lambda a, b: np.log(a) \* a *\* b}
> /usr/local/lib/python2.7/dist-packages/pymc/CommonDeterministics.py:834: RuntimeWarning: invalid value encountered in double_scalars
>  'b': lambda a, b: np.log(a) \* a *\* b}

**Comment by fonnesbeck** [comment]
I can't replicate this with the code you have posted. Are you sure there aren' t other objects at play? The error cites a call to `log`, but I see no logarithms in your code.

**Comment by juliohm** [comment]
Yes, I'm sure (copying/pasting the snippet directly into IPython).

I'm using the dev version.

**Comment by fonnesbeck** [comment]
Can you close IPython and open a new session, then type `whos` to confirm that there is nothing else in the namespace. Then paste the snippet and see if the same thing happens.

**Comment by juliohm** [comment]
Yes, I have been doing it. I started a new session in IPython, typed whos, then pasted the snippet. The error persists.

**Comment by fonnesbeck** [comment]
Also, is there any more to the error message than just those two lines? If so, please post.

**Comment by juliohm** [comment]
To eliminate other possibilities...

![pymc_bug](https://f.cloud.github.com/assets/3345261/731740/8c89cf54-e272-11e2-889e-8eed850a9317.png)

**Comment by fonnesbeck** [comment]
What version of numpy are you using?

**Comment by fonnesbeck** [comment]
Also, please see if this returns an error:

```
numpy.log(0.)
```

it ought to return `-inf`

**Comment by juliohm** [comment]
I'm using NumPy 1.6.2.

np.log(0.) returns -inf, but raises the same warning:

> -c:1: RuntimeWarning: divide by zero encountered in log
> Out[2]: -inf

**Comment by fonnesbeck** [comment]
That's probably the issue. Can you upgrade to 1.8? I will update the prerequisites.

**Comment by juliohm** [comment]
For the moment the issue is not stopping me to proceed, replacing x*_2 by x_x solves the warning.

BTW, I'm using NumPy from the Kubuntu 12.10 official repositories.
