### ISSUE TITLE
Array-valued variables and hdf5, with multiple chains

### ISSUE THREAD

**Issue by mpjdem** [pymc-devs/pymc3#304]
I had another multiple-chain issue with HDF5, that does not occur with for instance an sqlite backend. It occurs when concatenating the traces of an array-valued variable, manually or through stats(), csv_write(),... they get stacked along the wrong axis.

There is no problem with the HDF5 database itself; I believe the bug is found in the use of hstack() in both the Trace.**getitem**() and the Trace.gettrace() function.

``` python

import pymc as mc
import numpy as np

dat = np.random.rand(10)
mu = mc.Normal('mu', 0.5, 1e6, value=0.5)
mus = mc.Normal('mus', mu, 1., value=np.ones(10)*0.5)
obs = mc.Normal('obs', mus, 1., value=dat)

m = mc.MCMC([mu, mus, obs], db='hdf5', dbname='tmp.h5')

m.sample(100, progress_bar=False)
m.sample(100, progress_bar=False)

# No problem
print m.trace('mu', chain=0)[:].shape
print m.trace('mu', chain=1)[:].shape
print m.trace('mu', chain=None)[:].shape

# Problem
print m.trace('mus', chain=0)[:].shape
print m.trace('mus', chain=1)[:].shape
print m.trace('mus', chain=None)[:].shape

# Also with stats()
print m.stats()['mus']['mean'].shape

m.db.close()
```

**Comment by mpjdem** [comment]
d423036

**Comment by fonnesbeck** [comment]
Can you issue a pull request for this? I'm confused by where this commit resides.

**Comment by mpjdem** [comment]
Sure - I haven't used github before so I wasn't sure what the accepted procedure was for these things.

https://github.com/pymc-devs/pymc/pull/306
