### ISSUE TITLE
Chinese Restaurant Process

### ISSUE THREAD

**Issue by malmaud** [pymc-devs/pymc3#310]
I was wondering if there is support for the Chinese Restaurant Process so that I could write e.g. a Dirichlet process mixture model. It's not clear to me how to dynamically add and remove clusters to the model during inference in the pymc framework.

**Comment by fonnesbeck** [comment]
Though there is no formal DPP objects in PyMC, I give an example of a constructive stick-breaking DPP [here](http://stronginference.com/post/implementing-dirichlet-processes-for-bayesian-semi-parametric-models). The probabilities generated in the stick-breaking process are then used in a categorical stochastic to form a non-parametric random effect. Is this what you had in mind?

**Comment by malmaud** [comment]
Yes, except without artificial truncating.

**Comment by fonnesbeck** [comment]
Do you mean truncating the number of groups? I usually just select a number of breaks that is almost as large as the number of observations. If the estimates from a preliminary run seem to push against that bound, I just make it larger.

**Comment by malmaud** [comment]
How efficient will inference be with a large number of groups, though? Won't there be a lot of rejections if it's proposing changing all the stick weights at once?

**Comment by fonnesbeck** [comment]
I've never had a problem with constructive DPP used this way. I tend to get convergence pretty quickly. You can help things along by using adaptive Metropolis on the betas.
