### ISSUE TITLE
Strange behavior in pymc.NormApprox

### ISSUE THREAD

**Issue by devangel77b** [pymc-devs/pymc3#313]
I am trying to use pymc.NormApprox with a stochastic from pymc.MvNormal.  fit() runs OK but when I try to access mu and C afterwards, it gives KeyError (although I can look at the private _mu and _C just fine).  Also if I try to use pymc.MCMC it samples fine but then nukes the namespace afterwards.  

System: Ubuntu 12.04 with scipy, numpy etc all installed and working.  pymc installed via easy_install or also git + build; I have the same problem when I try on a MacBook Pro with pymc via Enthought so I don't think it's system specific.  The install gives warnings, but pymc tests pass (except not through nose and my nose is up to date - I have to run tests by copying the tests to Desktop and nosetest, pymc.test() fails to see them).

Minimal code to reproduce:
test.py::

```
#!/usr/bin/env python
import pymc
import numpy as np

x = pymc.MvNormal('x',mu=np.zeros(4),tau=np.eye(4))

@pymc.deterministic()
def y(x=x):
    result=np.zeros(2)
    result[0] = x[0]+x[2]
    result[1] = x[1]+x[3]
    return result

ymeas = pymc.MvNormal('ymeas',mu=y,tau=np.eye(2)*10000,
                      value=10*np.ones(2),observed=True)
```

Then in a shell running python or ipython:

```
import test
import pymc
foo = pymc.NormApprox(test)
foo.fit()

foo._mu # works 
foo._C # works
foo.mu[foo.x] # doesn't work
foo.C[foo.x] # doesn't work

foo = pymc.MCMC(test)
foo.sample(10000)
foo # doesn't work; namespace is nuked and Python doesn't know how to exit()
```

What I expect to see
foo.mu[foo.x] should give something like the posterior for x
Instead I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dennisevangelista/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pymc/NormalApproximation.py", line 56, in __getitem__
    tot_len += self.owner.stochastic_len[p]
KeyError: 5.2762630708260936
```

Also trying MCMC shouldn't nuke the namespace?
This could be an issue with MvNormal as Normal seems to work OK for 1D problems.

**Comment by devangel77b** [comment]
I am looking at the code for mu in NormalApproximation: I think these lines should be for p in xrange(len(stochastic_tuple)), similar to what appears in some other places in PyMC.  Alternatively it could be something like:: for p,index in enumerate(stochastic_tuple).  I will test it and let you know if it works. 

```
for p in stochastic_tuple:
    tot_len += self.owner.stochastic_len[p]

mu = zeros(tot_len, dtype=float)

start_index = 0
for p in stochastic_tuple:
    mu[start_index:(start_index + self.owner.stochastic_len[p])] = self.owner._mu[self.owner._slices[p]]
    start_index += self.owner.stochastic_len[p]
```

**Comment by devangel77b** [comment]
I found that changing NormApproxMu and NormApproxC in a few places seems to fix this issue. 

The code currently has 

```
for p in stochastic_tuple:
  # do stuff
```

After looking at the keys for self.owner.stochastic_len and self.owner._slices, I think the for statements in NormApproxMu and NormApproxC should be:

```
for p in stochastics:
    tot_len += self.owner.stochastic_len[p] 
    # builds up length of the mu slice asked for
```

and similarly for the line that returns the slice
and for the same bits in NormApproxC.  

This fixes my problem... but I don't know what was intended by having the try: stuff at the beginning of these methods and what stochastic_tuple is intended to do - stochastics is already a tuple of stochastic objects?

**Comment by fonnesbeck** [comment]
You cannot use a stochastic to index another stochastic, so `foo.mu[foo.x]` is not expected to work. 

I am able to sample the model above using an MCMC sampler:

```
In [1]: %paste
import pymc
import numpy as np

x = pymc.MvNormal('x',mu=np.zeros(4),tau=np.eye(4))

@pymc.deterministic()
def y(x=x):
    result=np.zeros(2)
    result[0] = x[0]+x[2]
    result[1] = x[1]+x[3]
    return result

ymeas = pymc.MvNormal('ymeas',mu=y,tau=np.eye(2)*10000,
                      value=10*np.ones(2),observed=True)

## -- End pasted text --

In [2]: foo = pymc.NormApprox(locals())

In [3]: foo.fit()

In [4]: bar = pymc.MCMC(locals())

In [5]: bar.sample(1000)
 [-----------------100%-----------------] 1000 of 1000 complete in 0.1 sec
```

**Comment by devangel77b** [comment]
Thanks for looking - I had tried to access it this way because the documentation on this at  
http://pymc-devs.github.io/pymc/modelfitting.html#normal-approximations
says to access the mu and C this way (which you say is the wrong way to access it): 

> > > N.mu[N.alpha]
> > > array([ 0.84658923])
> > > N.mu[N.alpha, N.beta]
> > > array([ 0.84658923,  7.74884998])
> > > N.C[N.alpha]
> > > matrix([[ 1.03854093]])
> > > N.C[N.alpha, N.beta]
> > > matrix([[  1.03854093,   3.54601911],
> > >         [  3.54601911,  23.74406919]])

Perhaps someone could update the doc to say what the right way is to access the posterior normal approximation mu and C for particular Stochastics?  It's very unclear.

**Comment by fonnesbeck** [comment]
Thanks for pointing that out. I will update the documentation.

**Comment by fonnesbeck** [comment]
Your suggested fix seemed to do the trick. Thanks!
