### ISSUE TITLE
PyMC3 is a package not module

### ISSUE THREAD

**Issue by Dmitrii-I** [pymc-devs/pymc3#3154]
Hi,

I am being overly pedantic here, not sure if this will be appreciated...

The docs at https://github.com/pymc-devs/pymc3/blob/master/docs/source/intro.rst say:

"PyMC3 is a probabilistic programming module for Python that allows users to fit Bayesian..."

but PyMC3 is not a single module rather a package. More correct would be:

"PyMC3 is a probabilistic programming Python package that allows users to fit Bayesian"

**Comment by fonnesbeck** [comment]
I've always used these terms interchangeably, but if you want to submit a pull request we would be happy to merge it.
