### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by tshauck** [pymc-devs/pymc3#324]
```
Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trenthauck/.virtualenvs/pydata3/lib/python3.3/site-packages/pymc/__init__.py", line 2, in <module>
    from distributions import *
ImportError: No module named 'distributions'
```

I find this very odd, because if I look at the code in the virtualenv there is a distributions module.  Not sure how to move forward.

**Comment by fonnesbeck** [comment]
Did you build this from the Github master source, or someplace else. Can you post (here or elsewhere) the entire terminal output from the installation?

**Comment by tshauck** [comment]
I used `pip install git+https://github.com/pymc-devs/pymc@pymc3` as described in the README.  I'll post the full install output soon.

**Comment by twiecki** [comment]
I think this is a python 3 problem where you have to do `from .distributions import *`. This probably means that we're not Python3 compatible currently.

**Comment by tshauck** [comment]
I was able to install and import on python 2.7.
