### ISSUE TITLE
Return samples after KeyboardInterrupt

### ISSUE THREAD

**Issue by aflaxman** [pymc-devs/pymc3#326]
It is very convenient to get the samples that have been computed so far after cancelling an MCMC sampler with KeyboardInterrupt (or Kernel->Interrupt in ipynb).  I would like to request this feature continue in PyMC3.

**Comment by jsalvatier** [comment]
Yup, that sounds like a must have.

**Comment by aflaxman** [comment]
Thanks, works great for me!

**Comment by twiecki** [comment]
Great! Next stop: live updating during sampling ;).
