### ISSUE TITLE
Shorter runs for `test_examples`

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#328]
In order to speed testing, it would be worth running the `test_examples` chains for fewer iterations (say 100). At present they are run via `imp` which simply calls the `__name__==__main__` block. I'm proposing having a `run` function in each example, which can be called with custom chain lengths.

**Comment by jsalvatier** [comment]
Yeah, that's probably a good idea.

**Comment by fonnesbeck** [comment]
`test_distributions` is one of the culprits. I wonder if we can strip down the sets of test values somewhat?

**Comment by jsalvatier** [comment]
Yes, that seems like a good way to do that.

**Comment by jsalvatier** [comment]
While this seems like a good idea, is there a reason this needs to be fixed before we do a beta release?

**Comment by twiecki** [comment]
+1

**Comment by fonnesbeck** [comment]
We might also consider either removing some examples that are redundant, or at least removing them from testing. Or, have multiple levels of testing, where one has to specify a flag for testing the entire suite of examples. I have _just_ the `test_examples` running now, and it has been going for more than an hour and a half.

It may also be worth removing any automatic plotting from the examples, as they can cause hangs depending on which backend is being used.

**Comment by jsalvatier** [comment]
Take a look at what I've done to the examples in https://github.com/pymc-devs/pymc/pull/417. I've made the examples all have a 'short' mode for testing. I've also split them up into several batches in test_examples. This seems to solve our problem for the most part.
