### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#330]
Just going over some examples like the stochastic volatiliy:
http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/pymc3/pymc/examples/stochastic_volatility.ipynb

A lot of the code used is now part of pymc3. 

I suspect this is the case for other examples too. Plus, I think we should use the new NUTS sampler throughout (except for maybe having a specific example just for HMC) as it makes the code simpler.

**Comment by jsalvatier** [comment]
This is mostly addressed, right? Can we close this?

**Comment by twiecki** [comment]
Yes.

**Comment by twiecki** [comment]
Fixed with https://github.com/pymc-devs/pymc/pull/351
