### ISSUE TITLE
HamiltonianMC() breaks when no scaling given

### ISSUE THREAD

**Issue by kforeman** [pymc-devs/pymc3#335]
If you call `HamiltonianMC()` without giving `scaling`, then it tries to call `guess_scaling()` in the global namespace and fails: `NameError: global name 'guess_scaling' is not defined`. 

It happens for both `import pymc` and `from pymc import *`.

Illustration: http://nbviewer.ipython.org/6490952

**Comment by twiecki** [comment]
Thanks for reporting.
