### ISSUE TITLE
PyMC 3: computations without Theano? 

### ISSUE THREAD

**Issue by spedemon** [pymc-devs/pymc3#338]
Hi John, 
Great work with PyMC 3; the integration with Theano seems very powerfull. 
I am considering to use PyMC 3 for an application in medical imaging which involves Hamiltonian MCMC sampling. In such application, though the data is quite large, the Hessian of the posterior is easy to compute numerically (the Hessian has a simple expression - in my case I have written some optimized GPU code that computes the Hessian and returns it is a Numpy array). 
In PyMC 3 the Hessian is obtained through manipulation of the analytical expression of the posterior and functional evaluation; I have not figured out how to integrate my 'manually' computed Hessian. 
Therefore I am also considering, in alternative, to fork PyMC 2 and add second order derivatives to enable Hamiltonian MCMC. 
Is the use of Theano currently a limitation in that sense, or am I missing something out? 
Thank you, keep up the good work. 
Stefano

**Comment by jsalvatier** [comment]
Hi Stefano

Currently, the Hessian is only used in setting up the samplers, not during actual sampling (but the gradient is used during sampling). You should be able to easily use the numerical hessian you have by passing it to the sampler you want to use. Take a look at https://github.com/pymc-devs/pymc/blob/pymc3/pymc/examples/gelman_bioassay.py for example, you would just replace h with your own hessian. 

If you also have a numerically computed gradient, the samplers are not set up to accept one, but it would be quite simple to add if you're interested.

There are some algorithms such as Riemann Manifold Hamiltonian Monte Carlo and its cousins that do use the hessian during sampling, but they are not currently implemented in pymc3. Though I would be very excited to accept such a contribution.

Does that answer your question?

**Comment by spedemon** [comment]
Hi John, 
Thank you for the clarification. 
I have just worked through the paper of Mark Girolami and Ben Calderhead 'Riemann manifold Langevin and Hamiltonian Monte Carlo methods' and it is indeed very exciting, even more so in combination with your Theano based framework. In fact Riemann manifold HCM requires also the 3rd derivatives of the log posterior, which could be computed via the automated differentiation feature (for small data :-) ). 
They also propose an approximation where the manifold is considered piece-wise constant. Such approximation boils down to using the Hessian as the mass matrix in the (Euclidean space) HMC. This has been proposed by many others and it's what I am interested in right now. The efficiency of the sampler increases dramatically and it seems to become more independent of parametrisation. I guess that is also quite straightforward to implement in PyMC3, given the automated differentiation. However, as you hinted, in my case the gradient (and the Hessian) is computed by an optimised external program. Therefore I would definitely be interested in modifying PyMC3 to accept a numerically computed gradient in the style of PyMC2. I would be happy to contribute, please get me started somehow. Last question is how are the gradient and Hessian treated differently in PyMC3? Shouldn't the sampler be able to obtain the gradient and/or the Hessian, either via Theano or calling a function? 
Stefano

**Comment by jsalvatier** [comment]
The easy thing to do is to modify the NUTS sampler (https://github.com/pymc-devs/pymc/blob/pymc3/pymc/step_methods/nuts.py) by adding a dlogp parameter that replaces `model.dlogpc(vars)` if its passed. 

I'm not sure this is the best possible solution, but it should get you started. 

To answer your last question, that is how pymc3 gets the gradient and hessian. They're not really treated differently except they're calculated by different functions (see https://github.com/pymc-devs/pymc/blob/pymc3/pymc/theanof.py)

Let me know if you have more questions.

**Comment by jsalvatier** [comment]
Oh and the function you pass in should take a dictionary of parameter values (as numpy arrays) and return a single 1-d numpy array.
