### ISSUE TITLE
Runtime failure: Node module not found

### ISSUE THREAD

**Issue by g5pw** [pymc-devs/pymc3#342]
I'm updating the pyMC port in Macports, the build ends fine, but when I try to import the pymc module, i get:

> % python3.3-c 'import pymc; pymc.test()'
> Traceback (most recent call last):
>  File "&lt;string&gt;", line 1, in <module>
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pymc/**init**.py", line 25, in <module>
>    from .Container import *
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pymc/Container.py", line 41, in <module>
>    from pymc.Container_values import LCValue, DCValue, ACValue, OCValue
>  File "Container_values.pyx", line 1, in init pymc.Container_values (pymc/Container_values.c:2592)
> ImportError: No module named 'Node'

If I run it under python2.7, I get:

> % python2.7 -c 'import pymc'
> Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/**init**.py", line 28, in <module>
>    from .CommonDeterministics import *
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 20, in <module>
>    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/utils.py", line 11, in <module>
>    from . import flib
> ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/flib.so, 2): Symbol not found: _bern_grad_p_
>  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/flib.so
>  Expected in: flat namespace
> in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/flib.so

Anyone have similar issues?

**Comment by fonnesbeck** [comment]
You are having Fortran compiler issues. Do you have gFortran installed? Also, which version of PyMC are you trying to install?

**Comment by g5pw** [comment]
Aha, I suspected fortran... I use gfortran 4.8 and pyMC v2.2. I can supply a buildlog if you want.

**Comment by fonnesbeck** [comment]
I would recommend building PyMC from the current master branch here on GitHub. Also, be sure that your gFortran corresponds to the Xcode version you are using.

**Comment by g5pw** [comment]
At macports we prefer to offer users stable software: is the master branch stable code? Also, I don't use the gFortran or gcc that comes from Xcode, but Macports gcc 4.8.

**Comment by fonnesbeck** [comment]
I will be releasing PyMC 2.3 very soon (a week or so?), so if you can get it working with the master branch I can send you a notification when the release is done, and you can update it.

As far as gFortran/gcc goes, that is fine as long as the two are compatible. Most of the Fortran errors we see are related to such incompatibilities.

**Comment by fonnesbeck** [comment]
If you have ongoing problems, please do post the build log to a Gist and link to it here.

**Comment by g5pw** [comment]
Aha, great! Feel free to close the issue when you release 2.3, so I'll get notified and update the port. Thanks!

**Comment by g5pw** [comment]
Ok, I admit I got curious and tried with the current master branch. Now it fails with the same error as python2.7 before: can't find the _bern_grad_p_ function. If I examine flib.o with nm, I see a symbol named _bern_grad_p__ (with two underscores), but not the one asked. Furtran compiler configuration (from the build log):

> Fortran f77 compiler: /opt/local/bin/gfortran-mp-4.8 -static -ff2c -m64 -O3 -funroll-loops
> Fortran f90 compiler: /opt/local/bin/gfortran-mp-4.8 -m64 -m64 -O3 -funroll-loops
> Fortran fix compiler: /opt/local/bin/gfortran-mp-4.8 -Wall -ffixed-form -fno-second-underscore -m64 -m64 -O3 -funroll-loops
> creating build/temp.macosx-10.8-x86_64-3.3/pymc
> compile options: '-DNO_ATLAS_INFO=3 -Ibuild/src.macosx-10.8-x86_64-3.3 -I/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/core/include -I/opt/local/Librar
> y/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c'

**Comment by fonnesbeck** [comment]
Can you try a different Fortran compiler? I cannot replicate this here (gFortran 4.2.1) and I have not had this reported by others.

**Comment by g5pw** [comment]
@fonnesbeck Ok, I got it. Apparently, I overwrote the default FFLAGS ('-Wall -ffixed-form -fno-second-underscore') with the ones specified in ./buildosx (-static -ff2c), and this prevented correct compilation of the flib module. The culprit is, of course, -fno-second-underscore.
