### ISSUE TITLE
PYMC 3 - Matrix operations with Wishart prior distribution

### ISSUE THREAD

**Issue by jangevaare** [pymc-devs/pymc3#343]
Hi, recent commits now allow a model specification to include the Wishart distribution.

In my model I am required to do various matrix operations (e.g. Kronecker product, inversion, transpose, matrix multiplication and addition) with Wishart prior distributions in the specification of the covariance matrix for a rather large MvNormal.

I have been unable to perform these operations though. I initially thought this was all possible through numpy, since I recall seeing examples of individuals using numpy functions for non-matrix pymc objects. I have also explored using theano for my matrix operations with similar result.

I am not sure if I am reporting a bug here or if I am making a feature request. But here is the kind of thing I am trying to do. Thank you for taking a look!

```
# Initial
python
from matplotlib.pylab import *
from pymc import *

# Data
cov=matrix([[2,1],[1,3]])
mean=([2,7])
tau=np.linalg.inv(cov)
N=1
z_data=np.ndarray.flatten(np.random.multivariate_normal(mean, cov, N))

# Create a test function...
def dbl_inv(X):
    return np.linalg.inv(np.linalg.inv(X))

# Build the model
with Model() as model:
    wishart_test=Wishart('wishart_test', n=3, p=2, V=np.eye(2), shape=(2,2))
    z=MvNormal('z', mu=mean, Tau=dbl_inv(wishart_test), shape=2, observed=z_data)
```

Which results in...

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "<stdin>", line 2, in dbl_inv
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 509, in inv
    _assertRankAtLeast2(a)
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 202, in _assertRankAtLeast2
    'at least two-dimensional' % len(a.shape))
numpy.linalg.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
```

**Comment by jsalvatier** [comment]
You get the same error with if you use the theano linear algebra functions (
http://deeplearning.net/software/theano/library/sandbox/linalg.html)? I am
not surprised that it doesn't work with numpy, because numpy does not work
on theano tensors.

**Comment by jangevaare** [comment]
Ah. Sorry I was being inexact. Here's what happens when I use Theano's linear algebra functions:

```
python
from matplotlib.pylab import *
from pymc import *

cov=np.array([[2,1],[1,3]])
mean=([2,7])
tau=np.linalg.inv(cov)
N=1
z_data=np.ndarray.flatten(np.random.multivariate_normal(mean, cov, N))

def dbl_inv(X):
    return theano.sandbox.linalg.ops.MatrixInverse(theano.sandbox.linalg.ops.MatrixInverse(X))

with Model() as model:
    wishart_test=Wishart('wishart_test', n=3, p=2, V=np.eye(2), shape=(2,2))
    z=MvNormal('z', mu=mean, Tau=dbl_inv(wishart_test), shape=2, observed=z_data)
```

Which results in...

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "<stdin>", line 2, in dbl_inv
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by jsalvatier** [comment]
It looks like MatrixInverse is not an actual operator, but a module, and
that matrix_inverse is the actual operator you want.

That's kind of annoying. Would you mind filing a ticket with Theano
https://github.com/Theano/Theano/issues?state=open about this error?

John

**Comment by jangevaare** [comment]
Well that's simple. Thank you. 

I don't understand what error I would be reporting for Theano. Re-reading the documentation it makes sense that matrix_inverse is the actual operation. Just to say that their sandbox.linalg documentation should be made a little more clear?

For completeness sake, this model specification indeed works:

```
python
from matplotlib.pylab import *
from pymc import *

cov=np.array([[2,1],[1,3]])
mean=([2,7])
tau=np.linalg.inv(cov)
N=1
z_data=np.ndarray.flatten(np.random.multivariate_normal(mean, cov, N))

def dbl_inv(X):
    return theano.sandbox.linalg.ops.matrix_inverse(theano.sandbox.linalg.ops.matrix_inverse(X))

with Model() as model:
    wishart_test=Wishart('wishart_test', n=3, p=2, V=np.eye(2), shape=(2,2))
    z=MvNormal('z', mu=mean, Tau=dbl_inv(wishart_test), shape=2, observed=z_data)
```

**Comment by jsalvatier** [comment]
Yes, I meant clearer documentation.

It took me a couple minutes to figure out, and I know Theano pretty well.

**Comment by jsalvatier** [comment]
Glad that cleared things up!

**Comment by twiecki** [comment]
Good to close?
