### ISSUE TITLE
Test errors: test_LazyFunction, test_cov

### ISSUE THREAD

**Issue by cdeil** [pymc-devs/pymc3#345]
On Mac OS X 10.8 with Macports and Python 2.7 and pymc dev d6be456a18b25f7af06b8845835028e1b862b03f I get a test error, a fail and a bunch of deprecation warnings:
https://gist.github.com/cdeil/6628062

Just thought I mention it in case you can fix it for the upcoming 2.3 release.

**Comment by cdeil** [comment]
The same errors and another one happen on travis-ci:
https://travis-ci.org/cdeil/pymc/builds/11565116

The astropy guys have set up a very nice extended test matrix for travis-ci:
https://github.com/astropy/astropy/blob/master/.travis.yml

Should I give it a try and adapt it for PyMC?

**Comment by fonnesbeck** [comment]
The inverse wishart bug is known, and is perplexing since it crops up when I run the whole test suite, but not when I run the test individually. I will get to the bottom of it before I tag a release.  The NormApprox bug will be fixed in the next commit. 

As for the test matrix  we always welcome helpful contributions!

**Comment by cdeil** [comment]
I now see this test error:

```
ERROR: test_cached (pymc.tests.test_LazyFunction.test_LazyFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pymc/tests/test_LazyFunction.py", line 69, in test_cached
    cur_frame] == A.counter.get_count())
IndexError: index 1 is out of bounds for axis 0 with size 1
```

Full test log: https://gist.github.com/cdeil/6647287
I updated to Xcode 5 ... possibly that is the reason for the new error.

**Comment by cdeil** [comment]
There's also this error on Python 3 on travis-ci ([log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/11621441/log.txt)):

```
ERROR: test (pymc.tests.test_cov.test_cov)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/cdeil/pymc/pymc/tests/test_cov.py", line 21, in test
    assert(C(x, x).shape == (len(x), len(x)))
  File "/home/travis/build/cdeil/pymc/pymc/gp/Covariance.py", line 525, in __call__
    C = self.eval_fun(x,x,symm=True,**self.params)
  File "/home/travis/build/cdeil/pymc/pymc/gp/cov_funs/cov_utils.py", line 174, in __call__
    thread_args = [(C,x,y,bounds[i],bounds[i+1],symm) for i in xrange(n_threads)]
TypeError: 'float' object cannot be interpreted as an integer
```

Let me know if you prefer one issue per test error.

**Comment by cdeil** [comment]
I do see 8 errors and 22 failures with Python 3.3 on Mac:
https://gist.github.com/cdeil/6647601
I didn't have a look if these are real PyMC issues or problems with my installation.

**Comment by fonnesbeck** [comment]
Are you using the current master? `test_LazyFunction` should not be present.

**Comment by fonnesbeck** [comment]
The HDF5 errors are due to your HDF5 being misconfigured. It can be a bear to get working, and we certainly will not be supporting this backend in PyMC 3.

I have not seen the others before, but I use Python 2.7 exclusively.

**Comment by fonnesbeck** [comment]
I have submitted an [issue to the numpy project](https://github.com/numpy/numpy/issues/3771) on the inverse Wishart failure problem, which does not appear to be a problem with our code.

**Comment by pv** [comment]
Try to add `import pdb; pdb.set_trace()` in your test and inspect what exactly goes wrong.
In my experience, it seems quite unlikely to that this sort of issues are due to Numpy issue --- every time we had something like this in Scipy, it turned out to be a bug in Scipy: memory corruption, leaking floating point flags due to mismatching function prototypes, global state affected by the order in which tests are run, etc.

**Comment by fonnesbeck** [comment]
This did not work. I have also tried setting seeds within individual test classes, but this does not work consistently either. It is definitely a stochastic problem, as the outcome changes from one run of the test suite to the next. I'm going to have one more go at this, and then I will simply remove the inverse wishart from PyMC altogether. I can't afford to spend all this effort on a distribution that (almost) nobody uses.

**Comment by pv** [comment]
Nose has several ways to specify setup routines that are run before each test. Setting the seed should make it deterministic, unless, your Fortran code has some internal random generator with internal random state that you cannot set.

**Comment by fonnesbeck** [comment]
Thanks, I will check this out. There is no random number generation associated with the Fortran code, as it is only calculating likelihoods. All the RNG is done on the Python side.

**Comment by fonnesbeck** [comment]
I have removed the inverse wishart in e5d758e, as I cannot get this error to go away. I know the code is fine, as the error is not triggered reliably. Nevertheless, the inverse wishart is not important enough to block a release. 

Unfortunately, there is now a failure in `test_beta` despite no changes being implemented in this code. It seems to have come up after upgrading to the latest Numpy master, so I'm thinking it has something to do with their beta RNG.

**Comment by fonnesbeck** [comment]
The Travis-CI tests now pass reliably for me on the current master branch. Let me know in the next few days if this does not hold true.
