### ISSUE TITLE
Don't generate documentation outside pymc folder?

### ISSUE THREAD

**Issue by cdeil** [pymc-devs/pymc3#348]
I was very surprised to see that generating the pymc html docs locally creates a `pymc-page` folder outside the pymc folder:

```
$ cd docs
$ make html
sphinx-build -b html -d _build/doctrees   . ~/Code/pymc-pages
...
Build finished. The HTML pages are in ~/Code/pymc-pages.
```

All other Python packages generate the docs inside the repo folder and this seems easier / safer. Change to generate html docs in `docs/_build/html`?

**Comment by fonnesbeck** [comment]
Yes, this was just a convenience for separating the gh-pages from the master branch. I can change it back to the default.
