### ISSUE TITLE
Cannot change StepMethod after sampling

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#35]
If a model has been initialized and sampled from, it is apparently not possible to change the StepMethod for any of its stochastics. use_step_method() works fine before sampling has occurred, but if a subsequent chain is sampled after changing the StepMethod, it uses the original StepMethod that it was initialized with. 

This post describes an example: http://groups.google.com/group/pymc/browse_thread/thread/2e7a7e3be91bc90f

**Comment by apatil** [comment]
Answered on the mailing list. use_step_method only adds step methods, at the end of the example code the variable x was being updated with five step methods. We don't have a remove_step_method method, and I don't really think we need one.
