### ISSUE TITLE
Where are (e.g.) pymc.Normal and pymc.Uniform defined?

### ISSUE THREAD

**Issue by jmandel** [pymc-devs/pymc3#352]
It would be helpful if the docs answered this question and documented the parameters that get passed to `Normal` and `Uniform`.  (If it's documented, I can't find it -- would appreciate a link!)

**Comment by fonnesbeck** [comment]
All of PyMC's log-likelihood distribution functions are [here](http://pymc-devs.github.io/pymc/distributions.html). The corresponding objects have the same arguments, except that they are preceded by a name.

Also, when in doubt, if you type a question mark after the object in IPython, it will give you the docstring:

```
In [2]: pymc.Normal?

Type:       StochasticMeta
String Form:<class 'pymc.distributions.Normal'>
File:       /Users/fonnescj/Code/pymc/pymc/distributions.py
Definition: pymc.Normal(self, *args, **kwargs)
Docstring:
N = Normal(name, mu, tau, value=None, observed=False, size=1, trace=True, rseed=True, doc=None, verbose=-1, debug=False)

Stochastic variable with Normal distribution.
Parents are: mu, tau.

Docstring of log-probability function:
```

etc.

**Comment by jmandel** [comment]
Thanks! Would probably help new developers to provide explicit functions in the pydocs, ratherthan just sdocumentingtthe log likelihood functions. Especially since arguments are at least a bit different...

**Comment by fonnesbeck** [comment]
You can look for this in PyMC 3, where we are no longer building stochastic objects from Fortran log-likelihoods. We are going to be diving into the docs very soon.

For now, in PyMC 2 the log-likelihoods are [automatically wrapped in `Stochastic` objects by PyMC](http://pymc-devs.github.io/pymc/modelbuilding.html#creation-of-stochastic-variables), so the parameterization follows a reliable pattern.
