### ISSUE TITLE
Implement slicing in MultiTrace

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#354]
Using slicing to cut out burn-in intervals from MultiTrace objects do not work, since `get_item` is currently specified to return variables indexed by name. We probably want MutliTrace to work similarly to Trace, but in either case, we need to be able to truncate the trace easily.

**Comment by fonnesbeck** [comment]
I've fixed this in the [multitrace](https://github.com/pymc-devs/pymc/tree/multitrace) branch, however the test that I added for this segfaults when type checking the MultiTrace. No idea why.

**Comment by fonnesbeck** [comment]
OK, it seems to pass Travis-CI, so there must be some Theano cruft on my machine.

**Comment by twiecki** [comment]
Pulled in via https://github.com/pymc-devs/pymc/pull/355
