### ISSUE TITLE
Pymc on Mac Mountain lion

### ISSUE THREAD

**Issue by abu77** [pymc-devs/pymc3#356]
Dear all, I've just upgraded to Mountain Lion... quite a pain in the a*\* to re-configure everything
I've installed Superpack, went quite smooth
but when I try to use pymc it says that no module is there
I tried than with pip install and this is the error
 i got

Command /usr/local/opt/python/bin/python2.7 -c "import setuptools;**file**='/private/var/folders/02/5m0nn2nn2_n4_m31rps09v8m0000gn/T/pip_build_abu/pymc/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/02/5m0nn2nn2_n4_m31rps09v8m0000gn/T/pip-POb3xc-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/02/5m0nn2nn2_n4_m31rps09v8m0000gn/T/pip_build_abu/pymc

what does it means? and how can i fix it?
Thanks a lot

**Comment by fonnesbeck** [comment]
It appears that the PyMC build did not make it into the SuperPack on this update. I've added it now. Try running the script again.

**Comment by abu77** [comment]
It looks like it's working
Thank you very much
