### ISSUE TITLE
Logarithm of a specific distribution

### ISSUE THREAD

**Issue by naji-s** [pymc-devs/pymc3#361]
I don't know if this is the write place to ask questions but I would like to have the logarithm of specific distribution as the distribution for my variable however I am unable to define such a thing in the model. I couldn't find anything relative in the documentation and nothing came up by googling.

I would be happy to get some help.

Thanks.

**Comment by fonnesbeck** [comment]
Not sure if you found the answer to your question, but the PyMC 2 user's guide has information on how to specify custom stochastics. 

The best place to get guidance for using PyMC (other than the user's guide, of course), is posting to [StackOverflow](http://stackoverflow.com/questions/tagged/pymc) using the "pymc" tag.

**Comment by naji-s** [comment]
Oh. I made it myself but thanks a lot for your quick reply and your answer
