### ISSUE TITLE
"FloatingPointError" for small values in Dirichlet distribution! 

### ISSUE THREAD

**Issue by naji-s** [pymc-devs/pymc3#363]
So I have a hierarchical bayesian model that I have implemented using PyMC. The model can be find here: https://www.dropbox.com/s/ij1tlqsgvjmcl1w/Paper.pdf

My model is in a file named HBM.py and the sampling scheme that I use is MCMC Metropolis by a Guassian distribution as proposal.

This is my code for the model:

```
"""
A Hierarchical Bayesian Model for Bags of Marbles

logalpha ~ logarithm of an exponential distribution with parameter lambd
beta ~ Dirichlet([black and white ball proportions]:vector of 1's)
theta ~ Dirichlet(alpha*beta(vector))

"""

import numpy as np
import pymc
from scipy.stats import expon
lambd=1.
__all__=['alpha','beta','theta','logalpha']
#------------------------------------------------------------
# Set up pyMC model: logExponential
#1 parameter: (alpha)

def logExp_like(x,explambda):
    """log-likelihood for logExponential"""
    return -lambd*np.exp(x)+x
def rlogexp(explambda, size=None):
    """random variable from logExponential"""
    sample=np.random.exponential(explambda,size)
    logSample=np.log(sample)
    return logSample
logExponential=pymc.stochastic_from_dist('logExponential',logp=logExp_like,
                                          random=rlogexp,
                                          dtype=np.float,
                                          mv=False)
#------------------------------------------------------------
#Defining model parameteres alpha and beta.
beta=pymc.Dirichlet('beta',theta=[1,1])
logalpha=logExponential('logalpha',lambd)

@pymc.deterministic(plot=False)
def multipar(a=logalpha,b=beta):
    out=np.empty(2)
    out[0]=(np.exp(a)*b)
    out[1]=(np.exp(a)*(1-b))
    return out
theta=pymc.Dirichlet('theta',theta=multipar)
```

And here is my code for test.py(sampling):

```
from pymc import Metropolis
from pymc import MCMC
from matplotlib import pyplot as plt
import HBM
import numpy as np
import pymc
import scipy
M=MCMC(HBM)
M.use_step_method(Metropolis,HBM.logalpha, proposal_sd=1.,proposal_distribution='Normal')
M.sample(iter=1000,burn=200)
```

After running the code I am getting "FloatingPointError" some of the times from line 978 of the distribution.py. I think there is a problem with implementation because when I run the code, sometimes I do get the distributions and when it happens the  histograms are pretty much like the ones in the paper.
![model description](https://f.cloud.github.com/assets/5704179/1355464/f62a7014-3766-11e3-8cd1-23296faa49d1.png)

**Comment by fonnesbeck** [comment]
One issue with this model is that it does not have a likelihood (`@observed`) node. The paper indicates there should be a Multinomial sampling distribution, but I do not see it in the model.

**Comment by naji-s** [comment]
Well my model is running on the no data case and that shouldn't be a problem I believe. The full paper can be accessed here:
https://www.dropbox.com/s/fmuzvhikdqoep2j/devsci07_kempetal.pdf

When I manually change the output of dirichlet distribution when gamma[0] is zero(line 978 in distributions.py) to return 1 for example, then my histograms look exactly like what they should look in the no data case.

**Comment by fonnesbeck** [comment]
I don't get any errors on the code that you posted. Are you using a recent version of PyMC? Also, which version of Numpy are you using?

**Comment by naji-s** [comment]
I think you have to increase the size of sample. Sometimes it can happen that it won't get into areas with problem! For  example 50000.

**Comment by naji-s** [comment]
I actually finally installed your ScipySuperPack as I am on Mac. Oh and thanks a lot for such great efforts. For both of them!

**Comment by fonnesbeck** [comment]
Getting back to this, I just ran it for 1M iterations without error. Can you make sure you are running the 2.3 release version?
