### ISSUE TITLE
pymc 2.3 last updated today does not have a setup.py file

### ISSUE THREAD

**Issue by setjmp** [pymc-devs/pymc3#366]
I was trying to download and install pymc 2.3 today, but found that the 2.3 tarball lacks a setup.py file:

```
aschein@localhost:pymc-2.3[1]$ ls
blas    lapack   MANIFEST.in  pymc           README.rst  setupegg.py
cephes  LICENSE  PKG-INFO     pymc.egg-info  setup.cfg
aschein@localhost:pymc-2.3$ 
'''

Here is the site I downloaded the package from:  https://pypi.python.org/pypi/pymc
```

**Comment by guyrt** [comment]
+1 (commenting to track)

**Comment by r-owen** [comment]
Same here. It is possible to download it from https://github.com/pymc-devs/pymc/tags and the version there is much larger than the version at PyPI (13Mb instead of <1Mb).

**Comment by fonnesbeck** [comment]
Sorry, folks. This should be fixed now.

cf

**Comment by guyrt** [comment]
confirmed. You can close this issue.
