### ISSUE TITLE
Standardize pymc import

### ISSUE THREAD

**Issue by zonca** [pymc-devs/pymc3#367]
I think it would be useful to standardize how `pymc` should be imported. Currently most of the examples and also the `pymc3` tutorial use:

``` python
from pymc import *
```

Of course this should be discouraged, and it would be useful to choose a standard shortcut import.
I suggest using:

``` python
import pymc as mc
```

It is used by [Bayesian Methods for Hackers](http://nbviewer.ipython.org/urls/raw.github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/master/Chapter2_MorePyMC/MorePyMC.ipynb) which I guess is one of the most common ways new users start using `pymc`.

If there is agreement on this, it would be useful to prepare a PR with standardization of the examples and tutorial (I can do this if nobody else volunteers).

**Comment by twiecki** [comment]
`pymc` 2 uses `import pymc as pm` and so does most other pymc code I know. So if Bayesian Methods changed the imports it should all be in agreement.

**Comment by zonca** [comment]
Ok
Sorry didn't know about that.
So do you think would be useful to modify tutorial and example to that standard?

**Comment by twiecki** [comment]
I think it would be useful to change the Bayesian Methods for Hackers book to adhere to the standard :).

**Comment by zonca** [comment]
Sure, I'll ask to the author, but for pymc3 there is no standard if you are
not using it in the examples...
So if I prepare a PR on putting import pymc as pm in examples would you
merge it?

**Comment by twiecki** [comment]
@zonca Oh I see what you mean. 

I think I'm in favor of this. What do you think @jsalvatier and @fonnesbeck ?

**Comment by fonnesbeck** [comment]
Definitely, yes. Thanks for offering.

**Comment by jsalvatier** [comment]
Yes, sounds like a great idea.

**Comment by zonca** [comment]
ok, good we agreed on this, I'll prepare a PR.
However, let me advocate a little bit about my proposal:

``` python
import pymc as mc
```

wouldn't you consider changing the default import from `pymc2`  to `pymc3`?
afterall the API changed a lot anyways, so it wouldn't be too bad to also change the default import name.

`mc` as Monte Carlo is a lot more descriptive of what the package does than `pm`.
`mc.sample`, `mc.Model`, `mc.Normal` I think look a lot better than `pm.sample`, `pm.Model`, `pm.Normal`.

I would like also to ask also @CamDavidsonPilon's opinion on this.

**Comment by CamDavidsonPilon** [comment]
I cannot recall why I chose `mc` as the alias for pymc. If the community wants to standardize, I fine with changing to `pm`. It will stop me from writing the ugly pattern:

`mcmc = mc.MCMC(...)`

**Comment by twiecki** [comment]
@zonca I see your argument but disagree. I don't think the standard should change in this way because of a new major version. If anything, we might want to rename `pymc` to `pymc3` and then do `import pymc3 as pm3` which would be more consistent. Note that I'm not advocating we actually do this.

I also think we should be compatible with other packages, `numpy` is `np`, `scipy` is `sp`, `statsmodels` is `sm` etc.

**Comment by zonca** [comment]
Ok, thanks @CamDavidsonPilon @twiecki!

It looks like there is an agreement on using `pm`, so I am going to prepare a PR for `pymc` and @CamDavidsonPilon will modify Bayesian Methods for Hackers.

**Comment by twiecki** [comment]
@zonca Thanks for helping with this!
