### ISSUE TITLE
Traceplot does not plot parallel chains of multivariate variables properly 

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#373]
After sampling multiple chains via `psample`, the `traceplot` function appears to concatenate the traces of multivariate nodes, rather than plotting them independently. For example, here is output from a variable of size 3 that was sampled for 10K iterations:

![unknown-1](https://f.cloud.github.com/assets/81476/1432832/a3f25a5e-40e5-11e3-9203-6cb2c47397af.png)

Clearly, the chains have been concatenated.

**Comment by twiecki** [comment]
Fixed with #392.
