### ISSUE TITLE
PyMC sets theano.config.compute_test_value to 'raise'

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#376]
As the title suggests, we currently configure this in `pymc.model`, which has consequences for using Theano alongside PyMC for other work. Some of the examples in the Theano tutorial, for example, will not run as expected under this setting. 

Can this be eliminated, and if not, is there perhaps a way of setting and unsetting it on the fly as it is needed or not? Or, can we print a warning in lieu of this, as I think it will cause some problems that are hard to diagnose.

**Comment by jsalvatier** [comment]
The reason for this is to raise errors about computations producing bogus results as early as possible, to make debugging easier. We could set/unset it inside the model `with` context perhaps.

**Comment by twiecki** [comment]
Closing in favor of https://github.com/pymc-devs/pymc/issues/566.
