### ISSUE TITLE
Building a model that requires external function in pymc3?

### ISSUE THREAD

**Issue by bhayden53** [pymc-devs/pymc3#377]
Hello,

I have been anxiously awaiting HMC functionality in pymc3; thanks for all the work everyone has put in.

I am attempting to make a model in pymc3 which requires one of the free parameters of my model to be operated on by an external python package. For instance, one of my 'free' parameters is an unknown parameter of the cosmology of the universe, and a set of integrals needs to be performed on this parameter in order to estimate an observable quantity.

Perhaps I just don't understand what's going on in pymc3, but I can't figure out how to do this since pm.Uniform returns a Theano TensorVariable. The basic structure of what I'm trying to do looks like:

```
import pymc as pm
import cosmology_calculator

data = some_data_from_somewhere
with pm.Model() as model:
    cosmo_param = pm.Uniform( 'cosmo_param', lower=0.0, upper=1.0 )
    cosmo_observable = cosmology_calculator( cosmo_param ) 
```

The cosmology_calculator step immediately wants the input to be a float, which crashes because it's a Tensor. 

Is there any way to construct a model in pymc3 that can do this?

**Comment by twiecki** [comment]
Yeah, this is something we have to fix.

Unfortunately if your likelihood is a blackbox function there is no way to compute the gradient and you can't run HMC.

**Comment by jsalvatier** [comment]
You can build a [Theano Op](http://deeplearning.net/software/theano/tutorial/extending_theano.html) which does the computation. 

This is not too hard, but it's not trivial either. See [here](https://github.com/pymc-devs/pymc/blob/master/pymc/distributions/special.py#L14) for some examples. 

One goal of ours will be to make this pretty trivial for simple cases.

**Comment by twiecki** [comment]
Closing this in favor of https://github.com/pymc-devs/pymc/issues/507.

**Comment by docyyz** [comment]
I'm interested to know this answer to this post as well, but the links posted above don't exist anymore.

**Comment by twiecki** [comment]
@docyyz You can see here: http://docs.pymc.io/notebooks/getting_started.html#Arbitrary-deterministics or ask questions here: https://discourse.pymc.io/
