### ISSUE TITLE
How to combine binomial?

### ISSUE THREAD

**Issue by abu77** [pymc-devs/pymc3#378]
Hi there, I would like to fit some data to a chain of binomial, that is: i have some susceptible individuals and the number of infected individuals; the infected ones are result of a disease that take 7 stages to develop; the transition rate of the stages is the same How can i combine the 7 binomial distibution in pymc?
Bests

**Comment by fonnesbeck** [comment]
The best place to post questions regarding how to use PyMC is the [StackOverflow page with a pymc tag](http://stackoverflow.com/questions/tagged/pymc). However, I do have a [disease dynamics example](https://github.com/pymc-devs/pymc/wiki/Sir) on our Wiki if you want to have a look at that.
