### ISSUE TITLE
Is Gelman-Rubin diagnostic working correctly in PyMC3?

### ISSUE THREAD

**Issue by aflaxman** [pymc-devs/pymc3#383]
I've been exploring the Gelman-Rubin convergence diagnostic statistic, and I'm not sure if it is working.  I have read online that a R_hat of under 1.1 or 1.2 indicates that the chain has mixed, but I have a simple example with R_hat of 1.03 where the mean is off by 19%.

![image](https://f.cloud.github.com/assets/51236/1516557/3f37ccee-4b16-11e3-9706-3921a44246b0.png)

I think I might be misinterpreting the test, or have done something wrong with my example, which I've put in [a gist here](http://nbviewer.ipython.org/7420408).  If I've done the test correctly and setup the model correctly, I'm still not sure whether this is a problem with the GR diagnostic in theory or with the PyMC3 implementation.

No matter what, this is great stuff you've been developing, and I hope my issue creation can be helpful to its progress, and not just a pain in your neck.

**Comment by twiecki** [comment]
Well Rhat just tells if you the chains can't be differentiated. I suppose you used `theta=1` to simulate the data? In that case convergence is fine but you didn't recover the parameter which can have several issues. Most likely, `theta` of that specific data set might be `1.19` so maybe try simulating more data? I might be misunderstanding your point though.

**Comment by fonnesbeck** [comment]
Yes, Rhat only compares within- and between-chain variance, and is (like all practical convergence diagnostics) only a heuristic. I have not noticed problems with it, based on informal use, and you can usually get an idea using the `forestplot` function. We should have a unit test, though.

What worries me is that `traceplot` only plotted one series. That's a bug.

**Comment by aflaxman** [comment]
@twiecki I've set it up so that the true mean of `theta` is 1.0

@fonnesbeck These forestplots are cool, here is one for theta when it did not mix:
![image](https://f.cloud.github.com/assets/51236/1526355/4c85761c-4be3-11e3-8435-097f8f5ab05c.png)

And here is one where it did:
![image](https://f.cloud.github.com/assets/51236/1526366/70b20ec4-4be3-11e3-9148-8b6a82a4620c.png)

It might be worthwhile to have an automatic test confirm that PyMC `gelman_rubin` gets the same results as the R function.  When I was reading about it, I got the impression there is some subtlety to this. Is that the unit test you were thinking of?

Regarding the `traceplot` results, have a look in the notebook http://nbviewer.ipython.org/7420408, because what I pasted above only has half of the output.  The trace shows all chains appended sequentially, and stacks two copies of the same thing.

**Comment by twiecki** [comment]
Having a unittest that compares Rhat to the R implementation (via rpy2) is a good idea. Where did the Rhat implementation come from? Can't we just take the one from pymc2?

@aflaxman Your point in the first plot is that Rhat = 1 but the chains haven't converged I guess. Although it's not clear what the value Rhat really is in that plot.

**Comment by aflaxman** [comment]
It looks like @fonnesbeck is to "blame" for adding this: https://github.com/pymc-devs/pymc/blame/master/pymc/diagnostics.py#L90 so he can speak to how it relates to the PyMC2 version.

It seems like the reference implementation is here: http://www.stat.columbia.edu/~gelman/itsim/itsim.sfun

I could not get rpy2 working in the time I had for this last week, but I'll try again in the future.

**Comment by fonnesbeck** [comment]
It was adapted from PyMC 2. I'm sure I just added a bug somewhere along the line. I think the best way to test it is against a series with known B and W values, rather than against another implementation. I can do that.

**Comment by fonnesbeck** [comment]
I've had a closer look at this, and I'm confident that the Gelman-Rubin diagnostic is being calculated as it should. Its a very simple calculation (in fact, debugging this allowed me to simplify the code even further). Here is the function:

```
def calc_rhat(x):

    m, n = x.shape

    # Calculate between-chain variance
    B = n * np.var(np.mean(x, axis=1), ddof=1)

    # Calculate within-chain variance
    W = np.mean(np.var(x, axis=1, ddof=1))

    # Estimate of marginal posterior variance
    Vhat = W*(n - 1)/n + B/n

    return np.sqrt(Vhat/W)
```

Note that all this statistic does is compare the between-chain and within-chain variance, and checks that the ratio of the marginal posterior variance (which combines these two variances) to the within-chain variance is close to one. So, even though you get posterior means that look like this:

![unknown](https://f.cloud.github.com/assets/81476/1568703/888399fa-50b6-11e3-85f7-efe836e82ad4.png)

looking at the chains plotted on the same axes shows pretty clearly that the within- and between-chain variances are pretty indistinguishable:

![unknown-1](https://f.cloud.github.com/assets/81476/1568730/aaf228e4-50b6-11e3-9a13-6599b8602cfa.png)

The fact that the means are not the same is not something that this statistic is able to address.

**Comment by twiecki** [comment]
Closing, feel free to reopen if you think it's still not working @aflaxman

**Comment by aflaxman** [comment]
I think closing is appropriate.  Thanks @fonnesbeck and @twiecki for looking into this for me.

I made a notebook comparing the alternative approaches to this currently available in PyMC3. Would it be appropriate to include in the examples folder, or in the docs in some way?

http://nbviewer.ipython.org/7592472

**Comment by fonnesbeck** [comment]
That's pretty cool, thanks. I think the best place for this will be in the docs, once we get there. We should also spruce up the Wiki with more PyMC 3 content. 

Once I'm done teaching, I'm all over this stuff.

**Comment by twiecki** [comment]
@aflaxman Very instructional. Would definitely be great to have this in the docs.

Some minor points: We moved all imports to `import pymc as pm`. Also, a head-line would look good :).
