### ISSUE TITLE
conda-recipe not working on linux

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#387]
I tried building the conda-recipe over at https://github.com/ContinuumIO/conda-recipes/ from linux but got many errors due to the compiler flags being set and not being understood by gfortran.

@fonnesbeck Is that what you had to set to get it to run under OSX?

In any case, I think a working recipe for all OSs is critical for having a good binary conda package.

**Comment by fonnesbeck** [comment]
Do you know which flags it does not like? Can you try the current recipe in [my fork](https://github.com/fonnesbeck/conda-recipes)?

**Comment by twiecki** [comment]
All of them ;). FWIW, here are the contents that make it compile under linux 32bit:

```
#!/bin/bash

$PYTHON setup.py build
$PYTHON setup.py install
```

But I suspect that we just have to find some minimal subset to make it compile on osx and linux. Certainly `-arch x86_64` will cause problems of 32bit.

Running your recipe thus gives:

```
compile options: '-Ibuild/src.linux-i686-2.7 -I/home/wiecki/envs/_build/lib/python2.7/site-packages/numpy/core/include -I/home/wiecki/envs/_build/include/python2.7 -c'
gcc: build/src.linux-i686-2.7/pymc/flibmodule.c
gcc: error: unrecognized command line option ‘-arch’
gcc: error: x86_64: No such file or directory
gcc: error: unrecognized command line option ‘-arch’
gcc: error: x86_64: No such file or directory
error: Command "gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -fPIC -Ibuild/src.linux-i686-2.7 -I/home/wiecki/envs/_build/lib/python2.7/site-packages/numpy/core/include -I/home/wiecki/envs/_build/include/python2.7 -c build/src.linux-i686-2.7/pymc/flibmodule.c -o build/temp.linux-i686-2.7/build/src.linux-i686-2.7/pymc/flibmodule.o" failed with exit status 
```

**Comment by fonnesbeck** [comment]
I can't get it to build on my system due to some NumPy compatibility issues for the version that is built on Anaconda. For now, I have removed the compiler flags for the recipe in my fork, which will probably do the trick for most people.

**Comment by fonnesbeck** [comment]
Is this still an issue?

**Comment by twiecki** [comment]
No, fixed by https://github.com/pymc-devs/pymc/commit/1e0453cbe7adcbdba0a98d8a23454515cd9816c3.
