### ISSUE TITLE
Theano requirement for python 3

### ISSUE THREAD

**Issue by kyleam** [pymc-devs/pymc3#388]
The theano 0.6.0rc3 requirement is only accurate for python 2 because the theano release in PyPI doesn't support python 3. If the latest release from PyPI is installed under python 3, it results in the import error below. This can be corrected by installing from the theano git repo. Adding `-e git+https://github.com/Theano/Theano.git#egg=Theano` to requirements.txt would fix this (when using `pip -r`), but it would break reading the requirements.txt in as a list to setup.py `install_requires`. With pymc3 in alpha, I don't imagine this is much of an issue at the moment, but, if you all think it's worthwhile, I'll have a shot at getting it running by tweaking setup.py to use the `dependency_links` argument.

```
In [1]: import pymc as pm
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-290dd01c5432> in <module>()
----> 1 import pymc as pm

/home/kyle/src/python/pymc/pymc/__init__.py in <module>()
      1 __version__ = "3.0"
      2
----> 3 from .core import *
      4 from .distributions import *
      5 from .math import *

[...]

/usr/lib/python3.3/site-packages/theano/gof/op.py in <module>()
     23 from theano.misc.windows import call_subprocess_Popen
     24
---> 25 from . import cc
     26 from . import graph
     27 from . import utils

ImportError: cannot import name cc
```

**Comment by twiecki** [comment]
Thanks for pointing that out. Definitely an issue that should be resolved. If you wanted to take a stab at it that'd be very much appreciated.

It also wouldn't be a big deal to just duplicate requirements.txt and setup.py deps.

**Comment by kyleam** [comment]
What is the current use of requirements.txt? Considering it doesn't contain any stricter specifications than`install_requires`, perhaps there isn't much point to having it? I'm thinking along the lines of [this](https://caremad.io/blog/setup-vs-requirement/).

**Comment by twiecki** [comment]
Agreed. I did not know about this so that seems like the way to go. Can you do a PR applying this change?

**Comment by kyleam** [comment]
Sure. The pull request now has this change.
