### ISSUE TITLE
Commit SHA: 76fdfd1c1c477960151566e1cc06e469715e9c3f breaks traceplot for NpTrace

### ISSUE THREAD

**Issue by ryanraaum** [pymc-devs/pymc3#393]
In the recent update to allow the multiple traces to be plotted on the same traceplot axes, trace plotting for NpTrace objects was inadvertantly broken. Where the code now reads:

```
if isinstance(trace, MultiTrace):
    if combined:
        traces = [trace.combined()]
    else:
        traces = trace.traces
```

it needs to have added:

```
if isinstance(trace, MultiTrace):
    if combined:
        traces = [trace.combined()]
    else:
        traces = trace.traces
else: #NpTrace
    traces = [trace]
```

(Sorry for not submitting a pull request - I don't have the pymc repository cloned)

**Comment by fonnesbeck** [comment]
Thanks! I've gone ahead and fixed it, and will push to master when my local test passes.
