### ISSUE TITLE
Make the pymc-devs account into an organization?

### ISSUE THREAD

**Issue by apatil** [pymc-devs/pymc3#40]
Github has organizations now. Would we be OK with making pymc-devs an organization?

**Comment by huard** [comment]
Sure

David

On Tue, May 17, 2011 at 5:55 AM, apatil
reply@reply.github.com
wrote:

**Comment by fonnesbeck** [comment]
If accounts can be converted, sure.

**Comment by apatil** [comment]
Ok.
