### ISSUE TITLE
Text progress bar in long runs blows up IPython notebook file size

### ISSUE THREAD

**Issue by jsw-fnal** [pymc-devs/pymc3#404]
In an overnight run of MCMC.sample, say 50k seconds, the progress bar text is added to the IPython notebook file 100k times.  This results in notebook files that are mostly progress bar text (and surrounding JSON).

Is there any way to change the frequency of the progress bar text output, or better yet to delete the previous output from the notebook file at each output?  There is a quota on my home area, and I'm paranoid that I'm going to lose a computation one of these days due to running over that quota.

**Comment by fonnesbeck** [comment]
You should just turn off the progress bar by specifying `progress_bar=False` in the call to `sample`. Unfortunately, we are stuck with the IPython behavior at the moment. Are you on PyMC 2.3 or 3?

**Comment by jsw-fnal** [comment]
```
pymc.__version__
```

'2.2'

Uh-oh.  I guess I'd better update...  Should I move to 2.3 or to 3 or to development from github (which I think I'm using, master as of June 2013)?

Maybe there's a simple hack I can make to change the display frequency.  I like having the progress bar -- it is very useful for some purposes.  For instance, I modified it to give an estimate of the time remaining and the total time, so I can tune my chain length to take all night.  Even if it just displays every 30 seconds instead of half a second, that would be superior.

**Comment by fonnesbeck** [comment]
You had better use 2.3 (it has been moved to the 2.3 branch), unless you want to convert all your models. The syntax for v.3 is similar, but not identical.

We talked about having a JS progress bar for use in IPython, but it has not yet come to pass. There is actually a `IPythonNotebookPB` class in `pymc.progressbar`, but I don't know if it works. As far as a hack goes, you can go into `MCMC._loop` and mess around with how often the progress bar updates. At the moment, it calls update every iteration but lets the progress bar decide how often to visually update.

**Comment by jsw-fnal** [comment]
OK, I'll look at the progress bar code to change how often it visually updates.  Thanks!
