### ISSUE TITLE
Implement psample using IPython rather than multiprocessing

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#407]
Currently `psample` spawns multiple Python processes that do not go away once `psample` finishes, which results in having to restart the IPython kernel. I typically get 12 orphan processes every time I use it (even though I am only running 2 parallel chains). Apparently this is a known issue but currently without a remedy (ipython/ipython#3833). It might be better to implement multiprocessing using IPython's facilities instead. Of course, this would mean IPython as a prerequisite, but I think few users would object.

EDIT: Actually, restarting the kernel does not kill the processes. They must be manually killed.

**Comment by twiecki** [comment]
Agreed. IPython parallel is better than `multiprocessing` in every respect. Moreover, IPython parallel has support for MPI so can run chains in parallel on a cluster.

**Comment by twiecki** [comment]
Also agree that the dependency isn't a big deal as IPython is the de-facto standard for scientific python computing.

I think though there's also a way to make this agnostic to the engine. If `psample` just takes a pool parameter that it calls `map()` on one could pass in multiprocessing, IPython parallel or some other frameworks that support this interface.

**Comment by bjedwards** [comment]
I noticed the current `psample` never runs `Pool.close` or `Pool.terminate`. Theoretically, `terminate` should run automatically when the pool object is garbage collected, but this may not be happening in IPython for whatever reason.

**Comment by fonnesbeck** [comment]
Wow. That's embarrassing. Thanks for spotting it.

**Comment by bjedwards** [comment]
Does this actually fix things? I was speculating...

**Comment by fonnesbeck** [comment]
Sure does. Thanks again.
