### ISSUE TITLE
Changelog for  PyMC 2 and PyMC 3

### ISSUE THREAD

**Issue by sotte** [pymc-devs/pymc3#409]
Hey!

I'm looking for a Changelog between PyMC 2 and PyMC 3 to figure out what the cool new features are :) Does something like this exist?

**Comment by fonnesbeck** [comment]
Not at present -- we have not added all the cool new features yet! But its definitely something we should do. In fact, I will create a changelog wiki page so that we can add to it as we go along. Thanks!

**Comment by sotte** [comment]
Hey,

Thanks for the quick reply! I was under the impression that PyMC 3 is basically ready to use. Maybe you could mention the status of PyMC in the README? I think a changelog file in the git repository is also nice and it could be included in the docs easily.

**Comment by fonnesbeck** [comment]
It is ready to use (see the `examples` folder in the repo), though all the features that we would like are not in place yet (see the issues for a partial wish list). I was thinking a wiki so that others can add to the list as they think of them, but perhaps the repo is a better place for it.
