### ISSUE TITLE
Test for importing from source tree masks compiler issues on Windows

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#42]
A couple of windows users have reported receiving the "'You seem to be importing PyMC from inside its source tree" error, despite being outside the source tree. Rather, it appears to be a problem with their gcc compiler not building Container_values. I wonder if there is a better test for the import from source tree issue that does not mask other unrelated problems?

```
try:
    import Container_values
    del Container_values
except ImportError:
    raise ImportError, 'You seem to be importing PyMC from inside its source tree. Please change to another directory and try again.'
```

**Comment by apatil** [comment]
Something like `os.getcwd().find(os.path.abspath(os.path.split(os.path.split(pymc.__file__)[0])[0]))>-1`?

**Comment by fonnesbeck** [comment]
Yes, though that would require "pymc" to have already been imported, no?

**Comment by apatil** [comment]
This patch works when pymc is installed with setupegg.py develop on a Mac. Does anyone have it installed with setup.py install?

``` diff

diff --git a/pymc/__init__.py b/pymc/__init__.py
index af76150..cec84d5 100755
--- a/pymc/__init__.py
+++ b/pymc/__init__.py
@@ -16,10 +16,9 @@ except ImportError:

 # Core modules
 from threadpool import *
-try:
-    import Container_values
-    del Container_values
-except ImportError:
+import os
+import pymc
+if os.getcwd().find(os.path.abspath(os.path.split(os.path.split(pymc.__file__)[0])[0]))>-1:
     raise ImportError, 'You seem to be importing PyMC from inside its source tree. Please change to another directory a
 from Node import *
 from Container import *
```

**Comment by fonnesbeck** [comment]
OK, I added this in 70ceab1e1a007d0baff46abdba0d4e751c110058
