### ISSUE TITLE
Gradient calculation fails on Dirichlet with Categorical child.

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#420]
I have implemented the categorical distribution in the `categorical` branch. It works fine when used with non-HMC samplers like Metropolis or Slice, but when using HamiltonianMC or NUTS, sampling fails with the following error:

```
AttributeError: 'All' object has no attribute 'grad'
```

I have modified the `dirichlet.py` example to include a Categorical likelihood. You will see the error here, and it goes away if you change the sampler.

**Comment by fonnesbeck** [comment]
This persists even with the new distribution classes. I have no idea what an "All" object is; it does not appear anywhere in the PyMC codebase, so perhaps its a Theano thing?

**Comment by jsalvatier** [comment]
I think its the `all()` function in theano.

**Comment by fonnesbeck** [comment]
Yes! Just found it moments ago. If I remove the `all(p >= 0)` and `all(p <= 0)` in the bound() call, the error goes away. Seems like the gradient calculation doesn't like them.

**Comment by jsalvatier** [comment]
I think that's a Theano bug.

**Comment by fonnesbeck** [comment]
Odd, because they are used extensively in the multivariate distributions.

**Comment by fonnesbeck** [comment]
It seems to have something to do with the simplex transform:

```
> /Users/fonnescj/Code/pymc/pymc/theanof.py(51)gradient()
-> return t.concatenate([gradient1(f, v) for v in vars], axis=0)
(Pdb) p vars
[simplex_p]
(Pdb) [gradient1(f, v) for v in vars]
    *** AttributeError: 'All' object has no attribute 'grad'
```

**Comment by fonnesbeck** [comment]
I wonder if we should do away with enforcing sum-to-unity constraints and just work with k-1 elements of Dirichlets. This would avoid having to use transformations like this that users should not have to worry about.

**Comment by fonnesbeck** [comment]
I've side-stepped this issue for now, so I am closing, but we can re-open if it troubles us again. Its not clear why it showed up here and not in other distributions that use `all` in the `bound` call.
