### ISSUE TITLE
No suitable default initial values for Multinomial

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#422]
The `Multinomial` distribution does not have a mode (just a mean), and so fails without manually being given a default when used in models, since `quckclass` only looks for modes of discrete distributions.

For example, the following:

```
import numpy as np
from pymc import Model, Gamma, Normal, Dirichlet
from pymc import Multinomial
from pymc import sample, Metropolis

k = 3
ndata = 500

v = np.random.randint(0, k, ndata)
data = ((v == 0)*(50 + np.random.randn(ndata))
        + (v == 1)*(-50 + np.random.randn(ndata))
        + (v == 2)*np.random.randn(ndata))

model = Model()

with model:
    dd = Dirichlet('dd', k=k, a=1, shape=k)
    precs = Gamma('precs', alpha=0.1, beta=0.1, shape=k)
    means = Normal('means', 0, 0.001, shape=k)
    category = Multinomial('category',
                           n=1,
                           p=dd,
                           shape=ndata)

    points = Normal('obs',
                    means[category],
                    precs[category],
                    observed=data)
    tr = sample(3000, step=Metropolis())
```

results in an `AttributeError`

```
AttributeError: <pymc.quickclass.Multinomial object at 0x4804210> has no default 
value to use, checked for: ['mode'] pass testval argument or provide one of these.
```

We could add a mode as follows:

```
round(p*n, 0)
```

if we can do this in Theano. I don't exactly understand how the `round` function works there, based on the docs.

I wonder if it might be worth having something like a `default_init` attribute in distributions, which for most of them could be set to the mean/mode, but for some problematic ones can just be given an arbitrary/random value.

**Comment by jsalvatier** [comment]
Looks like this is fixed.
