### ISSUE TITLE
Travis example tests aren't actually running

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#423]
The travis tests in master don't actually seem to be running. For example: https://s3.amazonaws.com/archive.travis-ci.org/jobs/15501701/log.txt

Says 0 tests run in .001 sec.

**Comment by fonnesbeck** [comment]
Is this still happening?

**Comment by jsalvatier** [comment]
I think its still a problem in master, but solved in https://github.com/pymc-devs/pymc/pull/417
