### ISSUE TITLE
pymc on OSX Mavericks

### ISSUE THREAD

**Issue by jtlz2** [pymc-devs/pymc3#428]
I'm trying to install pymc 2.3 under Mavericks, but have been frustrated by this error:

Enthought Canopy Python 2.7.3 | 64-bit | (default, Aug  8 2013, 05:37:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import pymc

```
Warning: You are importing PyMC from inside its source tree.
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymc/**init**.py", line 26, in <module>
    from .Container import *
  File "pymc/Container.py", line 41, in <module>
    from .Container_values import LCValue, DCValue, ACValue, OCValue
ImportError: No module named Container_values

If I step outside the source tree, I get:

Enthought Canopy Python 2.7.3 | 64-bit | (default, Aug  8 2013, 05:37:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import pymc
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/xxx/canopy/lib/python2.7/site-packages/pymc/**init**.py", line 29, in <module>
> > >     from .CommonDeterministics import *
> > >   File "/Users/xxx/canopy/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
> > >     from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
> > >   File "/Users/xxx/canopy/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
> > >     from . import flib
> > > ImportError: dlopen(/Users/xxx/canopy/lib/python2.7/site-packages/pymc/flib.so, 2): no suitable image found.  Did find:
> > >     /Users/xxx/canopy/lib/python2.7/site-packages/pymc/flib.so: mach-o, but wrong architecture

A stackoverflow question detailing the flib.so 64 v 32 bit error is at

http://stackoverflow.com/questions/20732351/installing-pymc-against-enthought-2-7-3-on-osx-mavericks-10-9-1

Do let me know of any other info you might need.

Many thanks.

**Comment by fonnesbeck** [comment]
Right, the first error is indeed because you are trying to run from within the PyMC directory, which is a no-no. The second error is because of an incompatibility with the binary. Where did you get PyMC from?

**Comment by jtlz2** [comment]
Thanks for the speedy reply - it comes via pip:

pip install pymc

**Comment by fonnesbeck** [comment]
OK, so you are building form source. This probably means your gfortran is not compatible. Do you know where you got yours from? If you use Homebrew, you can try installing that one, or you can grab one from [the AT&T R tools site](http://r.research.att.com/tools/), which works for most folks.

**Comment by jtlz2** [comment]
It comes from macports. I use that and fink and am a bit reluctant to bring homebrew into the mix unless I absolutely have to.

Does the file buildosx get picked up automatically? For what it's worth it contains:

#!/bin/sh
export MACOSX_DEPLOYMENT_TARGET=10.9
export CFLAGS="-arch x86_64"
export FFLAGS="-Wall -ffixed-form -fno-second-underscore -arch x86_64 "
export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch x86_64"
export PYTHONPATH="/Users/xxx/canopy/lib/python2.7/site-packages"
export F77=gfortran-mp-4.8
export CC=gcc-mp-4.8
export CXX=g++-mp-4.8
rm -rf build
python setupegg.py bdist_egg

# sudo python setupegg.py develop

I can supply -m64 to force 64 bits for flib.f, but that's where the hacking comes in, and which I'm also reluctant to do.

**Comment by jtlz2** [comment]
I can't get the CRAN version to work.......

**Comment by jtlz2** [comment]
The homebrew version seems to give the same error with flib :(

**Comment by jtlz2** [comment]
OK it's fixed - I had forgotten to do python setup.py install - the homebrew version worked..........

**Comment by fonnesbeck** [comment]
Yeah, the MacPorts guys did some tweaking to the script to suit them. Glad it worked with Homebrew. The Fortran compatibility is always a stumbling block. The good news is that in PyMC 3, there will be no Fortran so the problem will eventually go away.
