### ISSUE TITLE
Suggestion: move stats() to Trace or Database

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#43]
Hi,

currently, there is no way to print the stats of a loaded database object even though this would be trivial. As it is now, stats() is a method of Node which operates on it's trace instance. If the stats method would be implemented in the Trace class itself and node would just be deferring the call, users could have both, stats() on nodes and stats() from loaded database objects.

I would implement that but wanted to make sure that this wouldn't break anything. I think I'd move stats() in base.Trace. Any input?

-Thomas

**Comment by fonnesbeck** [comment]
Hi Thomas,

I have moved this method to Trace. stats() can now be called from a Trace, a Model, or a Node. Check it out in 70ceab1e1a007d0baff46abdba0d4e751c110058

**Comment by twiecki** [comment]
Hi Chris,

looks great! Thanks for the fast response.
