### ISSUE TITLE
Loading Tutorial notebook fails

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#430]
I get a "Bad Request" failure when I try to load it in a recent build of IPython.

**Comment by sandsfish** [comment]
I'm getting this too, on OS/X.  When viewing the file raw in the Chromium browser, I see the following parse error:

```
Error: Parse error on line 139:
...nt(\"MAP found:\"\n"),      "print(\"x:
-----------------------^
Expecting 'EOF', '}', ':', ',', ']'
```

Appears maybe there's a carriage return syntax  error or something.

**Comment by sandsfish** [comment]
Tried opening it from the browser using the nbviewer ( https://github.com/ipython/nbviewer ) and from the command-line as well.

**Comment by fonnesbeck** [comment]
This is fixed in master now.
