### ISSUE TITLE
n00b trying to learn

### ISSUE THREAD

**Issue by AdamSLevy** [pymc-devs/pymc3#432]
I lack the knowledge to adequately describe my problem. I am trying to follow Probabilistic Programming and Bayesian Methods for Hackers. I need PyMC to work. To my knowledge I have all of the necessary dependencies installed. I am on a mac 2012 15'' retina. I am running 10.9.1, with up to date Anaconda Accelerate distribution of python. 

Here is the error I run into running the introduction of PP&BM4hackrs.

![screen shot 2013-12-23 at 7 16 07 pm](https://f.cloud.github.com/assets/6133616/1804462/3728dc02-6c52-11e3-941c-2c42ef491529.png)

Any ideas troubleshooting this?

**Comment by fonnesbeck** [comment]
The trouble is that you are using the development version of PyMC (version 3) rather than the release version (2.3). You definitely want to be on 2.3 if you are a new user (and it correponds to what is in the book). How did you install?

**Comment by AdamSLevy** [comment]
Thanks.

I used

pip install pymc

How do I specify the version and downgrade?

Also: I just imported pymc and ran

pymc.test()

What repeatedly came up is this:

//anaconda/lib/python2.7/site-packages/scipy/stats/distributions.py:7357: DeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  return (1-p)**(k-1) \* p

**Comment by fonnesbeck** [comment]
Get rid of the PyMC package in the `site-packages` directory and try the following:

```
 pip install pymc==2.3
```

Let me know if it does not work.

**Comment by AdamSLevy** [comment]
That seems to be working now. Thank you so much. When will 3.0 be ready? Where can I read about the differences between the two versions?
