### ISSUE TITLE
What's @pm.deterministic in pyMC3?

### ISSUE THREAD

**Issue by xiaonanji** [pymc-devs/pymc3#434]
I have a tutorial written in pymc 2 using @pm.deterministic. What's the new syntax in pymc3? And any available tutorial for pymc3? I found the resource in Internet about version 3 is very limited! Pretty much all the tutorial ipython notebooks are not working.

Thank you.

**Comment by twiecki** [comment]
You can use `name = pm.Deterministic('name', x + y)`  to add a new deterministic node. And yes, docs are still missing but I'm not aware of the notebooks failing -- can you be more specific?
