### ISSUE TITLE
Errors and Warnings from pymc.test()

### ISSUE THREAD

**Issue by LarryBerk** [pymc-devs/pymc3#436]
PyMC.test() produce 7 figures of autocorrelation, trace and histograms for early_mean,  late_mean, switchpoint and rate as well as two plots of Z-scores.  These plots appear to be OK, although PyMC.test() produces messages like "Could not generate output statistics for..." each of the ploted components.

Windows Binaries were used to install these components:
NumPy v1.8.0
Nose v1.3.0
Python v3.3.0

Several DeprecationWarning messages from pymc/diagnostics.py line 289: "using a non-integer number instead of an integer will result in an error in the future
  first_slice = x[start: start + int(first \* (end - start))]"

One ResourceWarning from pymc\tests\test_interactive.py line 22: "unclosed file <_io.TextIOWrapper name='testresults/interactive.log' mode='w' encoding='cp1252'>"

Installed pyMC 2.3 for Python 3.3.3 on Windows 7 x64 machine.  pyMC.test() returns one error: "invalid syntax test_distributions.py line 1292".  

Here is the error traceback:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\nose\failure.py", line 38, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python33\lib\site-packages\nose\loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python33\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python33\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python33\lib\imp.py", line 180, in load_module
    return load_source(name, filename, file)
  File "C:\Python33\lib\imp.py", line 119, in load_source
    _LoadSourceCompatibility(name, pathname, file).load_module(name)

**Comment by fonnesbeck** [comment]
These look like Python 3 compatibility issues related to PyMC 2.3 that have been addressed since it was released. Are you able to build PyMC from source? If so, try building from the 2.3 branch, and these problems should be fixed.
