### ISSUE TITLE
project conventions

### ISSUE THREAD

**Issue by RayVR** [pymc-devs/pymc3#448]
Is there some reason for using the old method of calling `__init__` directly on the parent class or can I fix this code without causing some known issue?

**Comment by twiecki** [comment]
What do you mean with "fix"? Replacing with calls to `super()`?

**Comment by RayVR** [comment]
that's what I mean.

**Comment by twiecki** [comment]
I brought that up to @jsalvatier who had some concerns but I think we resolved most of them. Personally I'm a bit impartial. I think the main reason is that the current `__init__` call can be copy&pasted while with `super()` you have to pass the class. But beyond that...

**Comment by twiecki** [comment]
I just saw that in some places we're using `super()` while in others not. So I'd be in favor of having everything consistent and switching to `super()` throughout.

**Comment by jsalvatier** [comment]
I'm mildly opposed to super for the reason you described (the call is
different for each class), but not dramatically so.

**Comment by fonnesbeck** [comment]
Ray Hettinger made a pretty good case for using `super()` at PyCon a couple years ago. I can't find the slide deck, but [here is a related blog post](http://rhettinger.wordpress.com/2011/05/26/super-considered-super/). Seems to be the way to go, at least for Python3.
