### ISSUE TITLE
docstring incorrect for Exponential / exponential_like

### ISSUE THREAD

**Issue by rabbitmcrabbit** [pymc-devs/pymc3#45]
Hello

Firstly -- fantastic package. I just starting using it. Keep it up.

I got stuck earlier trying to figure out why my priors weren't behaving as expected. Then I realised that Exponential (and exponential_like) are misdocument. Half of this problem has been corrected between the 2.1beta and the current commit, but the docstrings are still incorrect.

So part of Exponential's docstring reads:

> E = Exponential(name, beta, value=None, observed=False, size=1, trace=True, rseed=True, doc=None, verbose=None, debug=False)
> 
> Stochastic variable with Exponential distribution.
> Parents are: beta.
> 
> .. math:: f(x \mid \beta) = \beta e^{-\beta x}
> 
>    :Parameters:
>      - `x` : x > 0
>      - `beta` : Scale parameter (beta > 0).
> 
>    .. note::
>      - :math:`E(X) = \beta`
>      - :math:`Var(X) = \beta^2`

In commit 5dce4d94341b9de74619f8a81e28095133574f4b, the math form was corrected from the parameterisation 
f(x \mid \beta) = \frac{1}{\beta}e^{-x/\beta}
whereas the current form reflects what's actually being calculated. However the expectations need to be changed as well -- in the current form, E(X) = 1/beta, and Var(X) = 1/beta^2. 

Even still, if this is the preferred form (giving 1/E(X) as the argument, rather than E(X)), then to be consistent with the standard literature, the parameter should be called \lambda and not \beta:
http://itl.nist.gov/div898/handbook/eda/section3/eda3667.htm
http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.exponential.html
http://mathworld.wolfram.com/ExponentialDistribution.html

It seems to be consensus that one parameterises the exponential distribution either as
f(x \mid \beta) = \frac{1}{\beta}e^{-x/\beta}
f(x \mid \beta) = \lambda e^{-\lambda x}

This was my stumbling block...

**Comment by apatil** [comment]
Thanks for the report, it's hard to keep all those docstrings straight. I changed the docstring in comit 894c0f712661892411382b19accab5d78cda1905 but didn't change the name of beta because it would break people's existing code. However, I added a note to the docstring about the parameterization.
