### ISSUE TITLE
import fail: UnicodeDecodeError

### ISSUE THREAD

**Issue by weidongzhou1994** [pymc-devs/pymc3#4522]
when I want to import pyms3, it encounters a problem：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

![image](https://user-images.githubusercontent.com/40510496/110569169-1ce4df80-818f-11eb-89c1-2382812bb21a.png)

**Comment by michaelosthege** [comment]
Which PyMC3 version did you install and how?

From the path `site-packages\theano\...` it looks like they are outdated.

**Comment by weidongzhou1994** [comment]
they are updated:
![Uploading image.png…]()

**Comment by michaelosthege** [comment]
> they are updated:

Looks like you clicked "comment" before the image finished uploading.

**Comment by twiecki** [comment]
What's the output of `gcc -dumpversion`?

**Comment by twiecki** [comment]
I think you should try to install things using conda and the conda-forge channel. Most likely that will resolve all your issues. See the installation instructions: https://github.com/pymc-devs/pymc3/wiki/Installation-Guide-(Windows)

**Comment by weidongzhou1994** [comment]
I have installed all things using conda and the conda-forge channel just like the instructions said.

**Comment by twiecki** [comment]
I think something went wrong with the installation. In your screenshot it shows that it installed from the default channel and that theano-pymc and pymc3 are installed via pip. I would retry in a new environment.

**Comment by weidongzhou1994** [comment]
When I run code in pycharm, it display this error, maybe this is the reason, but how can I resolve it?
![image](https://user-images.githubusercontent.com/40510496/110920597-895f0a80-8358-11eb-9286-c68678647c09.png)

**Comment by michaelosthege** [comment]
Personally, I don't trust the installation through conda-forge on Windows. I would even go as far as saying `conda install -c conda-forge pymc3` (as we currently write in the wiki) just doesn't work.

For me the following is a very reliable installation method:
```
conda create -n mypm3env python=3.8 mkl-service libpython m2w64-toolchain scipy matplotlib pandas
conda activate mypm3env
pip install "pymc3==3.11"
```

I should note that I run these commands with either the standard `cmd.exe` or with [Windows Terminal](https://github.com/microsoft/terminal).
**I wouldn't be surprised if using PowerShell, VS Developer Prompt or the like doesn't work.**

**Comment by twiecki** [comment]
OK, well you should know. Should we update the install instructions then?

**Comment by weidongzhou1994** [comment]
Even though I use the above commands to reinstall pymc3, it still doesn't work, so maybe the reason isn't the command：`conda install -c conda-forge pymc3`. I think the reason maybe is the vscode, but I don't know the way of solution.
![image](https://user-images.githubusercontent.com/40510496/111013650-2d899580-83db-11eb-8fba-c7b23ed1b535.png)

**Comment by weidongzhou1994** [comment]
I got it. That's a Unicode error. When I change the Unicode in the above code, the import  successed.
![image](https://user-images.githubusercontent.com/40510496/111071942-6d539880-8513-11eb-9285-73a076e3f777.png)
![image](https://user-images.githubusercontent.com/40510496/111071953-78a6c400-8513-11eb-81fc-c9af97886c09.png)

**Comment by twiecki** [comment]
@weidongzhou1994 Thanks for reporting back. Is this in your code or our code?
