### ISSUE TITLE
Change to scipy.stats.distributions breaks pymc 2.3

### ISSUE THREAD

**Issue by mmechtley** [pymc-devs/pymc3#454]
scipy.stats.distributions recently made a maintenance change (https://github.com/scipy/scipy/commit/7559f7991bea2858b8c805e7dcf07ad9b9919a0d) that splits the code from distributions.py into two additional files: _continuous_distns.py and _discrete_distns.py. In doing so, they broke distributions.__all__, which is used by pymc 2.x to get the list of available distributions (https://github.com/pymc-devs/pymc/blob/2.3/pymc/ScipyDistributions.py#L228).

Using pymc 2.x with the current scipy dev branch (e.g. current SuperPack) causes pymc import to fail.

**Comment by fonnesbeck** [comment]
That should do it. Please test.

**Comment by mmechtley** [comment]
Seemed to do the trick (using scipy-0.14.0.dev_40896a5-py2.7-macosx-10.9-intel). Thanks!

**Comment by argriffing** [comment]
Sorry for breaking that, it should be fixed in scipy now.
