### ISSUE TITLE
PyMC 2.3.1 (Bugfix release)

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#459]
Its time to get all of the fixes since 2.3 into a release version. I have created [PyMC 2.3.1_rc1](https://github.com/pymc-devs/pymc/tree/2.3.1_rc1) to this end. Please report any problems encountered with this version. The remaining issues in the tracker are non-blocking.

**Comment by fonnesbeck** [comment]
Pushing this out by the end of the week.

**Comment by twiecki** [comment]
This we haven't heard anything, want to push out 2.3.1?

**Comment by fonnesbeck** [comment]
Definitely. Maybe this afternoon.

**Comment by fonnesbeck** [comment]
@twiecki Done. Can you try installing on Anaconda from [my conda-recipes fork](https://github.com/fonnesbeck/conda-recipes) and see if it works on Linux?

**Comment by twiecki** [comment]
Seems like you forgot the setup.py in the package.

**Comment by fonnesbeck** [comment]
Hate setuptools.

**Comment by fonnesbeck** [comment]
OK, should be good now (v2.3.2).

**Comment by twiecki** [comment]
ok, I had to remove the pydot dependency as it apparently was not built for numpy 1.8.0 :-/. I think you'll also want to change the version to 2.3.2. linux 64 is available on https://binstar.org/twiecki/pymc

**Comment by fonnesbeck** [comment]
I have tagged and [released 2.3.2](https://pypi.python.org/pypi/pymc/2.3.2). Thanks!

**Comment by terhardt** [comment]
Don't know if this is the right place. But with the current conda-recipe I could not get PyMC to build on OSX.

I've came up with some change to the recipe and made it work. I'd be awesome if you could check them out and if they are okay, I'll submit a pull request to the conda-recipe repo

you can find them here: tobeplugged/conda-recipes@7f6406de9a8748651cf868d8ade0a99d4306f275

With these changes PyMC compiles and passes the test suite on my system.

**Comment by twiecki** [comment]
@tobeplugged thanks, pulled in via https://github.com/pymc-devs/pymc/commit/1e0453cbe7adcbdba0a98d8a23454515cd9816c3

If you want you can send me your OSX package so that I can upload it, I started an organization at:
https://binstar.org/pymc

**Comment by fonnesbeck** [comment]
I can also push this change to the conda-recipes repo.

@twiecki i noticed you added a `conda` subdirectory. Is that what folks are doing to build in support for Anaconda installs?

**Comment by twiecki** [comment]
@fonnesbeck If you create an account on binstar I can add you to the pymc organization. Just uploaded windows binaries.

Regarding the `conda` subdir, yeah, that's what I was told from some conda devs and I think that's the best way.

**Comment by fonnesbeck** [comment]
Done. Same user name as here.

**Comment by twiecki** [comment]
OK, if you then do inside the pymc dir:
conda build conda

It should tell you the file, then, after you did binstar login:
`binstar upload -u pymc --personal <file>`

**Comment by fonnesbeck** [comment]
Hmm. On build I get:

```
Error: Unsatisfiable package specifications
Hint: pymc 2.3.2 np17py27_0 has a conflict with the remaining packages
```

"remaining packages" is pretty vague. I have no idea.

**Comment by twiecki** [comment]
Sure you have up-to-date conda-build etc? I use miniconda 3.0 for this.

There's another problem you might fix with:
`export CONDA_NPY=18`

**Comment by fonnesbeck** [comment]
I have no idea. I created a new env, but I can't seem to do much with it. Updating anything results in these package conflict errors. 

I thought this sort of pain was what Anaconda was designed to solve??

**Comment by fonnesbeck** [comment]
One issue appears to be that `conda build conda` seems to want to link to Numpy 1.7.1, which can't be good:

```
The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.7.1                |           py27_2   hard-link
    openssl-1.0.1c             |                0   hard-link
    python-2.7.6               |                1   hard-link
    readline-6.2               |                2   hard-link
    sqlite-3.7.13              |                1   hard-link
    tk-8.5.13                  |                1   hard-link
    zlib-1.2.7                 |                1   hard-link
```

I have 1.8 installed, so I'm confused as to why it would be downgrading me.

**Comment by fonnesbeck** [comment]
OK, setting `CONDA_NPY` did the trick. That's insane. You should not have to mess with environmental variables to do this. But never mind ...

How do I get this to the `pymc` user on binstar? Are you going to move it from my account?

**Comment by twiecki** [comment]
Yeah, it's not supposed to be like that, just a bug.

You have to supply `-u pymc` to `binstar upload` and it should add it.

**Comment by fonnesbeck** [comment]
It gives me this error:

```
[NotFound] The path u'/stage/pymc/pymc/2.3.2/osx-64/pymc-2.3.2-np18py27_0.tar.bz2' could not be found
```

I have confirmed that the file I am attempting to upload actually exists on my hard drive.

**Comment by twiecki** [comment]
Is binstar up-to-date? Otherwise, not sure. Might want to post to the conda mailing list.

**Comment by terhardt** [comment]
@twiecki Sorry I was away from the internet. You can find the build here:
https://dl.dropboxusercontent.com/u/8339/pymc-2.3.2-np18py27_0.tar.bz2

I'm glad to help and provide further builds. As soon as I'm back at the office on monday, I will have access to a 64bit Windows as well as Linux machine. (Though I guess the latter is no problem)

**Comment by twiecki** [comment]
@tobeplugged When you tell me your binstar user-name I can add you to the pymc organization so that you can upload yourself.

**Comment by terhardt** [comment]
I'm in the midst of getting one. I'll ping you as soon as possible.

**Comment by terhardt** [comment]
Okay, my binstar user name is also `tobeplugged`.

edit:

I also updated the recipe here to match the one in conda-recipies. See #494

**Comment by twiecki** [comment]
OK, I added you. See above for how to upload to the pymc binstar channel.

It's also quite easy to build python 3 packages using miniconda3.

**Comment by terhardt** [comment]
I'll look into miniconda3.

However It would be more elegant to use some mechanism in conda build to do that. I run all my PhD work on the anaconda install that I have and even though it is amazing how fast I can get back up to speed with anaconda, I'm a little hesitant to screw with it.

**Comment by terhardt** [comment]
Turns out it is quite easy to build against python 3 using anaconda. You can just `export CONDA_PY=33` and do a regular conda build.

However there are a few things in PyMC that need to be changed for the test suite to pass in Python 3. I'm currently working through those errors and I'm yet to come across something that was unfixable.

Edit:
Digging through some old pull requests, I might have dug myself a deeper hole than I initially thought.

**Comment by terhardt** [comment]
@twiecki I see that you added an OSX binary for PyMC. I could not upload mine because of the same error that fonnesbeck described above (Binstar/binstar_client/issues/63).

Did you succeed to build PyMC 2 against Python 3?

**Comment by twiecki** [comment]
@tobeplugged Yes, @fonnesbeck did. Haven't tried Python3 -- is it not working?

**Comment by terhardt** [comment]
No, it does not compile because of a unicode issue with is easily fixed, but after compilation the test suite does not pass.

This happened for two reasons (that I could identify):
- The new devision behavior in Python3.
- On dicts `.values()` does not return a list

I will look through the source code and wrap the `dict.values()` in list statements. That is just busy work. I have the feeling though that more and more will crop up the longer I will look.

But I'll push something as soon as it is ready.

**Comment by twiecki** [comment]
Dang, we indeed don't check for Python 3 compat on travis. It _should_ be compatible so I don't think there should be too many of these issues.

**Comment by fonnesbeck** [comment]
It should already be Python 3 compatible. I will crank out a binary today if I can.

**Comment by terhardt** [comment]
I just opened a pull request (#495) with the fixes that where needed to build and test it in Python 3

**Comment by fonnesbeck** [comment]
Of course, these issues come up days _after_ I deploy a release ...
