### ISSUE TITLE
bug in laplace_like when called with an array

### ISSUE THREAD

**Issue by mbakker7** [pymc-devs/pymc3#470]
There appears to be a bug in the `laplace_like` function. 
It now returns:

```
return flib.gamma(np.abs(x-mu), 1, tau) - np.log(2)
```

But when `x` is an array (which it really always is), should be `N * np.log(2)`, where `N` is the length of `x`, so the code should be something like this:

```
N = 1
if hasattr(x, "__len__"): N = x.__len__()
return flib.gamma(np.abs(x-mu), 1, tau) - N * np.log(2)
```

Easy test case:

```
import pymc
print -pymc.distributions.laplace_like(array([8]), 10, 1)
print -pymc.distributions.laplace_like(array([9]), 10, 1)
# likelihood of values 8 and 9 together
print -pymc.distributions.laplace_like(array([8]), 10, 1) -pymc.distributions.laplace_like(array([9]), 10, 1)   
# should give the same answer, but doesn't without the suggested fix    
print -pymc.distributions.laplace_like(array([8,9]), 10, 1)
```

This is also confirmed by comparison with the `laplace.nnlf` of `scipy.stats`

```
from scipy.stats import laplace
print laplace.nnlf((10,1),array([8,9]))
```

**Comment by fonnesbeck** [comment]
Ignore the deleted comment. Will push the fix momentarily. Thanks.

**Comment by fonnesbeck** [comment]
OK, should be fixed (and a test added!) in 2.3 branch. Please test.

**Comment by mbakker7** [comment]
Thanks Chris.
What is the easiest way to update to pymc 2.3?
easy_install?

Mark

**Comment by fonnesbeck** [comment]
Its a little tricky because you need to install from the 2.3 branch. The easiest way is probably pip:

```
pip install git+https://https://github.com/pymc-devs/pymc.git@2.3
```
