### ISSUE TITLE
PyMC3 Disaster Model Switchpoint Error

### ISSUE THREAD

**Issue by QCaudron** [pymc-devs/pymc3#471]
The disaster model example (https://github.com/pymc-devs/pymc/blob/master/pymc/examples/disaster_model.py) always returns a switchpoint that is halfway between the time span allowed by the DiscreteUniform. I believe it's a problem with line 41, where switchpoint and a numpy array are compared elementwise.

**Comment by jsalvatier** [comment]
That actually looks right to me, but you ran the model and it didn't sample properly?
