### ISSUE TITLE
Travis tests failing

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#474]
The tests are not working and haven't for a while. Lets fix that. 
At least one of the errors is:

```
ERROR: pymc.tests.test_plots.test_plots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_plots.py", line 20, in test_plots
    forestplot(trace)
  File "/home/travis/build/pymc-devs/pymc/pymc/plots.py", line 325, in forestplot
    interval_plot = subplot(gs[0])
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 896, in subplot
    fig = gcf()
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 450, in gcf
    return figure()
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 31, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 38, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 70, in __init__
    FigureCanvasQT.__init__( self, figure )
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 207, in __init__
    _create_qApp()
  File "/home/travis/anaconda/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 62, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
-------------------- >> begin captured stdout << ---------------------
[                  0%                  ] 2 of 3000 complete in 0.5 sec
[-----------------79%----------        ] 2382 of 3000 complete in 1.0 sec
[-----------------100%-----------------] 3000 of 3000 complete in 1.1 sec

--------------------- >> end captured stdout << ----------------------
```

Any idea what's going on?

**Comment by fonnesbeck** [comment]
I've been working on this this in the `fix_travis` branch. It has to do with Matplotlib trying to use a backend, but since this a remote task there is no display (hence the lack of a DISPLAY variable). I have poked around and tried various suggestions on StackOverflow, such as using the `Agg` backend in our tests, but nothing seems to work. 

I'm pretty fed up with MPL, to be honest. I'm half tempted to explore other plotting options, such as D3, that we could simply bake into PyMC and drop this troublesome dependency.

**Comment by jsalvatier** [comment]
Can we mark the MPL stuff with known failure for now? Also, was this a
recent change? I thought these tests were passing before. Can we just
specify the version?

Have we talked to the MPL user/dev list? Since we're another package trying
to rely on them, maybe they will give us some help.

**Comment by kyleam** [comment]
I'm surprised that using Agg (as done on the fix_travis branch) didn't
fix it. As long as it comes before any pyplot/pylab imports, I think it
should do the trick. I'm not having any luck finding the plot errors in
the Travis log files. Do all the jobs from the fix_travis branch have
them? I thought that `test_plots.py` runs during the
`-e test_glm -e test_examples -e test_distributions` command,
but I'm not seeing the plot failure.

**Comment by fonnesbeck** [comment]
The errors can be found pretty reliably on runs of the `fix_travis` branch. [Here is one](https://s3.amazonaws.com/archive.travis-ci.org/jobs/17517100/log.txt). I have gone through (in that branch) and added `matplotlib.use('Agg') at the beginning of all the tests that use plotting, so I am also surprised at what's going on.

**Comment by fonnesbeck** [comment]
@jsalvatier I'm sure we will track this down, but MPL is always such a moving target that issues like this come up a fair bit (going back to PyMC 2). Particularly when there are far more pressing development tasks, its a source of frustration for me, at least.

**Comment by kyleam** [comment]
OK, I may have found the issue. I think `matplotlib.use('Agg')` is not
getting called before pyplot is imported because when `plots` and `glm`
are imported in pymc/**init**.py, they import pyplot. Making the
following changes on top of master seems to fixes the test_plots.py run
for me.

```
diff --git i/pymc/__init__.py w/pymc/__init__.py
index 44760fd..5c5ef91 100644
--- i/pymc/__init__.py
+++ w/pymc/__init__.py
@@ -13,9 +13,9 @@ from .debug import *

 from .diagnostics import *

-from .plots import *
+#from .plots import *

 from .tests import test

-from . import glm
-from .data import * 
+# from . import glm
+from .data import *
diff --git i/pymc/tests/test_plots.py w/pymc/tests/test_plots.py
index f31b9a5..5d6f14f 100644
--- i/pymc/tests/test_plots.py
+++ w/pymc/tests/test_plots.py
@@ -1,4 +1,7 @@
 #from ..plots import *
+import matplotlib
+matplotlib.use('Agg')
+
 from pymc.plots import *
 from pymc import psample, Slice, Metropolis, find_hessian, sample
```

**Comment by kyleam** [comment]
Sorry for the formatting issues. I can't seem to fix them by editing the comment.

**Comment by jsalvatier** [comment]
If the import order in init is important let's put a comment  mentioning why

**Comment by kyleam** [comment]
I'm having all sorts of trouble commenting today. I'm just copying and pasting an email reply that didn't seem to make it through. 

---

On 01/24/14 15:33, John Salvatier wrote:

> If the import order in init is important let's put a comment  mentioning why

It's not the order in `pymc/__init__.py`, but that pymc is loaded up (I
think by nose) before `test_plots.py`, where `matplotlib.use('Agg')` is
called, meaning that an interactive backend has already been selected.

The above patch commenting out the imports was just meant to show that
this was the issue. I think the best way to fix it should be discussed
because removing the imports would remove the plotting functions from
the top-level namespace.

**Comment by kyleam** [comment]
It seems that the recent Travis runs with the above changes passed (with respect to the MPL backend error).

I've pushed a [branch](https://github.com/kyleam/pymc/tree/fix-mpl-travis-function-imports) with a proposed fix that still allows the top-level import of the plotting functions.

**Comment by jsalvatier** [comment]
Thank you :)

**Comment by twiecki** [comment]
:+1:

**Comment by aflaxman** [comment]
This is so great, thanks!  Nosetests now run to completion for me, although there are still some test failures, about data paths and theano functions:

```
Ran 152 tests in 3093.846s

FAILED (SKIP=2, errors=5)
```

**Comment by fonnesbeck** [comment]
I will test this and merge it, if that's okay. I'm experimenting with using conda for the Travis builds, as the install procedures tend to be faster.

**Comment by fonnesbeck** [comment]
OK, this works for me too. Errors now seem to be due to `inplace_increment` in Theano, but MPL-related issues are gone. Will merge.

**Comment by kyleam** [comment]
> I will test this and merge it, if that's okay.

Sounds good. Thanks.

**Comment by fonnesbeck** [comment]
Yeah, [not entirely clean, but better than it was](https://travis-ci.org/pymc-devs/pymc/builds/17711489)

**Comment by twiecki** [comment]
I tried to speed up the installation a bit more by separating out numdifftools.

**Comment by twiecki** [comment]
Neat, we're down to 8 min 32 sec for test_distributions now: https://travis-ci.org/pymc-devs/pymc

**Comment by twiecki** [comment]
As @mwaskom pointed out I think https://github.com/pymc-devs/pymc/blob/master/pymc/__init__.py#L3 leads to a problem when using pymc interactively with a different backend.

**Comment by mwaskom** [comment]
Maybe a solution would be to have the Travis pre-test script do something like

```
- echo backend : Agg > .matplotlibrc
```

I'm not sure exactly where the local rc file will need to be for matplotlib to pick it up, possible in the `pymc/` directory itself. But, could work.

**Comment by kyleam** [comment]
I don't think selecting Agg in the top-level init is necessary. Adding
it to the top of the tests should be all that is needed. With the
function-level imports, the backend calls in the tests should be loaded
first.

**Comment by kyleam** [comment]
I checked again using just the changes from 40a8070. Both interactive
and non-interactive backends work for me. Selecting the Agg backend at
the top-level init file overrides the effects of 40a8070.

**Comment by twiecki** [comment]
@kyleam I think the use-case would be that you import pymc before anything else and then try to plot interactively. Does that work?

**Comment by kyleam** [comment]
> @kyleam I think the use-case would be that you import pymc before
> anything else and then try to plot interactively. Does that work?

Yes, it should work as normal. If you call a plotting function, it will
determine the backend with the normal matplotlib mechanisms. For the
typical matplotlib user settings, this will be an interactive backend.
So, this works:

```
import pymc
import matplotlib.pyplot as plt
plt.plot(range(10))
```

The point of the function-level imports is that a backend is not
selected before the tests or the user have a chance set the
non-interactive Agg backend. The reason this is necessary is that
matplotlib requires the backend being selected before any pyplot/pylab
import.

Please let me know if I'm missing something, or if the changes in
40a8070 aren't working for you.

**Comment by mwaskom** [comment]
Just a note that I now have a solution to this problem for testing `seaborn` that is outlined [here](https://github.com/mwaskom/seaborn/pull/97) if it is of interest.

**Comment by kyleam** [comment]
That seems like a good solution, but there are a couple reasons I'd
prefer function-level imports over using .matplotlibrc.
1. It works without having to do anything Travis-specific. This means
   that if anyone runs tests in a non-interactive environment, they'd
   work fine.
2. Users that want to use a different backend for matplotlib don't have
   to worry about the order that they import pymc. Without the
   function-level imports, they'd either have to import matplotlib and
   select another backend first, or they'd have to change their
   matplotlib configuration.

I think the function-level imports are inline with the convention
John Hunter described:

  https://groups.google.com/forum/#!msg/pystatsmodels/biNlCvJPNNY/BT7bQJmOa1cJ

**Comment by twiecki** [comment]
`Build #691 passed.`

Finally!

**Comment by jsalvatier** [comment]
Awesome!
