### ISSUE TITLE
node-name gets changed during append

### ISSUE THREAD

**Issue by hajasw** [pymc-devs/pymc3#476]
I might just be crossed-up in different naming-conventions for arrays of nodes.  However, I had a very specific name I wanted to use and utils.append changed the name on me.

Below, is the output from a debug-session.  I think the problem is clear.  

As an interim solution, I am just going to explicitly rename some nodes to what I want them to be.  No crisis on my end.

Regards, 
Wayne Hajas

I want to keep "YearEff_2007" as the name of the node.  In the append, the name gets changed to "YearEff_6"

> d:\analyses\cukenonparamprod\pyfunctions\prodmodelgs.py(53)LocNodes()
> -> self.YearEff=append(self.YearEff,LastYear)
> (Pdb) s
> --Call--
> c:\python33\lib\site-packages\pymc\utils.py(907)append()
> -> def append(nodelist, node, label=None, sep='_'):
> (Pdb) p node.__name__
> 'YearEff_2007'
> (Pdb) s
> c:\python33\lib\site-packages\pymc\utils.py(923)append()
> -> nname = node.**name**
> (Pdb) s
> c:\python33\lib\site-packages\pymc\utils.py(926)append()
> -> label = label or len(nodelist)
> (Pdb) s
> c:\python33\lib\site-packages\pymc\utils.py(929)append()
> -> ind = nname.rfind(sep)
> (Pdb) s
> c:\python33\lib\site-packages\pymc\utils.py(933)append()
> -> node.**name** = nname[:ind] + sep + str(label)
> (Pdb) s
> c:\python33\lib\site-packages\pymc\utils.py(935)append()
> -> nodelist.append(node)
> (Pdb) p node.**name**
> 'YearEff_6'
> (Pdb) s
> c:\python33\lib\site-packages\pymc\utils.py(937)append()
> -> return nodelist
> (Pdb)

**Comment by fonnesbeck** [comment]
Wayne, can you post the relevant chunk of code?

**Comment by hajasw** [comment]
This is one of those embarrassing situations.  I can't duplicate the error I was getting yesterday.  I'm glad I at least caught the debugger-results.    For whatever it is worth, the offending code-segment is below.  I am using pymc 2.2.2, python 3.3 and Windows 7.  I can't think of any other pertinent information.  

```
#Year Effects
self.YearEff= [Normal('YearEff'+'_%i' %self.L.SurveyYears[i],  0.0, self.tauYear) for i in range(self.L.nYear-1)]
i=self.L.nYear-1
LastYear=Lambda('YearEff'+'_%i' %self.L.SurveyYears[i],lambda x=self.YearEff:-sum(x))
self.YearEff=append(self.YearEff,LastYear)
```

**Comment by fonnesbeck** [comment]
I cannot reproduce.
