### ISSUE TITLE
Unable to install / use on windows, various methods tried.

### ISSUE THREAD

**Issue by jcress** [pymc-devs/pymc3#479]
After a fresh install of pythonxy on windows 7 (32 bit), 

I try pip install pymc and see

Found executable C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\link.exe

Creating library build\temp.win32-2.7\Release\cephes\flib.lib and object build\temp.win32-2.7\Release\cephes\flib.exp

flib.o : error LNK2019: unresolved external symbol _erf referenced in function _ factln_

build\lib.win32-2.7\pymc\flib.pyd : fatal error LNK1120: 1 unresolved externals

easy_install pymc works though.  however, after doing easy_install pymc I fire up python and get 

Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on
32
Type "help", "copyright", "credits" or "license" for more information.

> > > import pymc as pm
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\pymc-2.3-py2.7-win32.egg\pymc__init__.
> > > , line 26, in <module>
> > >     from .Container import *
> > >   File "C:\Python27\lib\site-packages\pymc-2.3-py2.7-win32.egg\pymc\Container
> > > ", line 41, in <module>
> > >     from .Container_values import LCValue, DCValue, ACValue, OCValue
> > > ImportError: DLL load failed: The specified module could not be found.

I don't know what to do from here.

**Comment by jsalvatier** [comment]
It looks like its trying to use the Visual Studio Compiler, but I think you
want to use MinGW (
http://sourceforge.net/projects/mingw-w64/?source=recommended).

**Comment by twiecki** [comment]
@jcress FWIW, I think anaconda works better with pymc and there are even conda binary packages here: https://binstar.org/twiecki

**Comment by jcress** [comment]
thanks twiecki

removing pythonxy and installing conda, then 
conda install -c https://conda.binstar.org/twiecki pymc

as directed solved the problem.  I can import pymc now.  

Thanks.
