### ISSUE TITLE
Name error from "exceptions.KeyError" in plots.py

### ISSUE THREAD

**Issue by coventry** [pymc-devs/pymc3#483]
https://github.com/pymc-devs/pymc/blob/bd69788241c040680ead2573dc5c60eb20f04266/pymc/plots.py#L76

Putting `import exceptions` in the header of the file fixes it.

Installed pymc on OS X 10.9 with the command `pip install git+https://github.com/pymc-devs/pymc` an hour or so ago.

**Comment by kyleam** [comment]
> Putting `import exceptions` in the header of the file fixes it.

Thanks. `KeyError` is in the default namespace, so line 76 should just
be `except KeyError`.
