### ISSUE TITLE
pymc and DYLD_FALLBACK_LIBRARY_PATH

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc3#490]
Note: This issue has a [thread](http://stackoverflow.com/questions/21713148/psycopg2-pymc-theano-and-dyld-fallback-library-path) at StackOverflow.
I am unable to use `pymc` along with `psycopg2`. The following simple snippet from the tutorial:

```
import pymc as pm
with pm.Model() as model:
    x = pm.Normal('x', mu=0., sd=1)
```

results in the following error:

> Exception: The environment variable 'DYLD_FALLBACK_LIBRARY_PATH' does
> not contain the '/Users/josh/anaconda/envs/py27/lib' path in its
> value. This will make Theano unable to compile c code. Update
> 'DYLD_FALLBACK_LIBRARY_PATH' to contain the said value, this  will fix
> this error.

I was able to fix this problem by adding:

```
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/Users/josh/anaconda/envs/py27/lib
```

to my shell init file `.bashrc`. **However**, and this is the part I don't understand, that line breaks `psycopg2`:

```
---> 50 from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
     51 
     52 from psycopg2._psycopg import Binary, Date, Time, Timestamp

ImportError: dlopen(/Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: @loader_path/../../../libpq.5.dylib                                                                                                 
  Referenced from: /Users/josh/anaconda/envs/py27/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

How can I have `psycopg2` and `pymc` (here `theano`) live happily together?

This is on OS X with a Python 2.7.6 installation with an Python environment created with [conda](http://docs.continuum.io/conda/index.html).

**Comment by jsalvatier** [comment]
Are you able to import just Theano and psycog2 together? Are you able to
import then both individually?

**Comment by amelio-vazquez-reina** [comment]
Thank you @jsalvatier I am able to import them without having to modify `DYLD_FALLBACK_LIBRARY_PATH`.  But just in case. the problem in `pymc` appeared when **creating the model**, specifically on the line: `x = pm.Normal('x', mu=0., sd=1)` above in the tutorial. To clarify, this error disappears if I do 
`export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/Users/josh/anaconda/envspy27/lib`

**Comment by jsalvatier** [comment]
Oh, yeah, I wasn't paying enough attention. I don't think I have the
expertise to be able to give you very good help. I would also open a ticket
with theano (https://github.com/Theano/Theano/issues?state=open) and link
to this one. I think they will be able to give you better help.

Does using theano directly work for you? Try one of these:
http://deeplearning.net/software/theano/tutorial/adding.html

**Comment by amelio-vazquez-reina** [comment]
I fixed the problem by installing from theano/master as explained [here](https://github.com/Theano/Theano/issues/1730).

**Comment by jsalvatier** [comment]
Awesome :)
