### ISSUE TITLE
PyMC 3 Documentation and User Guides

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc3#497]
What is the state of the PyMC **3** documentation? (User Guide, API reference and examples).

I am aware of:
- [Probabilistic Programming and Bayesian Methods for Hackers](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers)
- [PyMC User's Guide](http://pymc-devs.github.io/pymc/)

But they are both for PyMC **2**. 

Besides the [PyMC 3 tutorial](http://nbviewer.ipython.org/github/pymc-devs/pymc/blob/master/pymc/examples/tutorial.ipynb), are there any documentation, API references or user guides for PyMC **3**?

**Comment by fonnesbeck** [comment]
PyMC 3 is still in alpha, so we have not prepared documentation for public use. We recommend that most users stick to PyMC 2, unless you are interested in testing or contributing. When PyMC 3 is released, there will be complete documentation, and I am working on a book for Bayesian computation that will be based on PyMC 3. So, stay tuned.

As far as examples go, there are several in the `pymc/examples` directory in the master branch.

**Comment by amelio-vazquez-reina** [comment]
Thank you @fonnesbeck. That makes sense. One humble suggestion/question: Would it make sense to state something along those lines in the `readme.md` file, considering that the main view of the PyMC GitHub repository is for PyMC 3? (as a new user of the package, seeing **PyMC 3** on the front page of the GitHub repository for PyMC made me think that it  was ready for public use). Perhaps a short notice would suffice, at least to prevent first comers from repeating the same question here.

**Comment by fonnesbeck** [comment]
Done, thanks.
