### ISSUE TITLE
Improve example model set

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#5]
It would be nice to incorporate some of the better examples posted on the website into the examples in the source tree. There isn't a great deal of variety in the current example set, and several are very similar. I invite proposals for models to remove from and add to the current set.

**Comment by apatil** [comment]
Very good idea. Also, we should probably re-focus the docs and examples around the one-liner syntax, with the decorators there if you need them.

**Comment by jsalvatier** [comment]
I definitely agree with anand. Now that there are a lot of deterministic factory functions, and operators for making deterministics this should be the way to go.

**Comment by fonnesbeck** [comment]
That's probably a good idea, though the decorator syntax is one of the Great Strengths of PyMC. You can't make arbitrary stochastics in BUGS/JAGS!

**Comment by jsalvatier** [comment]
I've found someone interested in contributing to PyMC. Both of us think improving the example set, cleaning them up and making them simpler by using the one-liner syntax, would be a great initial project since it shouldn't be too hard, it's necessary and should provide a good introduction to PyMC. He should be able to start this sometime after April 7.

**Comment by apatil** [comment]
Sweet! Obviously that's fine by me. I think everyone has write permissions to the wiki.

**Comment by fonnesbeck** [comment]
I have added a couple of new models, a melanoma survival model and a zero-inflated Poisson model, and removed some old ones. I tried to make the style consistent among the model set. The examples are now a little biostat-heavy, so if others have some good ones (e.g. econometric, astrophysical), please feel free to suggest them.
