### ISSUE TITLE
GP Examples not in installed package code

### ISSUE THREAD

**Issue by chrisjordansquire** [pymc-devs/pymc3#50]
The GP examples in the source do not appear in the examples file in the installed code for the pymc package. (All the other examples do seem to be there, though.)

**Comment by fonnesbeck** [comment]
Is the entire gp folder absent?

**Comment by chrisjordansquire** [comment]
The folder pymc/gp exists, but pymc/examples/gp is completely absent.

**Comment by fonnesbeck** [comment]
OK, cb1052258cf97c890242bc23abea6b591ff13bc1 should fix it.
