### ISSUE TITLE
Ways to debug pymc calculations?

### ISSUE THREAD

**Issue by coventry** [pymc-devs/pymc3#504]
As I indicate in this [SO question](http://stackoverflow.com/questions/22030576/debugging-pymc-probability-calculations),  it can be pretty hard to debug why a pymc calculation is failing using the standard python debugging tools.  It would be great if there was a way to see the steps which go into pymc's calculation of a probability value.

**Comment by fonnesbeck** [comment]
John answered this on SO. Closing.
