### ISSUE TITLE
Question about `expm()` and `observed`

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc3#505]
I've got a model where I observe A and B, which should be related by a matrix exponential.  I'm having some difficulties getting this working:

```
import pymc as pm

n = 2
A_obs = np.random.normal(size=(n))
B_obs = np.random.normal(size=(n))

with pm.Model() as model:
    A = pm.Normal("A", mu=0., sd=1., shape=(n), observed=A_obs)
    K = pm.Normal("K", mu=0., sd=1., shape=(n, n))
    mu = pm.dot(pm.theanof.t.expm1(-K), A)
    B = pm.Normal("B", mu=mu, sd=1., shape=(n), observed=B_obs)
```

The code dies with this exception:

```
---> 10     mu = pm.dot(pm.theanof.t.expm1(-K), A)

AsTensorError: ('Cannot convert <pymc.model.ObservedRV object at 0x580d4d0> to TensorType', <class 'pymc.model.ObservedRV'>)
```

However, if I replace `expm()` with some other deterministic transformation, things work just fine.  For example, the following code runs just fine.  

```
import pymc as pm

n = 2
A_obs = np.random.normal(size=(n))
B_obs = np.random.normal(size=(n))

with pm.Model() as model:
    A = pm.Normal("A", mu=0., sd=1., shape=(n), observed=A_obs)
    K = pm.Normal("K", mu=0., sd=1., shape=(n, n))
    mu = 2.0 * pm.exp(K.sum()) + 3.0
    B = pm.Normal("B", mu=mu, sd=1., shape=(n), observed=B_obs)

with model:
    start = pm.find_MAP()    

with model:
    step = pm.Metropolis()

with model: 
    trace = pm.sample(5000, step, start)

```

Does anyone have any thoughts?

**Comment by kyleabeauchamp** [comment]
PS: I am using the latest git revision.

**Comment by jsalvatier** [comment]
I think what's its failing on is that you're passing `A` in to dot and A is
observed. Right now observed nodes are not tensors. I'd like to make them
so in the future, but we have to handle the case where the observed data is
a more complex data structure than a single array and theano doesn't have a
tuple type.

Looks like it would have helped to have better **str** methods here, so you
could have told _which_ variable was causing problem.

**Comment by jsalvatier** [comment]
You should be able to fix this by passing A_obs to dot instead of A.

**Comment by kyleabeauchamp** [comment]
To me, that's a slightly different model, right?  IMHO that would destroy the uncertainty on A, but preserve the uncertainty on B.  Or maybe I'm misunderstanding things.

**Comment by jsalvatier** [comment]
`mu = pm.dot(pm.theanof.t.expm1(-K), A)` should be `mu =
pm.dot(pm.theanof.t.expm1(-K), A_obs)`

Which is the exact same model since for A you set observed=A_obs.
There is no uncertainty in A since you say you're observing it.

**Comment by kyleabeauchamp** [comment]
Alright, I think I was misunderstanding something--I need another "hidden layer" in my model.  Thanks.

**Comment by jsalvatier** [comment]
Glad to help :)
