### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by Sayam753** [pymc-devs/pymc3#5056]
The links in this README section - https://github.com/pymc-devs/pymc#if-you-already-know-about-bayesian-statistics are broken. We need to fix them.

Related info -
The hosting of docs.pymc.io is switched from GitHub pages to ReadTheDocs. All the links earlier from docs.pymc.io will be redirected at docs.pymc.io/en/stable.

**Comment by twiecki** [comment]
Yes, can we also add an auto-redirect?

**Comment by Sayam753** [comment]
The auto-redirection is working. As an example - https://docs.pymc.io/api.html will be redirected to https://docs.pymc.io/en/stable/api.html

But, there are still broken links in README.rst file.

**Comment by twiecki** [comment]
Which ones?

**Comment by aandroni** [comment]
Hi,

There are 4 broken links: 'getting started guide' (first section), 'API quickstart guide', 'PyMC tutorial', and 'API reference' (in the 'Getting started' section).

I’d be happy to fix them if that’s ok with you.

**Comment by twiecki** [comment]
@aandroni That would be much appreciated!

**Comment by aandroni** [comment]
Ok thanks, I've created a PR.

**Comment by Sayam753** [comment]
Thanks for the PR @aandroni
