### ISSUE TITLE
Add generalized normal distribution

### ISSUE THREAD

**Issue by shifdz** [pymc-devs/pymc3#5102]
Is it possible to use distributions from scipy stat or tensorflow probability in PYMC3? I need to use generalized normal distribution, but it is not avialable in PYMC3. Any help is really appreciated.

**Comment by ricardoV94** [comment]
You cannot use scipy/tensorflow directly, you need a function defined in theano. 

Looking at the density funcition it should be pretty straightforward to define your own: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gennorm.html

I will mark this issue as a feature request. In the meantime if you want to go ahead and add your own distribution for your project I suggest you open an topic in our discourse: https://discourse.pymc.io/

Someone will probably help you out there

**Comment by shifdz** [comment]
I am new to programming and haven't worked in Theano, so I am not sure how to define a new distribution. Can someone please help me with implementing it? I opened a topic on Discourse, but didn't get any response.

**Comment by twiecki** [comment]
@shifdz There is a guide here: https://github.com/pymc-devs/pymc/issues/4686#issuecomment-839541040

**Comment by shifdz** [comment]
@twiecki  Will the generalized normal distribution be added in pymc3 any time soon?

**Comment by twiecki** [comment]
@shifdz Whenever someone creates a pull request :) It's not that hard and we're happy to help if you want to give it a go.
