### ISSUE TITLE
summary and traceplot with dimensions > 1

### ISSUE THREAD

**Issue by awellis** [pymc-devs/pymc3#512]
When running the 'hierarchical' example in pymc 3, I get the following warnings when calling

summary(trace)

/Users/andrew/anaconda/lib/python2.7/site-packages/pymc/trace.py:160: UserWarning: Skipping group_effects (above 1 dimension)
  warnings.warn('Skipping {} (above 1 dimension)'.format(var))
/Users/andrew/anaconda/lib/python2.7/site-packages/pymc/trace.py:160: UserWarning: Skipping effects (above 1 dimension)
  warnings.warn('Skipping {} (above 1 dimension)'.format(var))

group_effects has shape=(1, 1, 3) and 
effects has shape=(10, 3)

calling traceplot(trace) produces the following error:

---

LinAlgError                               Traceback (most recent call last)
<ipython-input-10-0a19dd14965b> in <module>()
----> 1 traceplot(trace)

/Users/andrew/anaconda/lib/python2.7/site-packages/pymc/plots.pyc in traceplot(trace, vars, figsize, lines, combined, grid)
     61                 histplot_op(ax[i, 0], d)
     62             else:
---> 63                 kdeplot_op(ax[i, 0], d)
     64             ax[i, 0].set_title(str(v))
     65             ax[i, 0].grid(grid)

/Users/andrew/anaconda/lib/python2.7/site-packages/pymc/plots.pyc in kdeplot_op(ax, data)
     94     for i in range(data.shape[1]):
     95         d = data[:, i]
---> 96         density = kde.gaussian_kde(d)
     97         l = np.min(d)
     98         u = np.max(d)

/Users/andrew/anaconda/lib/python2.7/site-packages/scipy/stats/kde.pyc in **init**(self, dataset, bw_method)
    186 
    187         self.d, self.n = self.dataset.shape
--> 188         self.set_bandwidth(bw_method=bw_method)
    189 
    190     def evaluate(self, points):

/Users/andrew/anaconda/lib/python2.7/site-packages/scipy/stats/kde.pyc in set_bandwidth(self, bw_method)
    496             raise ValueError(msg)
    497 
--> 498         self._compute_covariance()
    499 
    500     def _compute_covariance(self):

/Users/andrew/anaconda/lib/python2.7/site-packages/scipy/stats/kde.pyc in _compute_covariance(self)
    507             self._data_covariance = atleast_2d(np.cov(self.dataset, rowvar=1,
    508                                                bias=False))
--> 509             self._data_inv_cov = linalg.inv(self._data_covariance)
    510 
    511         self.covariance = self._data_covariance \* self.factor**2

/Users/andrew/anaconda/lib/python2.7/site-packages/scipy/linalg/basic.pyc in inv(a, overwrite_a, check_finite)
    381         inv_a, info = getri(lu, piv, lwork=lwork, overwrite_lu=1)
    382     if info > 0:
--> 383         raise LinAlgError("singular matrix")
    384     if info < 0:
    385         raise ValueError('illegal value in %d-th argument of internal '

LinAlgError: singular matrix

Is this intended behaviour? If so, what is the best way of getting summaries and trace plots of parameters with dimensions > 1?

**Comment by kyleam** [comment]
The warning for `summary` is the intended behavior. There's nothing in place right now to format variables over one dimension.

In terms of getting summaries for these variables, the functions in `pm.stats` (which are used in `summary`) will return arrays and should handle higher dimensions well.

```
In [4]: pm.stats.hpd(trace['effects'])
Out[4]:
array([[[ 1.96376297,  2.74802032],
        [ 1.99808192,  2.66065603],
        [-1.41440043, -0.65700887]],

       [[-1.08918516, -0.31116905],
        [-0.61882633,  0.32675753],
        [-0.32408858,  0.46829886]],

        ...

       [[ 0.51522619,  1.28986061],
        [-0.61824142,  0.08629609],
        [ 1.07584739,  1.81785731]]])
```

For plotting, I think `traceplot` should also be giving a warning there because it can't handle variables over one dimension right now either. At the moment, the only way to get plots for these variables would be to use matplotlib and the variable array directly. PyMC 2 handled higher dimensional variables, but PyMC 3 doesn't yet (#242).

**Comment by jsalvatier** [comment]
Yeah, we should add a more informative error or find a way to reshape
appropriately.

**Comment by jsalvatier** [comment]
Basically, we need to take an array of shape (n, d1, d2, d3 ... ) and
reshape it into an array of shape (n, product( d1, d2, d3...)) but have the
first dimension _mean_ the same thing as before. This should be achievable
with clever reshaping. Something like:

```
n, shp0 = a.shape[0]
new_shape = np.product(a.shape[1:])
a.reshape((n, new_shape), 'F')
```

This seems like it _might_ work. But I'm not sure.

**Comment by kyleam** [comment]
#516 and #521 should fix this. Closing.
