### ISSUE TITLE
Implement more distributions

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#515]
There are several distributions that ought to be available in PyMC 3 that currently are not. Here is a partial list; feel free to add to the list.
- half-Cauchy
- Weibull
- Pareto
- Chi-squared
- inverse-gamma
- hypergeometric

**Comment by twiecki** [comment]
- half-Normal
- Inverse Gaussian

**Comment by fonnesbeck** [comment]
Half-Cauchy and Weibull [have been added](https://github.com/pymc-devs/pymc/pull/517).

**Comment by twiecki** [comment]
As have been half-normal and wald https://github.com/pymc-devs/pymc/pull/519

**Comment by fonnesbeck** [comment]
Have also added Inverse gamma and Pareto #526. Will skip hypergeometric for now, as Theano does not have a combinations (or log-combinations) function.
