### ISSUE TITLE
cannot compute stats on a model that was loaded from a db

### ISSUE THREAD

**Issue by isofer** [pymc-devs/pymc3#52]
I cannot compute stats on a model that was loaded from a db although the model was loaded successfully.

Here is the code I used:
# creating MCMC model

import pymc as pm
x = pm.Normal('x',0,1)
mc = pm.MCMC([x],db='pickle', dbname='testing.db')
# sample

mc.sample(1000)
# print stats (no problem here)

print mc.stats()
# close the db

mc.db.close()
# now, let's load the db

db = pm.database.pickle.load('testing.db')
# create a new model

x = pm.Normal('x',0,1)
mc2 = pm.MCMC([x], db=db)
# check that the trace was loaded

print len(mc2.trace('x')[:])
# try to compute stats (which fails)

print mc2.stats()

here is the output that I got:

In [31]: import pymc as pm

In [32]: x = pm.Normal('x',0,1)

In [33]: mc = pm.MCMC([x],db='pickle', dbname='testing.db')

In [34]: mc.sample(1000)
Sampling: 100% [00000000000000000000000000000000000000000000000000000000000000000000000000000000000000] Iterations: 1000

In [35]: print mc.stats()
{'x': {'95% HPD interval': array([-1.88467957,  1.94281242]), 'n': 1000, 'quantiles': {2.5: -1.8828947855723701, 25: -0.68774516402745267, 50: -0.049887820880991689, 75: 0.665653263476219, 97.5: 1.9941128356195819}, 'standard deviation': 0.99104350597342195, 'mc error': 0.032035926857117064, 'mean': -0.030453765602493965}}

In [36]: mc.db.close()

In [37]: db = pm.database.pickle.load('testing.db')

In [38]: x = pm.Normal('x',0,1)

In [39]: mc2 = pm.MCMC([x], db=db)

In [40]: print len(mc2.trace('x')[:])
1000

In [41]: print mc2.stats()
Could not generate output statistics for x
{'x': None}

**Comment by isofer** [comment]
I just pulled pymc's latest version and now I get the following error:

In [20]: print mc2.stats()

AttributeError                            Traceback (most recent call last)

/Users/imrisofer/Documents/Projects/Schizo/PySchizo/<ipython console> in <module>()

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/pymc/Model.pyc in stats(self, variables, alpha, start, batches, chain)
    328         for variable in variables:
    329             # Plot object

--> 330             stat_dict[variable.**name**] = variable.trace.stats(alpha=alpha, start=start, batches=batches, chain=chain)
    331 
    332         return stat_dict

AttributeError: 'bool' object has no attribute 'stats'

**Comment by fonnesbeck** [comment]
This should be fixed in fa016d9dcf73e38889ca9ef6131675a2498b4f50 (your sample code runs, at any rate).

**Comment by isofer** [comment]
Hi Chris,
thank you for your help,
I think the problem may lie somewhere else.

firstly, I have access to the trace without the need of additional sampling

<pre>
In [123]: x = pm.Normal('x',0,1)

In [124]: mc = pm.MCMC([x],db='pickle', dbname='testing.db')

In [125]: #sample

In [126]: mc.sample(1000)
Sampling: 100% [0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000] Iterations: 1000

In [127]: #print stats (no problem here)

In [128]: print mc.stats()
{'x': {'95% HPD interval': array([-1.85325122,  1.91745091]), 'n': 1000, 'quantiles': {2.5: -1.9071128440215546, 25: -0.65506852296072782, 50: 0.053495177065224928, 75: 0.69540954027424606, 97.5: 1.9109705173069154}, 'standard deviation': 0.98238495187579189, 'mc error': 0.031908042184271485, 'mean': 0.031851384470447268}}

In [129]: #close the db

In [130]: mc.db.close()

In [131]: 

In [132]: #now, let's load the db

In [133]: db = pm.database.pickle.load('testing.db')

In [134]: #create a new model

In [135]: x = pm.Normal('x',0,1)

In [136]: mc2 = pm.MCMC([x], db=db)

In [137]: #check that the trace was loaded

In [138]: print mc2.trace('x')[:10]
[-1.66950803 -0.27798703 -0.79516555 -1.70746994 -1.12934057  1.05163419
 -0.85983377  0.95395848  0.3316708   1.32121151]
</pre>


secondly, I think there is a problem in the stats func.
here you can see how two different chains return the same statistics:

<pre>
In [139]: y = pm.Normal('y',0,1)

In [140]: m  = pm.MCMC([y])

In [141]: m.sample(1000)
Sampling: 100% [0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000] Iterations: 1000

In [142]: m.sample(1000)
Sampling: 100% [0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000] Iterations: 1000

In [143]: print m.stats(chain=-1)
{'y': {'95% HPD interval': array([-1.93863213,  1.97641809]), 'n': 1000, 'quantiles': {2.5: -2.009967607541058, 25: -0.68500599604475521, 50: 0.025369238223247794, 75: 0.62598590884186689, 97.5: 1.9545801802513938}, 'standard deviation': 1.0040483302549212, 'mc error': 0.029015479659518662, 'mean': -0.0096814291893063276}}

In [144]: print m.stats(chain=-2)
{'y': {'95% HPD interval': array([-1.93863213,  1.97641809]), 'n': 1000, 'quantiles': {2.5: -2.009967607541058, 25: -0.68500599604475521, 50: 0.025369238223247794, 75: 0.62598590884186689, 97.5: 1.9545801802513938}, 'standard deviation': 1.0040483302549212, 'mc error': 0.029015479659518662, 'mean': -0.0096814291893063276}}

</pre>


I checked the traces and it seems that these stats belong to the last chain.

**Comment by fonnesbeck** [comment]
Yeah, I deleted my original response. Have a look at the fix I submitted just now and see if it still does not work.

**Comment by isofer** [comment]
working great now,
thanks.
