### ISSUE TITLE
Blowflies Example

### ISSUE THREAD

**Issue by akloster** [pymc-devs/pymc3#525]
I was trying to implement the blowflies example from this url:
http://elec.physics.otago.ac.nz/w/images/b/b7/ELEC404_NicolsKupio.pdf

Basically blowflies are kept in a container, with a constant food supply, and their number is counted every two days. The counts exhibit cycles, and a model is proposed to explain this behavior.

The model would predict the population dynamics from just the initial population and two other parameters.

The problem I have with it is how to compute the population counts over time in theano. The only way I see would be to add variables dynamically in a loop, each depending on the prior generation.

I would suggest this as an example for the pymc3 collection, if it is possible.

**Comment by twiecki** [comment]
A PR for this would be great but I don't think this warrants an open issue as it's pretty specific. Certainly do ask on stackoverflow or the theano list on how to do this though.
