### ISSUE TITLE
Multivariate priors in PyMC?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc3#532]
Sorry if this isn't the wrong place to ask. I understand this forum is for dev, and not for Q&A, but I was wondering if it is possible at this moment in PyMC to define custom multi-variate priors in PyMC.

For example, say I want to define `p(a,b)∝(a+b)^(−5/2)` in PyMC where `a` and `b` are parameters for a Beta distribution:

``` python

# ....
# Code for the prior p(a,b)∝(a+b)^(−5/2) on a and b
# ....
theta   = pm.Beta("prior", alpha=a, beta=b)

# Binomials that share a common prior
bins = dict()
for i in xrange(N_cities):
    bins[i] = pm.Binomial('bin_{}'.format(i), p=theta, n=N_trials[i],  
                          value=N_yes[i], observed=True)
```

I have seen in some forum the ideas of defining your own stochastic, so I thought I could try:

```
import math
@pm.stochastic()
def custom_stochastic(a,b):
    return math.pow(a+b, -5.2)
```

but I don't know how to plug that in into alpha and beta definitions for `pm.Beta` above.

Note, I have a question also in SO is here: http://stackoverflow.com/questions/23198247/custom-priors-in-pymc

**Comment by jsalvatier** [comment]
I've responded in SO.

**Comment by amelio-vazquez-reina** [comment]
Thanks a lot @jsalvatier. I left you a comment and updated the OP in SO.

**Comment by amelio-vazquez-reina** [comment]
Sorry to be going back and forth John @jsalvatier. I left you a comment in SO. The only question left is how to get the prior on the individual variables from the **multivariate** prior.

**Comment by aloctavodia** [comment]
I'm not sure this is the right place to ask, but I have a related question posted on SO. http://stackoverflow.com/questions/24709627/how-to-define-a-custom-prior-in-pymc3. Thanks in advance.
