### ISSUE TITLE
Proposal: argument check when creating a Node 

### ISSUE THREAD

**Issue by isofer** [pymc-devs/pymc3#55]
I spent an hour today trying to understand why my simple linear model does not converge to the true values.

<pre>
#create data for a simple linear model
k = 4
n = 100
sigma = 0.3;
#create beta
true_beta = np.array([1, 0.5, -2, 1.7])
#create x martix
x = np.random.normal(0,1,size= (n,k))
#data = x*beta + noise
data = dot(x,true_beta) + np.random.randn(n)*sigma

#create linear model
beta = pm.Normal('beta', 0, 100, size=k)
xbeta = pm.Lambda('xbeta', lambda x=x,beta=beta:dot(x,beta))
tau = pm.Uniform('tau', 0,1000, value=0.2)
y = pm.Normal(xbeta, tau, observed=True,value=data)  ##!!!!!!!## my bug is here

#MCMC
mc = pm.MCMC([xbeta, tau, y, beta])
mc.sample(10000,5000)
</pre>

the model runs, and even converges, but not to the true values. the reason is that the first argument that was passed to pm.Normal when the y node was created is xbeta and not the node's name.

I think it would be extermly helpful to add argument checking when a node is initialize to prevent users from creating an incorrect model.

**Comment by fonnesbeck** [comment]
I find it extremely useful to generate a DAG for my model before I run it:

```
from pymc import graph
graph.dag(my_model)
```

This will show visually if there are any orphan nodes in your model.

**Comment by apatil** [comment]
Why not check the name argument. See commit f733d06bd9aabc4a713daa9c036098841819f673.
