### ISSUE TITLE
Math rendering in the docs

### ISSUE THREAD

**Issue by jseabold** [pymc-devs/pymc3#550]
It doesn't look like the equations are being correctly rendered in the docs or is this just me? E.g.,

https://pymc-devs.github.io/pymc/distributions.html#pymc.distributions.normal_like

I can't figure out how you build the docs locally so I haven't tried it, but I think you need a blank line after the `.. math::` statements in the docstrings and it needs to line up with the `m` in math. Maybe also an issue in math in the `note` directive. I'm not positive though.

https://github.com/pymc-devs/pymc/blob/2.3/pymc/distributions.py#L1992
http://sphinx-doc.org/latest/ext/math.html#directive-math

**Comment by fonnesbeck** [comment]
Its getting rendered correctly here, I believe:

![normal](http://d.pr/i/odHT+)

Is this not what you are expecting?

**Comment by jseabold** [comment]
Ah, ok. Must be a local issue. The mathjax isn't rendering it for me.

**Comment by jseabold** [comment]
Looking in the console in chrome

```
[blocked] The page at 'https://pymc-devs.github.io/pymc/distributions.html#pymc.distributions.normal_like' was loaded over HTTPS, but ran insecure content from 'http://mathjax.connectmv.com/MathJax.js?config=default': this content should also be loaded over HTTPS.
```

**Comment by fonnesbeck** [comment]
I did find a couple small errors in some inline math, so thanks.

**Comment by jseabold** [comment]
FWIW http://www.mathjax.org/resources/faqs/#problem-https

**Comment by fonnesbeck** [comment]
Cool, I've added this to the 2.3 branch. Thanks.

**Comment by jseabold** [comment]
Still seeing this. Do the changes need to get pushed to the `gh-pages` branch?

**Comment by twiecki** [comment]
Also seeing this.

**Comment by fonnesbeck** [comment]
I can't reproduce this on Safari, but Chrome seems to have problems.

**Comment by twiecki** [comment]
@fonnesbeck It's possible that Safari still has mathjax cached.

**Comment by fonnesbeck** [comment]
I'm not able to rebuild the 2.3 docs at present. No doubt Sphinx has changed since last I tried this. This will take some time, unfortunately.

**Comment by fonnesbeck** [comment]
OK, give it a spin now.

**Comment by twiecki** [comment]
Yep, that fixed it. I like your concept of "This will take some time" ;).

**Comment by fonnesbeck** [comment]
It was a vague prior.

**Comment by twiecki** [comment]
:clap:
