### ISSUE TITLE
`forestplot` bug

### ISSUE THREAD

**Issue by darribas** [pymc-devs/pymc3#551]
I think there is a bug somewhere in the `forestplot` method when `quartiles=False`.

I am following @fonnesbeck excellent [example with the radon data](https://github.com/fonnesbeck/multilevel_modeling). Say, for the case with varying intercepts, which is the first that uses the `forestplot`, I'm attaching the plots I get when I run the same command, only changing the parameter `quartiles`. That is:

`forestplot(varying_intercept_samples, vars=['a'])`

![with](https://cloud.githubusercontent.com/assets/417363/3258727/63134f94-f23c-11e3-9a0a-4ac33390df42.png)

 and: 

`forestplot(varying_intercept_samples, vars=['a'], quartiles=False)`

![without](https://cloud.githubusercontent.com/assets/417363/3258734/7b7d2d5c-f23c-11e3-854c-724b021720ef.png)

It could very well be I'm missing something in how the plots are supposed to be (I'm still getting my head around them), but I would think the dots for the medians should be placed on the same locations under both options (`quartiles` either True or False). If not, a clarification would help me a lot to understand them. Thank you very much.

**Comment by fonnesbeck** [comment]
Thats a bug. Thanks for reporting.

**Comment by fonnesbeck** [comment]
Fixed in master. Please test.

**Comment by darribas** [comment]
Beautiful! I 'pip install git+https://github.com/pymc-devs/pymc' and it works as I'd expect now. Thanks!
