### ISSUE TITLE
revert_to_max gives error when used with MAP

### ISSUE THREAD

**Issue by raiShashank** [pymc-devs/pymc3#560]
I have a simple model with the following stochastics:

```
    lam = pm.Uniform('lam', lower=0.0, upper=5, doc='lam')
    parameters = pm.Dirichlet('parameters',[1,1,1,1], doc='parameters')
    rv is a list of multinomial stochastic variables
```

I run MAP on it

```
   m = pm.MAP([lam, parameters, rv])
   m.fit(method='fmin_powell', verbose=1)
   print "Max log probability = ", m.logp_at_max
   print parameters[0].value, parameters[1].value, parameters[2].value, lam.value
   parameters.value = [0.1152,  0.3794, 0.1951]  
   lam.value = 0.1998
   print "After changing"
   print parameters[0].value, parameters[1].value, parameters[2].value, lam.value
   m.revert_to_max()
   print "After reverting"
   print parameters[0].value, parameters[1].value, parameters[2].value, lam.value
```

I get the following error : 

```
   File "/usr/local/lib/python2.7/dist-packages/pymc-2.3.2-py2.7-linux- i686.egg/pymc/NormalApproximation.py", line 486, in revert_to_max
self._set_stochastics([self.mu[s] for s in self.stochastics])

   File "/usr/local/lib/python2.7/dist-packages/pymc-2.3.2-py2.7-linux-i686.egg/pymc/NormalApproximation.py", line 58, in __getitem__
tot_len += self.owner.stochastic_len[p]
```

**I am using pymc 2.3.2 on ubuntu 12.04**

I modified the line 486 in NormalApproximation.py to 

```
  self._set_stochastics(self.mu[self.stochastics])
```

and it's working fine now, i.e. it reverts the stochastic variables back to their values after fitting. Could this be a simple bug and that's all that needs to change (in which case I thought I'd bring it to your attention), or am I missing something? Thanks for any help!

**Comment by fonnesbeck** [comment]
Thanks for the report. What was the actual exception? A TypeError, or something else?

**Comment by raiShashank** [comment]
I have already written the error I got. I didn't dig deep into the error, instead I got this link https://github.com/pymc-devs/pymc/issues/109 
and followed similar steps, and it worked.
See if that answers your query, or maybe I didn't understand your question (in this case please elaborate a little)

**Comment by fonnesbeck** [comment]
OK, so the current code (in 2.3.3) works for you, then? (i.e. the bug you had was fixed?)

**Comment by raiShashank** [comment]
Yes, after I modified the line 486 in NormalApproximation.py in function **revert_to_max** to

```
   self._set_stochastics(self.mu[self.stochastics])
```

from

```
   self._set_stochastics([self.mu[s] for s in self.stochastics])
```

it gave the expected result. And I am using 2.3.2. I just wanted to make sure if it is done or I am missing something.

**Comment by fonnesbeck** [comment]
Ok, then it's not fixed in the current release. What sort of exception did you receive? You did not report it in your original issue (you only gave part of the error message). Since I can't replicate this myself, I need a full error message.

**Comment by raiShashank** [comment]
**It was a KeyError**

```
File "/home/shashank/local/lib/python2.7/site-packages/pymc/NormalApproximation.py", line 486, in revert_to_max
self._set_stochastics([self.mu[s] for s in self.stochastics])

File "/home/shashank/local/lib/python2.7/site-packages/pymc/NormalApproximation.py", line 58, in __getitem__
tot_len += self.owner.stochastic_len[p]
```

KeyError: 0.46315179456859334

**Comment by fonnesbeck** [comment]
Should be addressed in the current 2.3 branch. Please test.

**Comment by raiShashank** [comment]
It is working now

**Comment by raiShashank** [comment]
**MAP.revert_to_max() is not working now**.  I provide my code below

```
m = pm.MAP(model)
for i in xrange(2):
print "B4 using "
    for j in model[:-1]:
        print j.value,
    print

    m.fit(method='fmin_powell')
    print "After using "
    print "Log Probability of model = ", m.logp     #prints log probability of model
    for j in model[:-1]:
        print j.value,
    print
    [j.random() for j in model[:-1]]
m.revert_to_max()
print "After reverting"
for j in model[:-1]:
    print j.value,
print
```

**It produces the following output:**

```
 B4 using 
 1.23672148829 0.820115008992 0.271956851004
  After using 
  Log Probability of model =  -1337.14722568
  2.62066389983 0.270432585863 0.9999999715
  B4 using 
  4.57095481725 0.222157464959 0.710940574112
  After using 
  Log Probability of model =  -1338.53399244
  1.30481898254 0.245951240798 0.999996336743
  After reverting
  1.30481898254 0.245951240798 0.999996336743
```

Quite clearly, since -1337.14 > -1338.53, it should have reverted but it does not

**Comment by fonnesbeck** [comment]
Are you sure you are using the current 2.3 branch? I cannot replicate with the example models:

```
In [2]: import pymc as pm

In [3]: from pymc.examples import gelman_bioassay
M = pm.MAP(gelman_bioassay)
M.fit()

In [4]: M.alpha.value
Out[4]: array(0.6523204513825168)

In [5]: M.alpha.random()
Out[5]: array(-3.094933282025095)

In [6]: M.alpha.value
Out[6]: array(-3.094933282025095)

In [7]: M.revert_to_max()

In [8]: M.alpha.value
Out[8]: array(0.6523204513825168)
```

**Comment by raiShashank** [comment]
Yes, I am using pymc 2.3.3 with all the changes made above (as you did to fix the earlier issue).
What I want is perform at least 2 (actually I perform 10) random restarts and then use MAP.revert_to_max() to revert to the best value found so far. I do this to avoid the case when MAP is caught in some local maxima.

But what I think is it remembers the previous fitting value, which should not have been the case

**Comment by fonnesbeck** [comment]
Can you post a full script (here or elsewhere) that I can use to help debug the issue, since I cannot replicate it?

**Comment by raiShashank** [comment]
Ok it seems that MAP.revert_to_max() simply reverts to previous fitted values i.e. say after running `MAP.fit()` ,I somehow change the values of stochastic variables, now if I run MAP.revert_to_max(), the values will be reset to the previous fitted values. 
**Isn't there any way by which I can revert back to the best value found so far?**
I run MAP.fit() starting from let's say 10 different random starting points, and then want to set the values of variables to the values at which the MAP.logp was maximum
**Why am I doing this?**
There is no guarantee that MAP will report the global maxima. It can as well report the local  maxima and if I start from the local maxima, it is possible that the model mixes poorly. By doing this, I believe that this scenario becomes less likely.
If you have some better approach, I will be happy to know of.

**Comment by fonnesbeck** [comment]
No, MAP currently only retains the last fitted value, as you have discovered. It sounds like you are searching for a good MCMC starting value? At present, you would just have to write a function that keeps track of the best value in a series of fits. But, if you come up with something good, we could probably add it to PyMC as a utility function.

**Comment by raiShashank** [comment]
This did the job for me.

```
def max_posterior(model, iterations = 10, method='fmin', iterlim=1000, tol=0.0001, verbose=1):
"""
    model : A collection (eg a list) of stochastic variables
    iterations : Number of random-restarts that you want

    Rest all parameters are arguments to MAP.fit()

    This function performs random restarts equal to 'iterations' and fits the stochastic variables to 
    the values which attained maximum logp in those iterations
"""
stochastic = []
simple = []
for j in model:
    try:
        j.random()
        if j.observed == False:
            stochastic.append(j)
        else:
            simple.append(j)
    except AttributeError:
        simple.append(j)

m = pm.MAP(model)
best_values = []
maxm = -np.inf
for j in stochastic:
    best_values.append(0)

for i in xrange(iterations):
    m.fit(method=method, verbose=verbose, iterlim=iterlim, tol=tol)
    if m.logp > maxm:
        maxm = m.logp
        for j in xrange(len(stochastic)):
            best_values[j] = stochastic[j].value
    for j in xrange(len(stochastic)):
        stochastic[j].random()

for j in xrange(len(stochastic)):
    stochastic[j].value = best_values[j]
```

The values are reflected back in the calling function as well
