### ISSUE TITLE
Binstar build

### ISSUE THREAD

**Issue by mrocklin** [pymc-devs/pymc3#567]
While at SciPy someone mentioned to me that someone in this project was interested in using binstar-build to regularly build `pymc3`.  I'm happy to help a bit with this if folks are interested.

**Comment by twiecki** [comment]
Thanks for offering @mrocklin. I think a more pressing issue right now is building pymc2 though https://github.com/pymc-devs/pymc/issues/556. Would you be willing to help with that?

**Comment by twiecki** [comment]
Closing in favor of #556.
