### ISSUE TITLE
Matplot.gof_plot error message

### ISSUE THREAD

**Issue by neuronphysics** [pymc-devs/pymc3#568]
I am a newbie in pymc and I was trying to test pymc examples from DisasterModelGOF , but when I run it in ipython notebook I get the following error message:

---

ValueError                                Traceback (most recent call last)
<ipython-input-40-2e1d548d267a> in <module>()
     58     # Plot GOF graphics
     59     pm.Matplot.discrepancy_plot(D, 'D')
---> 60     pm.Matplot.gof_plot(disasters_sim, disasters_array,'disasters' )

/vol/anaconda/lib/python2.7/site-packages/pymc/Matplot.pyc in gof_plot(simdata, trueval, name, bins, format, suffix, path, fontmap, verbose)
    850         bins = bins
    851     else:
--> 852         raise ValueError('Invalid bins argument in gof_plot')
    853 
    854     # Generate histogram

ValueError: Invalid bins argument in gof_plot

and even if I give to the bins option a quantity it raises another error message. What is the reason of getting error?

**Comment by kyleam** [comment]
When I run `disaster_model_gof.py`, it fails, but not with the same error. Can you check if [these changes](https://github.com/pymc-devs/pymc/tree/pymc2/gof_plot-trace-check) fix the error on your side?

**Comment by kyleam** [comment]
@twiecki, does disaster_model_gof.py on the 2.3 branch fail for you (and if so, does 7b22533 fix the issue)?

**Comment by twiecki** [comment]
@kyleam oops, I thought you already merged the fix. Yes, 2.3 produces the error and your fix works. Can you merge that into the v2.3 branch?

**Comment by kyleam** [comment]
Will do. Thanks for the confirmation.
