### ISSUE TITLE
Issue with Categorical Stochastic Variable (PyMC 2.3)

### ISSUE THREAD

**Issue by mertterzihan** [pymc-devs/pymc3#571]
Categorical Stochastic Variable proposes values that have negative numbers which cause log probability of the proposed step to be zero, thus proposed step to be rejected. Below is one of the steps that I've come up when I run my model:

DiscreteMetropolis_z_0 getting initial logp.
    z_0: logp accessed.
    z_0: Returning log-probability  -2.33176411698
    DiscreteMetropolis_z_0 Current log-likelihood plus current log-probability -3.76869633667
DiscreteMetropolis_z_0 proposing.
    z_0: value accessed.
    z_0: value accessed.
    z_0: value set to  [ 1.  0. -1.  0.]
    z_0: logp accessed.
    z_0: value accessed.
    z_0: Returning log-probability  -1.79769313486e+308
DiscreteMetropolis_z_0 rejecting due to ZeroProbability.
DiscreteMetropolis_z_0 returning.
Step method Metropolis_phi_0 stepping

'z_0' is a Categorical variable, which cannot take any value below 0. If the size of the Categorical variable is big enough, it is being rejected in every step.

**Comment by jsalvatier** [comment]
Would you post your model and sampler?

**Comment by mertterzihan** [comment]
Sure, my model is a simple LDA model as follows:

``` python
from pymc import Dirichlet, Categorical, Deterministic, Lambda, Stochastic, Container, Model
import numpy as np
from numpy.random import dirichlet

beta = 0.05
total_vocab = 78 # total items in the vocabulary
# symmetric prior parameter for word-topic distributions
beta_vector = [beta for t in xrange(total_vocab+1)] 
total_topics = 10

# Symmetric Dirichlet prior for topic-word distributions
phi = [Dirichlet("phi_%s" % k, 
                 theta=beta_vector,
                 value=dirichlet(beta_vector)[:-1]) for k in range(total_topics)]

local_docs = list()
# Given the data as a list of strings (lines), structure it in such a way that it can be used by the below model
for doc_number,line in enumerate(data):
    document_data = line.split(',')
    words = document_data[1].split(' ')
    words = map(int, words)
    local_docs.append((int(document_data[0]), words))

# The symmetric prior parameter for document-topic distribution
alpha = 50.0/total_topics
alpha_vector = [alpha for k in xrange(total_topics)]
# The Dirichlet distribution for document-topic distribution, theta
theta = [Dirichlet('theta_%i' % local_docs[i][0], 
                   theta=alpha_vector,
                   value=dirichlet(alpha_vector)[:-1]) for i in xrange(len(local_docs))]
# The topic assignments for each word
z = [Categorical('z_' + str(doc[0]), 
                 p=theta[n], 
                 size=len(doc[1]), 
                 verbose=0) for n, doc in enumerate(local_docs)]
# Modeling the observations
x = [Categorical('x_' + str(doc[0]), 
                 p=Lambda('lambda_%i' % doc[0], 
                          lambda z=z, 
                          phi=phi: [phi[z[n][order]]/np.sum(phi[z[n][order]]) for order,word in enumerate(doc[1])]), 
                 value=doc[1], 
                 observed=True) for n, doc in enumerate(local_docs)]
```

I'm using regular MCMC sampler, currently without any tuning. 

Additionally, I found the reason: Size of each variable z is minimum 100 or 200. DiscreteMetropolis step method proposes in each iteration a new value for z which has a negative value due to the size of the variable. Thus, every proposal is being rejected. 

One way to prevent this is to implement a custom step method class. In this case, I have implemented a hybrid random walk where a new value is proposed from a random walk or a uniform distribution. The overridden propose distribution of the step method class also makes sure that none of the values causes such issue.

**Comment by fonnesbeck** [comment]
You can pass an argument to `DiscreteMetropolis` that restricts proposals to positive values. Try the following before sampling (here, `M` is your MCMC instance):

```
M.use_step_method(DiscreteMetropolis, M.z, positive=True)
```

Perhaps this should be the default, since most standard discrete variables are non-negative.

**Comment by fonnesbeck** [comment]
Try running the current 2.3 branch. I have flipped the flag to be positive by default.

**Comment by fonnesbeck** [comment]
If this is still an issue, please reopen.
