### ISSUE TITLE
question from a JAGS convert

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc3#572]
I have used JAGS for a while and my question relates to the general approach of composing models. In JAGS you can write one model specification of the joint distribution, in this general form:

`my model = P(param|data) = P(data|param)P(param)`

Often it is important to see how well your model can make good inferences about a parameter where you know it's true value (parameter recovery). To do this you need to generate data from the model with a known parameter value, that is, draw samples from `P(data|param)`. You then need do the inference by drawing samples from `P(param|data)`. The nice thing about JAGS models is that you can use the one single model and it makes MCMC samples available for any of the unobserved nodes. So, one model, used for two purposes based on what observed data you pass to it.

My question is, can you do this in PyMC? 

As far as I understand, you can't, because the PyMC model specification seems to explicitly define which variables are observed, and so they are basically models of specific conditional distributions, not a model of the whole joint distribution. This is not necessarily a big deal because the only difference between the two models is explicitly defining some variables as observed, but for big models, having to copy/paste/modify the models seems inelegant and error prone.

I'm hoping that I am wrong, it's entirely possible that I've misread the documentation and overlooked something. How do I go about building ONE model which can then be used to evaluate whatever conditional distribution I want?

By way of example, what I want to do is just create one model like this and then be able to pass it whatever observations I want, whether that me of `mu` or of `data`

```
def my_joint():
    #prior
    mu = pymc.Uniform("mu", lower=-10, upper=10)
    # likelihood function
    data = pymc.Normal("m", mu=mu, tau=tau)
    return locals()
```

but it seems as if I have to instead write two models, one for data generation...

```
def generate():
    #prior
    mu = pymc.Uniform("mu", lower=-10, upper=10, value=true_param, observed=True)
    # likelihood function
    data = pymc.Normal("m", mu=mu, tau=tau)
    return locals()
```

and this for inference...

```
def inference():
    #prior
    mu = pymc.Uniform("mu", lower=-10, upper=10)
    # likelihood function
    data = pymc.Normal("m", mu=mu, tau=tau, value=generated_data, observed=True)
    return locals()
```

**Comment by fonnesbeck** [comment]
You are essentially correct, because PyMC is object-oriented you are giving each node its attributes when you instantiate it. One way to avoid having to write two models would be something like the following:

```
def generate_model(values={'mu': true_param, 'm': None}):

    #prior
    mu = pymc.Uniform("mu", lower=-10, upper=10, value=values['mu'], 
        observed=(values['mu'] is not None))

    # likelihood function
    m = pymc.Normal("m", mu=mu, tau=tau, value=values['m'], 
        observed=(values['m'] is not None))

    return locals()
```

Thus, if you decided to provide data instead of `mu`, it would estimate `mu` instead.

**Comment by drbenvincent** [comment]
Superb. Thanks for the quick reply. 

This is an excellent and much needed project. I'm recent convert to Python (from Matlab) but as and when I get up to speed, then I'll attempt to contribute examples.

**Comment by drbenvincent** [comment]
Fully worked through example here http://nbviewer.ipython.org/github/drbenvincent/learning-pymc/blob/master/BayesEquation.ipynb 

Feel free to ignore / use / link to.
