### ISSUE TITLE
Solving stochastic optimization problems?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc3#581]
Can PyMC be used to solve stochastic optimization problems? For example, solving LP with distributions on coefficients and/or constraints. If so, how would one go about solving them?

I posted an example [here](http://stats.stackexchange.com/questions/105557/stochastic-programming-e-g-lp-with-mcmc) which I include below:

![screen shot 2014-07-29 at 4 52 41 pm](https://cloud.githubusercontent.com/assets/1993919/3741721/515989d0-1762-11e4-93dd-adb59aadf296.png)
![screen shot 2014-07-29 at 4 54 43 pm](https://cloud.githubusercontent.com/assets/1993919/3741739/9a8dbea0-1762-11e4-987a-f8693366b9f7.png)

I have a background in MRFs and graphical models in general, so I believe I can use PyMC `potentials` to solve the problem. Are there any known PyMC examples that use `potentials` to create a graphical problem similar to the one described above?

**Comment by jsalvatier** [comment]
Sure, you could use it for that, probably even some of standard algorithms,
but if you want it to work well, you'd probably want to write your own
algorithm.

**Comment by amelio-vazquez-reina** [comment]
Thanks @jsalvatier  My guess is that I could define this model with `potentials`. Are you aware of any examples that I could follow that are somewhat close to that I posted?

**Comment by jsalvatier** [comment]
Yes, I think the best way to implement constraints is going to be in the
potential. I can't think of any examples right now, but if you give it a
shot and can't figure out how to do it right, I'd be happy to help you.

**Comment by amelio-vazquez-reina** [comment]
Thanks a lot, @jsalvatier. Abraham Flaxman just answered [the original question in cross-validated](http://stats.stackexchange.com/questions/105557/stochastic-programming-e-g-lp-with-mcmc/110063#110063). His solution does not use `potentials` and instead relies on an external LP solver, which is very interesting.

This makes me wonder:  Was I wrong about using potentials in first place? Before seeing Abraham's answer I thought I would do the following: define two potentials: one for the cost function and one for the constraints. The potential for the constraints would output `p=0` (constraints not satisfied) or `p=1` (constraints satisfied), while the potential for the cost function would simply return `c1*x1 + c2*x2 + ... + cn*Xn`. 

I thought I would then let MCMC do the heavy lifting, i.e. sample from the full joint distribution defined by the potentials. PyMC would not know that this is a stochastic LP problem, but I would imagine it would learn to sample from around the optimal area.

Does the idea of using potentials the way I mention above really make sense? Is Abraham's solution correct as well?  If so, what is the difference between both approaches?

It looks to me that Abraham's approach is quite powerful since it can be used to address any type of optimization problem!

**Comment by amelio-vazquez-reina** [comment]
FYI I tried combining Abraham's solution with a true solver ([cvxopt](http://cvxopt.org/)) with no luck. Installing `cvxopt` is easy (`pip install cvxopt` takes care of everything), and I know it works well:

``` python
import pymc as pm
from cvxopt import matrix, solvers

# Testing that cvxopt works
# Example from http://cvxopt.org/userguide/coneprog.html#linear-programming
c = matrix([-4., -5.])
G = matrix([[2., 1., -1., 0.], [1., 2., 0., -1.]])
h = matrix([3., 3., 0., 0.])
sol = solvers.lp(c, G, h)
# The solution sol['x'] is correct: (1,1)
```

but it doesn't when I wrap it in PyMC:

``` python
# Now we try with a stochastic problem:
c1 = pm.Normal('c1', mu=-4, tau=.5**-2)

@pm.deterministic
def x(c1=c1):
    c = matrix([c1, -5.])
    G = matrix([[2., 1., -1., 0.], [1., 2., 0., -1.]])
    h = matrix([3., 3., 0., 0.])
    sol = solvers.lp(c, G, h)
    solution = np.array(sol['x'],dtype=float).flatten()
    return solution

m = pm.MCMC(dict(c1=c1, x=x))
m.sample(20000, 10000, 10)
```

I get the following PyMC error:

```
<ipython-input-21-5ce2909be733> in x(c1)
     14 @pm.deterministic
     15 def x(c1=c1):
---> 16     c = matrix([c1, -5.])
     17     G = matrix([[2., 1., -1., 0.], [1., 2., 0., -1.]])
     18     h = matrix([3., 3., 0., 0.])

TypeError: invalid type in list
```

**Comment by amelio-vazquez-reina** [comment]
If anyone runs into this problem, the solution is [here](http://stackoverflow.com/a/25087484/283296):

``` python
@pm.deterministic
def my_lp_solver(c1=c1):
  c = matrix([float(c1), -5.])
  G = matrix([[2., 1., -1., 0.], [1., 2., 0., -1.]])
  h = matrix([3., 3., 0., 0.])
  sol = solvers.lp(c, G, h)
  solution = np.array(sol['x'],dtype=float).flatten()
  return solution

     pcost       dcost       gap    pres   dres   k/t
 0: -8.1223e+00 -1.8293e+01  4e+00  0e+00  7e-01  1e+00
 1: -8.8301e+00 -9.4605e+00  2e-01  1e-16  4e-02  3e-02
 2: -9.0229e+00 -9.0297e+00  2e-03  2e-16  5e-04  4e-04
 3: -9.0248e+00 -9.0248e+00  2e-05  3e-16  5e-06  4e-06
 4: -9.0248e+00 -9.0248e+00  2e-07  2e-16  5e-08  4e-08
Optimal solution found.
```

**Comment by amelio-vazquez-reina** [comment]
As I mentioned in the [original Cross-Validated thread](http://stats.stackexchange.com/questions/105557/stochastic-programming-e-g-lp-with-mcmc), after looking into this more carefully, I reached the following conclusion that I thought may be useful to share with others: Abraham's solution is useful for looking at the statistics of the **optimal solution under variations of model parameters**, but it **does not optimize the expected cost/utility** (with cost/utility defined by the objective function subject to constraints) given the uncertainty in the parameters of the formulation. 

Note that optimizing **expected cost/utility** (i.e. using the squared loss function) is common in stochastic programming. 

This is an important clarification. I wonder if MCMC (e.g. PyMC) can be used to solve the latter on a relatively general case.
