### ISSUE TITLE
Frequent ZeroProbability error using TruncatedNormal in pymc 2.3.3 but not 2.3.2 or 2.2

### ISSUE THREAD

**Issue by dmcnamee** [pymc-devs/pymc3#588]
``` python
import numpy as np
import pymc as pm
init = 0.5; minv = 0.; maxv = 1.
A = pm.Uniform('A', value=init, lower=minv, upper=maxv)
B = pm.TruncatedNormal('B', value=init, mu=A, tau=1., a=minv, b=maxv)
C = pm.Normal('C', value=np.random.normal(init,1,10), mu=B, tau=1., observed=True)
model = pm.MCMC(pm.Model([A, B, C]))
model.sample(1000)
```

nearly always throws the following error:

```
pymc.Node.ZeroProbability: Stochastic B's value is outside its support,
 or it forbids its parents' current values.
```

I believe this example is minimal since if I remove A or C it seems to work (at least, it works a lot more frequently). This only seems to occur in pymc v2.3.3.

**Comment by fonnesbeck** [comment]
Can you build PyMC from the current 2.3 branch? I can't replicate it using that.

**Comment by dmcnamee** [comment]
Cannot replicate error in current version (v2.3.4), works fine. Apologies for the trouble, thought I was up-to-date.

**Comment by fonnesbeck** [comment]
You are up to date in terms of release versions. This appears to be related to #589
