### ISSUE TITLE
eliminating special casing in __getitem__

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#6]
Currently when **getitem** gets a scalar value, it returns an Index deterministic, otherwise it returns a regular deterministic that indexes into the array. My understanding is that Index exists so that linear models can be special cased. I would like to find a way to eliminate the special casing since it's a bit inelegant. Could Index be made to handle non-scalars?

**Comment by apatil** [comment]
If you can think of any other way for a step method, say, to look at a model and figure out when a deterministic's value is an element of another variable, that would be fine too.

**Comment by jsalvatier** [comment]
Specifically a single element?

**Comment by apatil** [comment]
I guess it doesn't matter, as long as it's possible to figure out what slice is being taken.
