### ISSUE TITLE
hdf5 fails to create table when running on a large model

### ISSUE THREAD

**Issue by isofer** [pymc-devs/pymc3#60]
I'm not sure this is a pymc error, it could be an hdf5 error.
I'm getting it when I'm using MCMC  with hdf5 on large models.
(Is there any backend which is recommended for work on large models?)

<pre>
import pymc as pm
import numpy as np
n = 1500
a = np.empty(n, dtype=object)
for i in range(n):
    a[i] = pm.Normal('a%d' % i,0,1)

m = pm.MCMC(a, db='hdf5', dbname = 'test.db')
m.sample(100)

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/table.py:720: PerformanceWarning: table ``/chain3/PyMCsamples`` is exceeding the recommended maximum number of columns (512); be ready to see PyTables asking for *lots* of memory and possibly slow I/O
  PerformanceWarning )
HDF5-DIAG: Error detected in HDF5 (1.8.5-patch1) thread 0:
  #000: H5Ddeprec.c line 169 in H5Dcreate1(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 431 in H5D_create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1640 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1863 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: H5Gtraverse.c line 964 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 759 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1686 in H5L_link_cb(): unable to create object
    major: Object header
    minor: Unable to initialize object
  #007: H5O.c line 2976 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: H5Doh.c line 295 in H5O_dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #009: H5Dint.c line 1039 in H5D_create(): can't update the metadata cache
    major: Dataset
    minor: Unable to initialize object
  #010: H5Dint.c line 806 in H5D_update_oh_info(): unable to update datatype header message
    major: Dataset
    minor: Unable to initialize object
  #011: H5Omessage.c line 184 in H5O_msg_append_oh(): unable to create new message in header
    major: Attribute
    minor: Unable to insert object
  #012: H5Omessage.c line 224 in H5O_msg_append_real(): unable to create new message
    major: Object header
    minor: No space available for allocation
  #013: H5Omessage.c line 1925 in H5O_msg_alloc(): unable to allocate space for message
    major: Object header
    minor: Unable to initialize object
  #014: H5Oalloc.c line 1135 in H5O_alloc(): object header message is too large
    major: Object header
    minor: Unable to initialize object
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)

/Users/isofer/Projects/Schizo/PySchizo/<ipython console> in <module>()

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/pymc/MCMC.pyc in sample(self, iter, burn, thin, tune_interval, tune_throughout, save_interval, verbose, progress_bar)
    215 
    216         # Run sampler

--> 217         Sampler.sample(self, iter, length, verbose)
    218 
    219     def _loop(self):

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/pymc/Model.pyc in sample(self, iter, length, verbose)
    226         if length is None:
    227             length = iter
--> 228         self.db._initialize(self._funs_to_tally, length)
    229 
    230         # Put traces on objects

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/pymc/database/hdf5.pyc in _initialize(self, funs_to_tally, length)
    406             title='PyMC samples', \
    407             filters=self.filter,
--> 408             expectedrows=length)
    409 
    410         self._tables.append(table)

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/file.py in createTable(self, where, name, description, title, filters, expectedrows, chunkshape, byteorder, createparents)
    772                      description=description, title=title,
    773                      filters=filters, expectedrows=expectedrows,
--> 774                      chunkshape=chunkshape, byteorder=byteorder)
    775 
    776 

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/table.py in __init__(self, parentNode, name, description, title, filters, expectedrows, chunkshape, byteorder, _log)
    590 
    591         super(Table, self).__init__(parentNode, name, new, filters,
--> 592                                     byteorder, _log)
    593 
    594 

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/leaf.py in __init__(self, parentNode, name, new, filters, byteorder, _log)
    289         # is a lazy property that automatically handles their loading.

    290 
--> 291         super(Leaf, self).__init__(parentNode, name, _log)
    292 
    293 

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/node.py in __init__(self, parentNode, name, _log)
    294             #   Create or open the node and get its object ID.

    295             if new:
--> 296                 self._v_objectID = self._g_create()
    297             else:
    298                 self._v_objectID = self._g_open()

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/table.py in _g_create(self)
    745         # set because it is needed for setting attributes afterwards.

    746         self._v_objectID = self._createTable(
--> 747             self._v_new_title, self.filters.complib or '', obversion )
    748         self._v_recarray = None  # not useful anymore
    749         self._rabyteorder = None # not useful anymore

/Library/Frameworks/EPD64.framework/Versions/7.0/lib/python2.7/site-packages/tables/tableExtension.so in tables.tableExtension.Table._createTable (tables/tableExtension.c:2074)()

HDF5ExtError: Problems creating the table
</pre>

**Comment by fonnesbeck** [comment]
This is likely related to #41

**Comment by scopatz** [comment]
Yes, this is related to #41.  At the top `n=1500` whereas the limit is closer to `n=1000`
