### ISSUE TITLE
error when loading flib.pyd

### ISSUE THREAD

**Issue by xueliang** [pymc-devs/pymc3#61]
I am working in windows xp + python 2.7. 
the pymc packages is downloaded from github direclty.
https://github.com/downloads/pymc-devs/pymc/pymc-2.2alpha.win32-py2.7.exe
but I have a problem when run it.
It says:
" import flib
ImportError: DLL load failed: The specified module could not be found. "

After a check, I find that there are two dll file missing:
LIBGCC_S_SJLJ-1.DLL  LIBGFORTRAN-3.DLL

Could you please also add the two files in the packages ? Thank you very much.

**Comment by fonnesbeck** [comment]
Have you installed a gfortran compiler?

**Comment by xueliang** [comment]
I did not install gfortran since I do not use it at all.
could you rebuid it with static library? thanks

**Comment by fonnesbeck** [comment]
We will try and shoot for a static build next time, but I have no access to a Windows machine. If you want to extend PyMC (or Numpy for that matter) at all, a gfortran compiler will come in handy, so I recommend installing it.

**Comment by Mewit** [comment]
Hi there, I have the same problem except I'm running on Windows 7 64. Easy_install wouldn't work so I installed pymc using this file:
http://cloud.github.com/downloads/pymc-devs/pymc/pymc-2.2alpha.win-amd64-py2.7.exe

But whenever I try to import it, it can't find the flib module (or dll?)
I tried to install gfortran by installing MiniGW, but it doesn't seem to have helped, it still can't find flib. I'm sure there's something stupid I'm overlooking, but I can't figure out what it is... 
Thanks a lot,
Alex

**Comment by xueliang** [comment]
Hello Alex,
    You can find flib.dll in gfortran fold, and copy it to
python27/libs/site-packages/pymc, renamed the dll as flib.pyd. It would
work. Good luck

xueliang

On Sun, Jan 15, 2012 at 11:34 AM, Mewit <
reply@reply.github.com

**Comment by Mewit** [comment]
Hmm ok, there doesn't seem to be an flib.dll in the MinGW folder, does that mean I've installed gfortran wrong?

**Comment by fonnesbeck** [comment]
Any insight on this from Windows users would be welcome.

**Comment by Mewit** [comment]
Part of my problem was I had to put the MinGW bin in the path, but it still didn't work so I ended up replacing 64 bit python with 32 bit python, with which it seems to work. That was an option because I don't really need 64 bit python, for others that may not be the case.
Thanks,
Alex

**Comment by Nillie** [comment]
I seem to have the same problem... using windows and python 2.7. 
I installed MinGW with both c & fortran. 

This is what I get when I try and import pymc: 

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pymc\__init__.py", line 27, in <module>
    from .CommonDeterministics import *
  File "C:\Python27\lib\site-packages\pymc\CommonDeterministics.py", line 20, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element

  File "C:\Python27\lib\site-packages\pymc\utils.py", line 12, in <module>
    from . import flib
ImportError: DLL load failed: The specified procedure could not be found.
</pre>


I also got the same error after trying to install pymc from a package found here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/

Is there any way out? pymc sounds like a very good tool to check out :-(

**Comment by fonnesbeck** [comment]
Hi Millie,

Did you try Alex's solution -- installing with 32-bit Python? It appears that the binary you are installing is 32-bit. If you need 64-bit Python, I can post instructions for building it from source.

**Comment by Nillie** [comment]
Well, I actually tried with a 32-bit python first (on a 64-bit win), and then installed a 64-bit python (with the installer, not from source) and tried again. Do you think building it from source again will help?

**Comment by fonnesbeck** [comment]
It will guarantee that the libraries match your machine's architecture. Make sure that you have Numpy and Matplotlib installed (the minimum dependencies) and follow the instructions in the user's guide:

 http://pymc-devs.github.com/pymc/INSTALL.html#compiling-the-source-code

Let me know how that works out.

**Comment by Nillie** [comment]
Not so well... 
I'm getting errors. I'm assuming the 32-bit MinGW is at fault here, but I don't seem to be able to find a complete/installable 64-bit version for the compiler, and compiling a compiler seems like a bit of a drastic measure. If there's one you can recommend...

Here's a sample of the errors:

c:\users\sonsof\pymc/build/src.win-amd64-2.7/pymc/flibmodule.c:28972: undefined
reference to `_imp__PyString_FromString'
c:\users\sonsof\pymc/build/src.win-amd64-2.7/pymc/flibmodule.c:28972: undefined
reference to`_imp__PyObject_SetAttrString'
c:\users\sonsof\pymc/build/src.win-amd64-2.7/pymc/flibmodule.c:28980: undefined
reference to `_imp__PyDict_GetItemString'
c:\users\sonsof\pymc/build/src.win-amd64-2.7/pymc/flibmodule.c:28981: undefined
reference to`_imp__PyObject_SetAttrString'
c:\users\sonsof\pymc/build/src.win-amd64-2.7/pymc/flibmodule.c:28985: undefined
reference to `_imp__PyString_FromString'

**Comment by fonnesbeck** [comment]
I'm hoping some Windows users can chime in here, because I'm not familiar with the build issues there.

If, however, in the meantime you want to play with PyMC, you can try it on PythonAnywhere (http://www.pythonanywhere.com). PyMC is pre-installed.

**Comment by xueliang** [comment]
I use the package in 32bits windows, which is installed it with binary exe
file. The pyd file is from _FORTRAN_ . If some body need the pyd file,
please leave your mail here.

xueliang

On Mon, Feb 13, 2012 at 6:14 PM, Chris Fonnesbeck <
reply@reply.github.com

**Comment by hanru** [comment]
I'd like to churn this issue again. No matter whatever I tried, pymc complied from mingw is problematic; however, pymc complied by the gcc/gfortran within EPD seems OK. Details below.

My settings: Windows 7 x64, EPD 7.2-2, gcc 4.6.2 (mingw)

The problem is: pymc not load properly on Windows. After installing the pre-built binaries or compiling source per [tutorial](http://pymc-devs.github.com/pymc/INSTALL.html#windows), `import pymc` and I got the "**ImportError: DLL load failed: The specified procedure could not be found.**" error message. I also tried to copy libgcc_s_dw2-1.dll and libgfortran-3.dll from mingw/bin to site-packages/pymc, then got another error message "**ImportError: cannot import name PyMCObjects.**"

In contrast, pymc complied by the gcc/gfortran within EPD (in Scripts directory) has none of the above problems. I just run `pip install pymc` from a command line which in turn compiles pymc automatically (install pip first of course). The trick is, PATH environment variable should be set properly, EPD and EPD\Scripts must precede mingw\bin.

@fonnesbeck I'm a newbie to Python and even newer to pymc, cannot go any further. It seems to me that the easiest way to start use pymc on Windows is to compile it by the compiler within EPD, and the installation guide on Windows part is more or less error-prone. I hope the information above is useful for you to diagnose.

To other people come upon this issue: compile pymc using the gcc/gfortran within EPD, and problem solved!

**Comment by fonnesbeck** [comment]
OK, that's good to know. I can add some of these details to the user's guide for others' reference.

If you have a binary that you have built, I can add it to the downloads if you send it to me.

**Comment by fonnesbeck** [comment]
I have mentioned this alternative install strategy in the most recent [user's guide](http://pymc-devs.github.com/pymc/INSTALL.html#windows).

**Comment by hanru** [comment]
Thanks for you quick response. Binary sent.

**Comment by mimiWielki** [comment]
I'm a newbie to Python so I solve this problem in this way:
1) install gfortran-windows-20120518.exe
2) add system path to gfortran
3)copy "includes" folderf  from gfortran to python2.7
4) delete earliers  pymcs
5) install new pymc from source
