### ISSUE TITLE
Format for gelman_rubin raw input

### ISSUE THREAD

**Issue by jseabold** [pymc-devs/pymc3#611]
I think I've been computing my `gelman_rubin` statistics wrong. See image below. If you pass it raw data, it should be the different chains in rows _not_ in columns. Is this correct? Looking at the [documentation](https://pymc-devs.github.io/pymc/modelchecking.html#formal-methods), it looks to me like the chains are assumed to be in the columns. If you pass it data like this, then I think the GR stat is miscomputed. I.e., I assumed `B_over_n` to contain an `np.mean(x, 0)` rather than the `np.mean(x, 1)` in the code based on the documentation (and so on). Perhaps this is just a docs issue and should be cleared up? Or is this just my confusion? 

![gr_stat](https://cloud.githubusercontent.com/assets/296164/4547044/453fe11c-4e49-11e4-83f8-676351c69968.png)

**Comment by jseabold** [comment]
This is PyMC 2.3.4

**Comment by fonnesbeck** [comment]
I _think_ PyMC is doing the right thing, and perhaps the documentation could use a tweak. If using raw data, it expects an iterable containing traces, which may be an easier way of thinking of things instead of columns and rows. For example:

![screen shot](http://d.pr/i/RcAb+)

Does that seem right to you? If so, I will beef up the docstring.

**Comment by jseabold** [comment]
Yeah I think everything is right now that I know what's going on. I was just passing traces over the columns because the \theta_{\cdot,j} notation in the docs I linked to, which implied (I thought) that the columns should contain the trace j = {1,...,m} where m is the number of chains. Might want to switch the notation around in the online docs and add the bit about the iterable to the docstring to make it idiot-proof.
