### ISSUE TITLE
test() fails due to Theano as_op

### ISSUE THREAD

**Issue by esafak** [pymc-devs/pymc3#613]
The tail of my test() output is

```
ERROR: pymc.tests.test_examples.test_examples1('pymc.examples.disaster_model_arbitrary_determinisitc',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/emre/.local/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/emre/.local/lib/python3.3/site-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/home/emre/.local/lib/python3.3/site-packages/pymc/examples/disaster_model_arbitrary_determinisitc.py", line 27, in <module>
    @theano.compile.ops.as_op(itypes=[t.lscalar, t.dscalar, t.dscalar],otypes=[t.dvector])
AttributeError: 'module' object has no attribute 'as_op'

----------------------------------------------------------------------
Ran 280 tests in 1371.962s

FAILED (SKIP=2, errors=1)
<nose.result.TextTestResult run=280 errors=1 failures=0>
```

Theano 0.6 test() passes with only "known errors".

P.S. The test name, "pymc.examples.disaster_model_arbitrary_determinisitc" contains a typo.

**Comment by kyleam** [comment]
`as_op` was introduced after the 0.6 release of Theano (commit c5b999ed), so the Theano dependency in setup.py is no longer accurate.

**Comment by esafak** [comment]
Good enough for me; you can close this when you or someone has taken corrective action.

BTW, I opened this ticket after I faced an [undefined symbol error](http://stackoverflow.com/questions/26263989/import-pymc-fails-with-undefined-symbol-kmpc-begin) upon installing the stable version with pip.

**Comment by kyleam** [comment]
@twiecki Do you think we should go back to relying on the git version of Theano in setup.py (which, looking back at #389, was a bit of a hack), or prevent this example from running with the tests for the time being?

**Comment by twiecki** [comment]
@kyleam Hm, using theano master actually worked pretty well so I agree that that's the way to go. That way we can also anticipate any upcoming changes that make our code incompatible.

**Comment by kyleam** [comment]
OK, I'll bring back that setup then.

**Comment by twiecki** [comment]
Thanks!

**Comment by kyleam** [comment]
@esafak Thanks for reporting this (and the typo). Let me know if the pushed changes don't work for you. You'll have to remove any previous Theano versions first (see commit message).
