### ISSUE TITLE
pymc 2.3.3 fails to import due to undefined symbol __kmpc_begin in flib.so

### ISSUE THREAD

**Issue by esafak** [pymc-devs/pymc3#617]
pip says it installed succesfully, but when I try to import pymc I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emre/.local/lib/python2.7/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/home/emre/.local/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/home/emre/.local/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: /home/emre/.local/lib/python2.7/site-packages/pymc/flib.so: undefined symbol: __kmpc_begin
```

I'm on Ubuntu 12.04 and I have ifort 14.0.3 installed.

**Comment by fonnesbeck** [comment]
It looks like there was an issue with your Fortran compiler. I'd recommend building with gfortran, if you can. In principle, you should be able to compile with an Intel compiler, but I have never done it (nor do I know anyone who has) and have no means for getting to the bottom of the issue.

**Comment by esafak** [comment]
I see. Is it possible to do this with pip? I tried `pip install --user --install-option="--fcompiler gfortran" pymc`.

**Comment by fonnesbeck** [comment]
Are you still having issues with this? If so, provide some details and re-open.
