### ISSUE TITLE
Deterministic variables computed non-analytically

### ISSUE THREAD

**Issue by jasonmhite** [pymc-devs/pymc3#622]
I'd like to be able to define deterministic variables with values that are computed non-analytically. An example might be via calling an external code or via an iterative scheme. In the 2.0 series this was easy, since you could basically decorate any function with the `Deterministic` decorator and in its body it could do whatever you like, e.g. farming out to an external code via `subprocess` calls. This is an extremely valuable capability because it lets you perform tasks like data calibration using PyMC on code packages that model real phenomena, which often can't be expressed analytically.

I'm trying the 3.0 branch and I'd like to be able to do the same thing. However, given that PyMC3 represents the model as a Theano expression graph I can't seem to figure out how to do this. I've tried lots of manipulations and even adding in some new classes attempting to circumvent Theano, but it doesn't work.

Could you provide some guidance here? At least point me in the direction of what I need to implement... I have a decent understanding of the code for PyMC and I know a lot about MCMC, so I don't mind adding it myself if this isn't already possible.

**Comment by twiecki** [comment]
You can do this using `as_op`:
https://github.com/pymc-devs/pymc/blob/master/pymc/examples/disaster_model_arbitrary_deterministic.py

**Comment by jasonmhite** [comment]
Thanks, I figured it was some trick with Theano, but I just couldn't find it.
