### ISSUE TITLE
Docstring format

### ISSUE THREAD

**Issue by sczesla** [pymc-devs/pymc3#64]
Dear all,

first of all, thanks for this great package, which I enjoy much.

Do you use a fixed docstring format to generate API documentation? If
I just did not find it, please give me a hint. If not, do you have any intention
to use, e.g., the numpydoc format in the future?

Best regards,
Stefan

**Comment by fonnesbeck** [comment]
We endeavor to use the numpy docstring format, but I'm sure there are places we have been inconsistent.
