### ISSUE TITLE
negative binomial documentation 

### ISSUE THREAD

**Issue by piantado** [pymc-devs/pymc3#652]
I believe there is an error in the negative_binomial_like documentation. I think it should read

:math:`\mu=rp/(1-p)`

instead of

:math:`\mu=r(1-p)/p`

**Comment by twiecki** [comment]
Yes, you're correct. Thanks for pointing that out. Want to do a pull request for this change?

**Comment by fonnesbeck** [comment]
Taken care of it.

**Comment by piantado** [comment]
Thank you!
