### ISSUE TITLE
Binomial distribution ignores prior

### ISSUE THREAD

**Issue by mbillingr** [pymc-devs/pymc3#654]
I am trying to infer `p` from a binomial distribution with `n` and `k` given.
The posterior always looks like it came from a uniform prior, but I would expect the posterior to be more concentrated for more informative priors (see example below).

When using normal distributions instead of beta/binomial distributions with unknown mean I get expected results.

Am I doing something wrong, or is there a problem with the binomial distribution? Is there a workaround?
**edit:** I'm using PyMC 2.3.3 
**update:** PyMC 2.2 gives expected results.

``` python
    from pymc import Binomial, Beta, MCMC
    import matplotlib.pyplot as plt
    import numpy as np

    informed = Beta('informed', alpha=10, beta=10)
    result1 = Binomial('result1', n=10, p=informed, value=5, observed=True)

    uninformed = Beta('uninformed', alpha=1, beta=1)
    result2 = Binomial('result1', n=10, p=uninformed, value=5, observed=True)

    expected = Beta('expected', alpha=15, beta=15)

    model = MCMC([expected, informed, uninformed, result1, result2])
    model.sample(iter=20000, burn=5000)

    plt.title('$p$')
    plt.hist(model.trace('expected')[:], 30, label="expected posterior (informed prior)", normed=True)
    plt.hist(model.trace('informed')[:], 30, label="posterior (informed prior)", normed=True)
    plt.hist(model.trace('uninformed')[:], 30, label="posterior (uninformed prior)", normed=True)
    plt.legend()
    plt.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/2392396/5299918/b84d5ab8-7bcb-11e4-9e19-e3ad1e5ff396.png)

**Comment by fonnesbeck** [comment]
I cannot replicate this with the current version (2.3.4):

![binomial](http://d.pr/i/1klVw+)

Can you upgrade to the current version and see what you get?

```
pip install -U git+git://github.com/pymc-devs/pymc.git@2.3 
```

**Comment by mbillingr** [comment]
I have a Windows machine at work and was not able to get the Fortran stuff going. Therefore, I'm limited to the precompiled releases that come with conda (2.2) or binstar (2.3.3).

That just made me think... could be a problem with the binstar package.

I'll give the current version a try on my Linux machine at home.

**Comment by mbillingr** [comment]
On Arch Linux everything is consistently fine with all versions of pymc on both python 2 and 3.

I will try to compile the sources on Windows once again to verify if this is a package issue.

**Comment by fonnesbeck** [comment]
I know we were having a number of issues with 2.3.3, including with the binomial in particular, which is why we are encouraging folks to use 2.3.4 or the current 2.3 branch. We are working on conda builds, but are having some Fortran issues.

**Comment by mbillingr** [comment]
Managed to build the current 2.3 branch on Windows and everything seems to be working fine.

(Give and take some Python 3 compatibility issues, but those were caused by numpy.)
