### ISSUE TITLE
Does pymc support DBN models?

### ISSUE THREAD

**Issue by hitalex** [pymc-devs/pymc3#664]
Does pymc support DBN models, like HMM and its variants?

**Comment by twiecki** [comment]
You can certainly code those up but the samplers are not optimized for this type of problem (you probably want Gibbs sampling, which you could write).

**Comment by hitalex** [comment]
I read the [doc](http://pymc-devs.github.io/pymc/modelfitting.html#gibbs-step-methods) and find that Gibbs sampler is under development right now. Do you have any idea that Gibbs sampler will be ready to use?

**Comment by twiecki** [comment]
Those are in pymc 2 but I don't think they are what you need for HMM.
