### ISSUE TITLE
Python 2.7.9 |Anaconda 2.1.0 cannot import pymc succesfully

### ISSUE THREAD

**Issue by attilacsordas** [pymc-devs/pymc3#666]
Wanted to get up to speed with PyMC today quickly, instead I ran into a 1-2 hour long installation/PyCharm/python versions/packages/modules hell: ended up trying out Anaconda due to https://github.com/pymc-devs/pymc/issues/642 and added it to PyCharm just to be able to run the disaster example http://pymc-devs.github.io/pymc/tutorial.html#an-example-statistical-model

so after 'conda install -c https://conda.binstar.org/fonnesbeck pymc'
when trying to run the tests on the python command line I get:

> > > import pymc
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/anaconda/lib/python2.7/site-packages/pymc/**init**.py", line 30, in <module>
> > >     from .CommonDeterministics import *
> > >   File "/anaconda/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
> > >     from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
> > >   File "/anaconda/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
> > >     from . import flib
> > > ImportError: dlopen(/anaconda/lib/python2.7/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libquadmath.0.dylib
> > >   Referenced from: /anaconda/lib/python2.7/site-packages/pymc/flib.so
> > >   Reason: image not found

any help is appreciated

**Comment by twiecki** [comment]
Can you try instead:
conda install -c asmeurer pymc

**Comment by attilacsordas** [comment]
hey, that did it, thanks!
in the meantime I figured out how to set up PyMC properly with regular Python 2.7.5 by reinstalling many things, homebrew, fortran compiler, python modules so the issue became less pressing. But Anaconda seemed like a cool scientific option.
