### ISSUE TITLE
Error in "pymc.gp.Covariance.py"  when "Uo_Cxo" is referenced before assignment

### ISSUE THREAD

**Issue by sobri0t4** [pymc-devs/pymc3#68]
Worked in previous versions. Now we are missing these two before line ~557:

Cxo = self.eval_fun(self.obs_mesh, x, **self.params) 
Uo_Cxo = trisolve(self.Uo, Cxo, uplo='U', transa='T')

**Comment by fonnesbeck** [comment]
I _think_ I addressed this in cd07a7a94bb000579969a772827c07e26cb740cc but check to make sure.
