### ISSUE TITLE
Python 2.5 does not have package 'multiprocessing' by default

### ISSUE THREAD

**Issue by jskowron** [pymc-devs/pymc3#69]
File INSTALL.rst says in "Dependencies" section:
- Python_ version 2.5 or 2.6.
  However Python 2.5 does not have "multiprocessing" package by default. Hence error immediately after my new installation:

/usr/lib64/python2.5/site-packages/pymc/**init**.py in <module>()
     16 
     17 # Core modules
---> 18 from threadpool import *
     19 import os
     20 import pymc

/usr/lib64/python2.5/site-packages/pymc/threadpool.py in <module>()
    309     **PyMCThreadPool** = ThreadPool(int(os.environ['OMP_NUM_THREADS']))
    310 except:
--> 311     import multiprocessing
    312     **PyMCThreadPool** = ThreadPool(multiprocessing.cpu_count())
    313 

ImportError: No module named multiprocessing

I have installed today (Nov 29th, 2011) from the sources from: git clone git://github.com/pymc-devs/pymc.git pymc
at Fedora 10 Python 2.5.2 x86_64

**Comment by fonnesbeck** [comment]
Handled error in b56cd75a0e8798ab5b1251bde731fd698a73d083
