### ISSUE TITLE
Log-probability derivation of the minimum statistic of i.i.d. discrete variables

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc3#6959]
### Description

Extensions of #6790 and #6846.

For reference: the survival function $P(X_{(1)} > 1)$ can be written as:

$$
P(X_{(1)} > x) = P(\text{all of } X_1, \dots, X_n > x) = \prod_{i=1}^n P(X_i > x) = \prod_{i=1}^n \big(1 - P(X_i \leq x)\big) = \big(1 - \text{CDF}(x)\big)^n \, .
$$

The pmf of $X_{(1)}$ can then be derived for any $x$ in $X$'s support as follows:

$$
P(X_{(1)}  = x) = P(X_{(1)} \geq x) - P(X_{(1)} > x) =  P(X_{(1)} > x - 1) - P(X_{(1)} > x) = \big(1 - \text{CDF}(x - 1)\big)^n - \big(1 - \text{CDF}(x)\big)^n
$$

An appropriate test akin to [test_max_discrete](https://github.com/pymc-devs/pymc/pull/6790/files#diff-0cb3b2f62ae2e454acb992b6a31d0c8b5ec3e8406b820be26227779fe998bcd9R240) can be spun from this

CC @Dhruvanshu-Joshi @ricardoV94

**Comment by ricardoV94** [comment]
Closed via #6968
