### ISSUE TITLE
Python 2.5.2 does not have 'warnings.catch_warnings()'

### ISSUE THREAD

**Issue by jskowron** [pymc-devs/pymc3#70]
File INSTALL.rst says in "Dependencies" section:
`Python`_ version 2.5 or 2.6.
However warnings module in Python 2.5.2 does not have a function "warnings.catch_warnings()". Hence error immediately after my new installation:

/usr/lib64/python2.5/site-packages/pymc/**init**.pyc in <module>()
     35 
     36 
---> 37 from tests import test
     38 
     39 # Utilities modules

/usr/lib64/python2.5/site-packages/pymc/tests/**init**.py in <module>()
      6     import numpy
      7     numpy.seterr(divide = 'raise', invalid = 'raise')
----> 8     with warnings.catch_warnings():
      9         warnings.simplefilter('ignore')
     10         test = Tester().test

AttributeError: 'module' object has no attribute 'catch_warnings'

I have installed today (Nov 29th, 2011) from the sources from: git clone git://github.com/pymc-devs/pymc.git pymc
at Fedora 10 Python 2.5.2 x86_64

**Comment by fonnesbeck** [comment]
We use catch_warnings throughout the test suite, so I am going to handle this error but Python 2.5 will not be able to use the test suite.

**Comment by fonnesbeck** [comment]
OK, fixed in a97f57fa6c17c857042a46e34a8195651d76ccb2. You should be able to test now.
