### ISSUE TITLE
No 'with' statement in Python 2.5

### ISSUE THREAD

**Issue by jskowron** [pymc-devs/pymc3#71]
For example, line 17 in file pymc/tests/test_adaptive.py is using 'with' statement. My Python 2.5.2 does not support this.

if **name** == '**main**':
    with warnings.catch_warnings():
        warnings.simplefilter('ignore',  FutureWarning)
        nose.runmodule()

This could be helpful to solve both, 'with' problem and 'catch_warnings': 
http://stackoverflow.com/questions/2059675/catching-warnings-pre-python-2-6

**Comment by fonnesbeck** [comment]
Thanks for the bug reports. Obviously we do not have many (any?) 2.5 users currently. I will address these, but will probably also make 2.6 the minimum requirement for the 2.2 release.

**Comment by jskowron** [comment]
Sorry for all problems. These came from my fixed setup, where a computer I am working with is in my Institute's lab and I really cannot update the system. Upgrading Python is also a huge work.
In my second institute most of the computers run Centos 5.2/5.3, this has Python 2.4.3 by default !!? This is nightmare. And all cluster nodes have Python 2.4.3 as well, so running python based jobs is hard, and sometimes impossible.

Moving up to 2.6 is probably a good idea, since I can imagine that keeping legacy support can use up lots of time. 
As you have pointed out, there is probably not many users with old machines like me. Other possibility is that, there are, but they do not install from git sources, only from packages like: 2.0 or 2.1beta.

The newly released CentOS 6 has Python 2.6 as a base. This means that most of the computers at institutions and cluster computers will run python 2.6 for years to come (till 2017 I believe?). So, in the future, moving away from 2.6 up will also be hard.

**Comment by fonnesbeck** [comment]
OK, fixed in 820ff23ecc6ef68e4ef59af03f516fa54b7e997f
