### ISSUE TITLE
issue with latest scipy(.misc).derivative

### ISSUE THREAD

**Issue by doctorBenton** [pymc-devs/pymc3#73]
I've just had to do a clean reinstall of everything on a macbookpro.

I'm doing through macports.  Here's what i have that is relevant:
  python27 @2.7.2_3 (active)
  py27-numpy @1.6.1_1 (active)
  py27-scipy @0.10.0_0+gcc44 (active)
  py27-matplotlib @1.1.0_0+ghostscript+latex+tkinter (active)
  py27-pymc @2.0_0+gcc44 (active)

The problem is that pymc fails to load normally, because it says it can't find scipy, with the error message:
    normApprox = pymc.NormApprox( model )
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/NormalApproximation.py", line 483, in **init**
    raise ImportError, 'Scipy must be installed to use NormApprox and MAP.'
ImportError: Scipy must be installed to use NormApprox and MAP.

I think the problem is that in the latest scipy, scipy.derivate has moved to scipy.misc.derivative.

I haven't been brave enough to try altering the source code, but i find the error disappears if i do the following:

import scipy
from scipy.misc import derivative
scipy.derivative = derivative

I've no idea what (if any) difference there is between the old scipy.derivative, and the new sci.misc.derivative, but everything seems okay-ish in any case.

Hope that's helpful, even if it's somewhat mundane.

**Comment by fonnesbeck** [comment]
This bug does not exist in more recent versions of PyMC. I encourage you to either build it yourself from the source, or install the Scipy Superpack if you are running Lion: http://fonnesbeck.github.com/ScipySuperpack/

**Comment by doctorBenton** [comment]
Hi Chris --

Thanks for this update.

A quick query.  I've just got a new machine in the last couple months,
and this time i'm trying out using macports to manage all my
everything.

Do you know offhand how well the superpack scripts play with macports?
 I've really struggled with multiple package managers in the past
(although that was when i was still using the EPD as my base), and
would really like to avoid going down that road again.

Thanks,

drB

---

"Things will not be necessarily continuous.
The fact that they are something other than continuous
ought not to be characterised as a pause.
There will be some things that people will see.
There will be some things that people won't see.
And life goes on."
    -- Donald Rumsfeld

---

"In theory there is no difference between theory and practice.
In practice there is."
   -- Yogi Berra and/or Albert Einstein

---

On 12 January 2012 06:23, Chris Fonnesbeck
reply@reply.github.com
wrote:

**Comment by fonnesbeck** [comment]
I am not sure how well it plays with MacPorts, as I always use the Python that ships with the current version of OSX. If you do use MacPorts, you may want to ensure that the Python it installs is version 2.7, however. 

## 

Chris Fonnesbeck
Department of Biostatistics
Vanderbilt University School of Medicine
