### ISSUE TITLE
beta should be defined as a rate parameter for the Gamma distribution

### ISSUE THREAD

**Issue by isofer** [pymc-devs/pymc3#79]
In the documentation of the Gamma variable beta is defined as a scale parameter.
according to Wikipedia (http://en.wikipedia.org/wiki/Gamma_distribution) it should be defined as a rate parameter. The scale parameter is 1/beta.

**Comment by fonnesbeck** [comment]
Fixed in 003e886cd4b023a8ada2d3f5141e9ef057c57a45 for both the gamma and exponential.
