### ISSUE TITLE
gradient calculations in fortran sometimes permutes results with ndim > 2

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc3#8]
I think this is due to a fortran/c array ordering issue. 

Example: 

```
In [5]: x = array([[1, 2, 3],
       [4, 5, 6]])

In [7]: reshape(flib.normal_grad_mu(x, zeros(x.shape), 1.0),x.shape)
Out[7]: 
array([[ 1.,  4.,  2.],
       [ 5.,  3.,  6.]])
```

This to me is another reason why moving to numexpr or similar is a good idea.

**Comment by fonnesbeck** [comment]
You won't get any argument from me, thought Anand's point about the cost:benefit of moving so much code that generally works already. I would envision a slow transition to cython or similar, starting with functions like this.

**Comment by apatil** [comment]
It's safest to set the order,

```
x = asarray([[1, 2, 3],
            [4, 5, 6]], order='F')
```

for anything multidimensional that's going to be passed to f2py. This only makes a copy if it has to.

**Comment by apatil** [comment]
You can check whether an ndarray will be handled correctly by f2py with

```
x.flags['F_CONTIGUOUS']
```

**Comment by apatil** [comment]
How is the numexpr_dist branch comparing to the master branch in terms of speed these days?

**Comment by jsalvatier** [comment]
I haven't tested it yet, since I put it together this weekend. It does have most of the common distributions. I'm not sure what the best way to do a comprehensive speed test is. I guess just pick a large array size and run the likelihoods.

**Comment by apatil** [comment]
It's a big change... it would eventually be nice to see all the likelihoods that are implemented, for arrays of size 1, 10, ... 100000, with the smaller ones averaged over a number of trials.

**Comment by jsalvatier** [comment]
That's a good point, I will make sure to measure speed for different array sizes.

**Comment by fonnesbeck** [comment]
Can we close this?

**Comment by jsalvatier** [comment]
I think so, no one is working on it and it doesn't seem to have had a problem since.
