### ISSUE TITLE
linalg_utils missing dpotrf_wrap

### ISSUE THREAD

**Issue by mcfarljm** [pymc-devs/pymc3#9]
On Fedora 13, with the latest development version from github, I get this import error when importing pymc:
## In [1]: import pymc

ImportError                               Traceback (most recent call last)

/usr/lib/python2.6/site-packages/pymc/**init**.pyc in <module>()
     45 from CircularStochastic import *
     46 import distributions
---> 47 import gp
     48 
     49 # Optional modules

/usr/lib/python2.6/site-packages/pymc/gp/**init**.py in <module>()
     20 from GPutils import *
     21 from Mean import *
---> 22 from Covariance import *
     23 from BasisCovariance import *
     24 from FullRankCovariance import *

/usr/lib/python2.6/site-packages/pymc/gp/Covariance.py in <module>()
      8 from numpy.linalg import cholesky, LinAlgError
      9 from GPutils import regularize_array, trisolve, square_and_sum
---> 10 from linalg_utils import diag_call, dpotrf_wrap
     11 from incomplete_chol import ichol, ichol_continue
     12 

ImportError: cannot import name dpotrf_wrap

I can verify using nm that linalg_utils.so does not contain dpotrf_wrap.

**Comment by apatil** [comment]
I don't get this error. Were there errors during compilation?

**Comment by mcfarljm** [comment]
No, I didn't notice any build errors on the console.  Is there a log file I can check?

**Comment by mcfarljm** [comment]
Anand: the difference may be that my system doesn't have a system lapack, so it's using different code in setup.py.  Can you try to recreate the issue by forcing lapack_info==False?  It looks like on my build, blas_wrap.o isn't getting included in linalg_utils.so, so probably has something to do with setup.py...

**Comment by mcfarljm** [comment]
OK, I think the fix is to add the source for blas_wrap.f to linalg_utils at line 80 of setup.py:
config.add_extension(name='gp.linalg_utils',sources=['pymc/gp/linalg_utils.f', 'pymc/blas_wrap.f'] + f_sources)

(I also had to update the timestap on blas_wrap.f or else re-running setup.py was not triggering a re-generation of linalg_utilsmodule.c; seems like a minor deficiency in the distutils build system.)

**Comment by apatil** [comment]
Thanks John, could you please verify that commit 7d3755cdb7d174475c0f35b9eb844304af6f8b13 fixes the problem?

**Comment by mcfarljm** [comment]
Yes, that works for me.

**Comment by apatil** [comment]
Cool.

**Comment by mcfarljm** [comment]
Closing: fixed by above commit
