### ISSUE TITLE
Unclear docs for Goodness of Fit

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#94]
I read through this section of the docs but couldn't really make heads or tails of it:
http://pymc-devs.github.com/pymc/modelchecking.html#goodness-of-fit

First, simulated and real data is introduced in the first example. Then the Freeman-Tukey test is described without any specification of what the parameters mean or what is indexed over. Following that, the discrepancy function is introduced which requires passing of an expected argument of which I also don't know where that is supposed to come from.

If I may suggest an improvement, I think it would make the whole story more clear if the following code examples for pymc.discrepancy() would build on the example introduced in the beginning of the section.

**Comment by fonnesbeck** [comment]
I have tried to clarify the GOF discrepancy and the sample code. Have a look at the current version.
